### ISSUE TITLE
When "edit" makes a temporary copy of a file, keep its extension intact

### ISSUE THREAD

**Issue by noelk** [lavv17/lftp#103]
Hello,

a forwarded wishlist request from https://bugs.debian.org/770910

"Thank you very much for all your work on lftp.

When I run an lftp command like "edit index.php.new", lftp creates a
temporary local copy of the remote file in my /tmp directory.  It
gives it a name like "edit.tmp.4075".  Sadly, some text editors make
decisions regarding syntax highlighting simply by looking at the
filename extension, and won't highlight a ".4075" file at all.

Please preserve the remote file's extension when creating the local
copy.  Instead of calling the local copy something like
"edit.tmp.4075", call it "edit.tmp.4075.php.new".

Kind regards,
Jason Spiro:  computer consultant."

**Comment by jasonspiro** [comment]
Please assume that everything after the first dot character is the extension. So the extension is `php.new` in the example I provided.

**Comment by lavv17** [comment]
1510cd44871df0d6a658bc18fdd653128beff460 should solve the issue.

**Comment by jasonspiro** [comment]
Thank you very much!  :)
