### ISSUE TITLE
Please offer filename tab completion for users of the "edit" command

### ISSUE THREAD

**Issue by jasonspiro** [lavv17/lftp#107]
I am using lftp packaged by Debian.  The Debian package version number is 4.3.6-1+deb7u2.

In lftp, filename tab completion works wlth other commands, such as `cd` &mdash; but doesn't seem to work with the `edit` command.

When I type `edit ind` and press Tab, nothing happens.  It would be wonderful if lftp would tab-complete the filename I am entering by and show onscreen the full filename, `index.html`.

**Comment by lavv17** [comment]
1510cd44871df0d6a658bc18fdd653128beff460 should solve the issue.
