### ISSUE TITLE
implement global bookmarks

### ISSUE THREAD

**Issue by lkraav** [lavv17/lftp#111]
This is for supporting centralized server-based remote work scenario. There are bookmarks that should be shared to reduce maintenance burdain. I'm thinking symlinking to everybody's homedir is an option right now, but having lftp read something like /etc/lftp/bookmarks would be useful. Final bookmark list available in the app should be a merge between global and local bookmark list.

Thoughts?

**Comment by lavv17** [comment]
I think it is possible to add bookmark commands to the global /etc/lftp.conf

**Comment by lkraav** [comment]
PS I noticed just recently that "bookmark edit" will try to open ~/.lftp/bookmarks, even though "bookmark list" shows bookmarks from ~/.local/share/lftp/bookmarks. Shouldn't it load bookmarks for editing from share?

**Comment by lavv17** [comment]
@lkraav 4dc2632 should fix the issue with "bookmark edit"
