### ISSUE TITLE
The "edit" command should call "local mkdir -f ~/.lftp" upon every invocation

### ISSUE THREAD

**Issue by jasonspiro** [lavv17/lftp#113]
If the `edit` macro fails because ~/.lftp doesn't yet exist, please don't just fail with a `No such file or directory` error. This is too confusing: the user may not know which file or directory doesn't exist. (I, for one, didn't know.) Instead, please do something more understandable.

Suggested solution:

Please change the `edit` macro to call `local mkdir -f ~/.lftp` upon every invocation. This will make sure that the directory exists. (The `-f` flag causes mkdir not to display any error message, even if the directory already existed.)

Thank you!

**Comment by lavv17** [comment]
I think the proper way to fix it would be to implement "edit" as an built-in command instead of an alias.

**Comment by jasonspiro** [comment]
Why would this be desirable?  My suggested solution seems to work fine.  :)

**Comment by lavv17** [comment]
It would fix several issues at once

**Comment by lavv17** [comment]
1510cd44871df0d6a658bc18fdd653128beff460 should solve the issue.

**Comment by jasonspiro** [comment]
Cool.  Thank you very much for the fix.  As well, thank you very much for continuing to maintain lftp &mdash; my favorite FTP client in the world!  :)
