### ISSUE TITLE
saves unknown host's fingerprint in known_hosts without any prompt

### ISSUE THREAD

**Issue by noelk** [lavv17/lftp#116]
Hello,
a forwarded Debian bug https://bugs.debian.org/774769

--8<--
From the src/SSH_Access.cc file:
47: const char *y="(yes/no)?";
73: if(s>=y_len && !strncasecmp(b+s-y_len,y,y_len))
74: {
75:     pty_recv_buf->Put("yes\n");
76:     pty_send_buf->Put("yes\n");
77:     return m;
78: }

Not only does it make a particular SFTP file transfer insecure, but also
any future connection via any SSH client.

After enabling debug (the "yes" answer generated automatically):
#v+
$ lftp sftp://mszewczyk@localhost:22203
Password: 
lftp mszewczyk@localhost:~> debug
lftp mszewczyk@localhost:~> ls
---- Running connect program (ssh -a -x -s -l mszewczyk -p 22203 localhost sftp)
---> sending a packet, length=5, type=1(INIT), id=0
<--- The authenticity of host '[localhost]:22203 ([::1]:22203)' can't be established.
<--- RSA key fingerprint is 84:a2:ec:3d:98:1e:95:e6:e4:68:d9:a4:31:92:f7:8d.
<--- Are you sure you want to continue connecting (yes/no)? yes
<--- 
<--- Warning: Permanently added '[localhost]:22203' (RSA) to the list of known hosts.
#v-
--8<--

IMHO the user should be asked .

thx.

**Comment by lavv17** [comment]
lftp does not ask user asynchronously by design. I can make a setting to disable accessing unknown hosts by default.

**Comment by wodny** [comment]
The setting sounds good. Would you be willing to make this setting enabled by default? I know it may surprise some users but I think the whole point of using SFTP is the security it gives. For example "ssl:verify-certificate" seems to be enabled by default.

**Comment by nwgat** [comment]
I agree

**Comment by lavv17** [comment]
Please test bc7b476

**Comment by wodny** [comment]
Seems to work. I get `Fatal error: Host key verification failed` when `auto-confirm` is set to `no`. Thank you.

(BTW, I had to modify `GETTEXT_MACRO_VERSION` in `po/Makefile.in` if that is of any significance)

**Comment by wheelq** [comment]
Will have to check how it responds upon changed key, will it also auto-accept it

**Comment by wodny** [comment]
SSH doesn't ask questions if a key has changed.

openssh-client  1:6.7p1-3
lftp  4.6.0-1

    $ ssh the_host
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
    Someone could be eavesdropping on you right now (man-in-the-middle attack)!
    It is also possible that a host key has just been changed.
    The fingerprint for the ECDSA key sent by the remote host is
    a5:2e:94:6f:e9:05:bb:78:6e:45:d5:6e:23:32:4e:fe.
    Please contact your system administrator.
    Add correct host key in /home/wodny/.ssh/known_hosts to get rid of this message.
    Offending ECDSA key in /home/wodny/.ssh/known_hosts:367
      remove with: ssh-keygen -f "/home/wodny/.ssh/known_hosts" -R [1.2.3.4]:22
    ECDSA host key for [1.2.3.4]:22 has changed and you have requested strict checking.
    Host key verification failed.
    
    wodny@orkisz:4:~$ lftp sftp://the_host
    lftp the_host:~> debug
    lftp the_host:~> rels
    ---- Running connect program (ssh -a -x -s the_host sftp)
    ---> sending a packet, length=5, type=1(INIT), id=0
    <--- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    <--- @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
    <--- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    <--- IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
    <--- Someone could be eavesdropping on you right now (man-in-the-middle attack)!
    <--- It is also possible that a host key has just been changed.
    <--- The fingerprint for the ECDSA key sent by the remote host is
    <--- a5:2e:94:6f:e9:05:bb:78:6e:45:d5:6e:23:32:4e:fe.
    <--- Please contact your system administrator.
    <--- Add correct host key in /home/wodny/.ssh/known_hosts to get rid of this message.
    <--- Offending ECDSA key in /home/wodny/.ssh/known_hosts:367
    <---   remove with: ssh-keygen -f "/home/wodny/.ssh/known_hosts" -R [1.2.3.4]:22
    <--- ECDSA host key for [1.2.3.4]:22 has changed and you have requested strict checking.
    <--- Host key verification failed.
    rels: Fatal error: Host key verification failed
    ---- Disconnecting
