### ISSUE TITLE
Add support for disabling sslv3 and enabling specific tls versions

### ISSUE THREAD

**Issue by pcpa** [lavv17/lftp#117]
Hi,

I created a fork and branch tls-version, and this patch
https://github.com/pcpa/lftp/commit/7c3cf33c1e9bb81685d748655f048ece9f482b28
I would like to know if you have any comments about it.
I was asked to help in finding a solution to enforcing use
of tls v1.2 for ftp clients.

**Comment by lavv17** [comment]
Thanks for the patch!
But I'd rather see a single setting for this. Something like ssl:priority with gnutls priority format. For openssl it would be needed to parse the string to convert it to openssl options.

**Comment by pcpa** [comment]
Please check if https://github.com/pcpa/lftp/commit/2ba3afabc95c2f3c88db94d2f778ac54f3451ae2 is better. I added a simple parser, in case built with OpenSSL, to understand the relevant options.

**Comment by lavv17** [comment]
I like this solution better. I have applied your patch with some modifications on top, thanks!

**Comment by uhliarik** [comment]
I'm not sure, if this solution works. 

I'm getting this error:
```
gnutls_priority_set_direct(`NORMAL:-SSL3.0:-TLS1.0:-TLS1.1:-TLS1.2'): The request is invalid.
```

```+SSL3.0``` is not a valid GNUTLS string. Valid GNUTLS string is +VERS-SSL3.0


Also, you could check return value of function gnutls_priority_set_direct in lftp_ssl.cc @ 288
```
// hack for some ftp servers
      const char *auth=ResMgr::Query("ftp:ssl-auth", hostname);
      if(auth && !strncmp(auth, "SSL", 3))
         gnutls_priority_set_direct(session, "NORMAL:+SSL3.0:-TLS1.0:-TLS1.1:-TLS1.2",0);
```

**Comment by lavv17** [comment]
Please try https://github.com/lavv17/lftp/commit/f1085c490d846545b114219fd1c9e9409c52b124
