### ISSUE TITLE
issue with resume when IP changes.

### ISSUE THREAD

**Issue by vinaymcp** [lavv17/lftp#118]
Hello All,

Lftp works perfect with v 4.3.3 but with version 4.6.0 with new settings  xfer:use-temp-file and xfer:temp-file-name , i am not able to resume the upload on modem network.

My testing scenario is as follows.

1. Connected 1st modem.
2. Started the upload process.
3. Disconnected the 1st modem while uploading was in process.
4. Connected 2nd modem.
5. Upload does not resume, it just hangs.

This used to work very well on v4.3.3

Any approx dates when the latest stable version will be released ?

Thanks
Vinay

**Comment by lavv17** [comment]
Can you provide a debug log from lftp when it happens?

**Comment by vinaymcp** [comment]
modem1 to modem2  no resume


lftp a3bio@50.56.33.64:~> put -O /home/rpms/test_lftp /home/test.tar.gz
---- Connecting to 50.56.33.64 (50.56.33.64) port 21
<--- 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
<--- 220-You are user number 2 of 50 allowed.
<--- 220-Local time is now 12:41. Server port: 21.
<--- 220-This is a private system - No anonymous login
<--- 220-IPv6 connections are also welcome on this server.
<--- 220 You will be disconnected after 15 minutes of inactivity.
---> FEAT
<--- 211-Extensions supported:                       
<---  EPRT
<---  IDLE
<---  MDTM
<---  SIZE
<---  REST STREAM
<---  MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
<---  MLSD
<---  AUTH TLS
<---  PBSZ
<---  PROT
<---  UTF8
<---  TVFS
<---  ESTA
<---  PASV
<---  EPSV
<---  SPSV
<---  ESTP
<--- 211 End.
---> AUTH TLS
<--- 500 This security scheme is not implemented    
---> OPTS UTF8 ON
<--- 200 OK, UTF-8 enabled                     
---> OPTS MLST type;size;modify;UNIX.mode;UNIX.uid;UNIX.gid
<--- 200  MLST OPTS type;size;sizd;modify;UNIX.mode;UNIX.uid;UNIX.gid;unique;
---> USER a3bio
<--- 331 User a3bio OK. Password required      
---> PASS test
<--- 230-User a3bio has group access to:  a3bio          
<--- 230 OK. Current directory is /home/rpms/buffer
---> TYPE I
<--- 200 TYPE is now 8-bit binary                        
---> PASV
<--- 227 Entering Passive Mode (50,56,33,64,85,237)      
---- Connecting data socket to (50.56.33.64) port 21997
---- Data connection established                           
---> ALLO 25548800
<--- 200 A L'HUILE                                       
---> STOR /home/rpms/test_lftp/test.tar.gz
<--- 150 Accepted data connection                        
**** Timeout - reconnecting                                          
---- Closing idle connection                                         
`/home/test.tar.gz' at 7747816 (30%) [Sending data]

**Comment by lavv17** [comment]
should be fixed with b35f277, please test

**Comment by vinaymcp** [comment]
I just tested it, it resumes back on first disconnection. on second time disconnection it does not resume. It starts the upload from 0%

Attached is the log.

debuglog.txt

lftp testing@50.56.33.44:~> put -O /home/test_lftp /home/test.tar.gz
---> PASV
<--- 227 Entering Passive Mode (50,56,33,44,102,37)      
---- Connecting data socket to (50.56.33.44) port 26149
---- Data connection established                           
---> ALLO 25548800
<--- 200 A L'HUILE                                       
---> STOR /home/test_lftp/test.tar.gz
<--- 150 Accepted data connection                        
**** Timeout - reconnecting                                         
---- Closing data socket
---- Closing control socket
---- Connecting to 50.56.33.44 (50.56.33.44) port 21
<--- 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
<--- 220-You are user number 2 of 50 allowed.
<--- 220-Local time is now 11:41. Server port: 21.
<--- 220-This is a private system - No anonymous login
<--- 220-IPv6 connections are also welcome on this server.
<--- 220 You will be disconnected after 15 minutes of inactivity.
---> FEAT
<--- 211-Extensions supported:                              
<---  EPRT
<---  IDLE
<---  MDTM
<---  SIZE
<---  REST STREAM
<---  MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
<---  MLSD
<---  AUTH TLS
<---  PBSZ
<---  PROT
<---  UTF8
<---  TVFS
<---  ESTA
<---  PASV
<---  EPSV
<---  SPSV
<---  ESTP
<--- 211 End.
---> AUTH TLS
<--- 500 This security scheme is not implemented           
---> OPTS UTF8 ON
<--- 200 OK, UTF-8 enabled                            
---> OPTS MLST type;size;modify;UNIX.mode;UNIX.uid;UNIX.gid
<--- 200  MLST OPTS type;size;sizd;modify;UNIX.mode;UNIX.uid;UNIX.gid;unique;
---> USER testing
<--- 331 User testing OK. Password required             
---> PASS testing
<--- 230-User testing has group access to:  testing                 
<--- 230 OK. Current directory is /home/rpms/buffer
---> TYPE I
<--- 200 TYPE is now 8-bit binary                               
---> SIZE /home/test_lftp/test.tar.gz
<--- 213 18173084                                               
copy: put rolled back to 3600104, seeking get accordingly
copy: get rolled back to 3600104, seeking put accordingly
---> PASV
<--- 227 Entering Passive Mode (50,56,33,44,52,36)              
---- Connecting data socket to (50.56.33.44) port 13348
---- Data connection established                                  
---> ALLO 25548800
<--- 200 A L'HUILE                                              
---> REST 3600104
<--- 350 Restarting at 3600104                                  
---> STOR /home/test_lftp/test.tar.gz
<--- 150 Accepted data connection                                               
**** Timeout - reconnecting                                            
---- Closing data socket
---- Closing control socket
---- Connecting to 50.56.33.44 (50.56.33.44) port 21
<--- 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
<--- 220-You are user number 3 of 50 allowed.
<--- 220-Local time is now 11:47. Server port: 21.
<--- 220-This is a private system - No anonymous login
<--- 220-IPv6 connections are also welcome on this server.
<--- 220 You will be disconnected after 15 minutes of inactivity.
---> FEAT
<--- 211-Extensions supported:                               
<---  EPRT
<---  IDLE
<---  MDTM
<---  SIZE
<---  REST STREAM
<---  MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
<---  MLSD
<---  AUTH TLS
<---  PBSZ
<---  PROT
<---  UTF8
<---  TVFS
<---  ESTA
<---  PASV
<---  EPSV
<---  SPSV
<---  ESTP
<--- 211 End.
---> AUTH TLS
<--- 500 This security scheme is not implemented            
---> OPTS UTF8 ON
<--- 200 OK, UTF-8 enabled                             
---> OPTS MLST type;size;modify;UNIX.mode;UNIX.uid;UNIX.gid
<--- 200  MLST OPTS type;size;sizd;modify;UNIX.mode;UNIX.uid;UNIX.gid;unique;
---> USER testing
<--- 331 User testing OK. Password required              
---> PASS test
<--- 230-User testing has group access to:  testing                  
<--- 230 OK. Current directory is /home/rpms/buffer
---> TYPE I
<--- 200 TYPE is now 8-bit binary                                
---> SIZE /home/test_lftp/test.tar.gz
<--- 550 Can't check for file existence                          
copy: put rolled back to 16238144, seeking get accordingly
copy: put rolled back to 0, seeking get accordingly
---> PASV
<--- 227 Entering Passive Mode (50,56,33,44,124,30)      
---- Connecting data socket to (50.56.33.44) port 31774
---- Data connection established                           
---> ALLO 25548800
<--- 200 A L'HUILE                                       
---> STOR /home/test_lftp/test.tar.gz
<--- 150 Accepted data connection                        
<--- 550 Can't check for file existence                          ta]  
copy: put rolled back to 16238144, seeking get accordingly
---- Closing data socket                                               at 19387272 (75%) 66.0K/s eta:96s [Sending data]  
<--- 226-File successfully transferred                                                    
<--- 226 362.302 seconds (measured here), 68.87 Kbytes per second
---> SITE UTIME 20150116063910 /home/test_lftp/test.tar.gz
<--- 500 UTC Only                                                                         
---> SITE UTIME /home/test_lftp/test.tar.gz 20150116063910 20150116063910 20150116063910 UTC
<--- 250 UTIME OK                                                                         
42063872 bytes transferred in 1162 seconds (35.4 KiB/s)
lftp testing@50.56.33.44:~>

**Comment by lavv17** [comment]
It looks like a server's problem. On the second retry the SIZE commend did not find the partially uploaded file, so it was re-uploaded completely.

**Comment by vinaymcp** [comment]
I tried to do the same with 4.3.3 and it worked well, but with latest
version i am facing the same issue.

**Comment by vinaymcp** [comment]
Also it resumes for first time, but from second time it does not.

this is usual pattern, always starts from 0 when disconnected for second time.

**Comment by vinaymcp** [comment]
Thanks, it works!

But only issue is it takes about 5 mins to resume the upload.

Any workaround on it ?

**Comment by lavv17** [comment]
Have you tried to adjust net:timeout setting?

**Comment by micrat** [comment]
Hello, sorry for resuming an old thread, but I have a similar issue.
In particular, if I set the suggested option: `set net:timeout 60;`, the connection is re-established sooner, but I get the following error:
`mirror: Access failed: 550 The process cannot access the file because it is being used by another process.`
and in the debug:
`<--- 550 The process cannot access the file because it is being used by another process.`
`copy: put rolled back to 2555904, seeking get accordingly`
`copy: put rolled back to 0, seeking get accordingly`
It starts the upload from 0.

Instead, if I do not set the `net:timeout` parameter, at restart (that takes longer, about 5 mins), I get another error (see the debug here-below):
`<--- 550 The system cannot find the file specified. `
`copy: put rolled back to 22015479, seeking get accordingly`
`copy: put rolled back to 0, seeking get accordingly`
And again, it starts the upload from 0.

If I manually stop lftp while is waiting to re-connect, and then I restart, the upload resumes correctly.

Could you suggest a solution for restarting the uploads without loosing the contents of the file that was previously uploaded?

(using LFTP Version 4.6.4)
Thanks
