### ISSUE TITLE
ls argument with spaces

### ISSUE THREAD

**Issue by arekm** [lavv17/lftp#121]
Hello.
mirror "some directory with spaces" works fine but:

````
 lftp> ls "test zupa"
---> #LIST test zupa
ls -la test zupa; echo '### 200'
<--- ### 200
ls: cannot access test: No such file or directory
ls: cannot access zupa: No such file or directory
copy: get hit eof
````

What is interesting is that
cls "test zupa"
works fine.

version 4.6.0

**Comment by lavv17** [comment]
It's difficult to get right. The command "ls" is expected to pass all the arguments to the server for interpretation, but it does not know how exactly the server is going to interpret it. So probably the best way to fix it is to pass the entire line (like "!" does) to the server, without any quote or white space interpretation.

**Comment by lavv17** [comment]
Please test 8e8e146

**Comment by arekm** [comment]
Works, thanks!
