### ISSUE TITLE
The file with the same name cannot be overwritten

### ISSUE THREAD

**Issue by bigmodelking** [lavv17/lftp#122]
When used the following variables and PUT command, the file with the same name in the remote sftp server can not be overwritten.

set xfer:temp-file-name .in.*
set xfer:use-temp-file yes

below error messages appear in the sftp log 
2015-01-27 12:53:03,748 mod_sftp/0.9.9[12183]: denying RENAME of '/.in.abc.tar' to '/abc.tar': '/abc.tar' already exists and client did not specify OVERWRITE flag

client: lftp-4.6.1
server: proftpd 1.3.5 with mod_sftp
Platform: solaris10

**Comment by lavv17** [comment]
Please test a07ea02 (use "set xfer:clobber yes")

**Comment by wheelq** [comment]
This is a normal behaviour

**Comment by wheelq** [comment]
What about a situation when lftp uploads the file but connection is dropped before the rename command. Would the retry setting still apply?

**Comment by lavv17** [comment]
@wheelq Yes, lftp will retry the rename. It is possible however that the first rename command was executed successfully but the status has not reached lftp, then the second rename would fail and lftp would report an error.

**Comment by bigmodelking** [comment]
HI, Lavv17
After modify SFtp.cc and recompile proftpd with 'enable-nls'. lftp can use put command then overwrite the file with same name in the remote SFTP server. Thanks.
