### ISSUE TITLE
HTTP connections to IPv6 addresses have escaped host header.

### ISSUE THREAD

**Issue by danlange** [lavv17/lftp#123]
Version 4.0.9 of lftp does not seem to support HTTP connections to IPv6 addresses.  The IP address is escaped in the Host header sent to the remote server, making the host header invalid.  For example:
lftp -d -u test,test http://[dead::250:56ff:feb8:6c92] -p 80
---- Connecting to dead::250:56ff:feb8:6c92 (dead::250:56ff:feb8:6c92) port 80
---- Sending request...
---> HEAD / HTTP/1.1
---> Host: dead%3A%3A250%3A56ff%3Afeb8%3A6c92:80
---> User-Agent: lftp/4.0.9
---> Accept: */*
---> Authorization: Basic dGVzdDp0ZXN0
---> Connection: keep-alive
---> 
<--- HTTP/1.1 400 Bad Request
<--- Content-Type: text/html
<--- Content-Length: 349
<--- Connection: close
<--- Date: Thu, 29 Jan 2015 04:02:50 GMT
<--- Server: lighttpd/1.4.35
<--- 
cd: Operation not supported: 400 Bad Request (HEAD)
---- Closing HTTP connection

**Comment by lavv17** [comment]
should be fixed in 2ef16b6c829eec8770b0198d32b585492bb7ecbb, please test.

**Comment by danlange** [comment]
Thanks for fixing it!  I am happy to test it, however I am unable to build lftp sucessfully in a CentOS 6.6 environment.  Here is what I did:
unzip lftp-master.zip
cd lftp-master
./autogen.sh 2>&1 > autogen1.out

yum install autoconf
yum install libtool
yum install gettext
#yum install automake

cd ..
yum install git
git clone git://git.savannah.gnu.org/gnulib.git
export PATH=${PATH}:$(pwd)/gnulib/

cd lftp-master

./autogen.sh 2>&1 > autogen2.out

wget 'http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess'
wget 'http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub'

yum install gcc-c++

./autogen.sh &> autogen3.out

yum install readline-devel

./autogen.sh &> autogen4.out

#yum install gnutls
yum install gnutls-devel

./autogen.sh &> autogen5.out

tail -4 autogen5.out
# checking for deflate in -lz... no
# configure: error: cannot find -lz library
# ./configure: line 71130: exit: install: numeric argument required
# ./configure: line 71130: exit: install: numeric argument required

% yum install lz
No package lz available.
Error: Nothing to do

% yum install z
No package z available.
Error: Nothing to do

% yum install zlib
Package zlib-1.2.3-29.el6.x86_64 already installed and latest version
Nothing to do

**Comment by lavv17** [comment]
Try zlib-devel

ср, 11 февр. 2015, 2:11, danlange <notifications@github.com>:

**Comment by lavv17** [comment]
You can also get the latest lftp snapshot from the download page

ср, 11 февр. 2015, 6:38, Alexander Lukyanov <lavv17f@gmail.com>:

**Comment by danlange** [comment]
I am now able to use HTTP over IPv6 successfully.  The problem is resolved.
