### ISSUE TITLE
feature: --no-times

### ISSUE THREAD

**Issue by quite** [lavv17/lftp#124]
On systems where setting timestamps isnt permitted, it would be great with an option like this to not have to see error messages. For put and mirror commands.

**Comment by lavv17** [comment]
Can you provide a sample of those error messages to locate the place in the code which generates them?

**Comment by quite** [comment]
Hm, ok. I do this in lftp:

    ftp ftp@chimp:/d> mirror -R dist
    New: 4 files, 0 symlinks                                            
    390887 bytes transferred in 1 second (373.4 KiB/s)
    4 errors detected

These are the errors reportedThe destination is an ftpserver on an android device. It's log follows below. I guess the ftpserver is the one reporting errors (500), and ltp counts them. This ftpserver may or may not implement the ftp protocol in a competent manner, but it would never the less very nice if lftp could avoid these errors, if they are only due to a failure to modify the timestamp.

    FTPServer 2.9.1 (66)
    15-02-10T12:00:41 <== CWD /d
    15-02-10T12:00:41 ==> 250 command succesful (/d/)
    15-02-10T12:00:41 <== MKD dist
    15-02-10T12:00:41 ==> 257 Directory /d/dist/ created
    15-02-10T12:00:41 <== CWD dist
    15-02-10T12:00:41 ==> 250 command succesful (/d/dist/)
    15-02-10T12:00:41 <== TYPE A
    15-02-10T12:00:41 ==> 200 Switching to mode TYPE A
    15-02-10T12:00:41 <== PASV
    15-02-10T12:00:41 ==> 227 Entering Passive Mode (192,168,0,8,143,220)
    15-02-10T12:00:41 <== LIST
    15-02-10T12:00:41 ==> 150 Directory listing for /d/dist/
    15-02-10T12:00:41 ==> 226 Directory send OK.
    15-02-10T12:00:41 <== NLST
    15-02-10T12:00:41 <== TYPE I
    15-02-10T12:00:41 ==> 200 Switching to mode TYPE I
    15-02-10T12:00:41 <== STOR vdirsyncer-0.3.2-py2.7.egg
    15-02-10T12:00:41 ==> 150 Binary data connection
    15-02-10T12:00:42 ==> 226 transfer complete
    15-02-10T12:00:42 Refreshing the MediaStore
    15-02-10T12:00:42 <== MFMT 20141207210210 vdirsyncer-0.3.2-py2.7.egg
    15-02-10T12:00:42 ==> 500 - could not set lastModified timestamp (this is most likely an android limitation)
    15-02-10T12:00:42 <== PASV
    15-02-10T12:00:42 ==> 227 Entering Passive Mode (192,168,0,8,143,220)
    15-02-10T12:00:42 <== STOR vdirsyncer-0.3.4-py2.7.egg
    15-02-10T12:00:42 ==> 150 Binary data connection
    15-02-10T12:00:42 <== MFMT 20141227204305 vdirsyncer-0.3.4-py2.7.egg
    15-02-10T12:00:42 <== STOR vdirsyncer-0.4.1-py2.7.egg
    15-02-10T12:00:42 <== MFMT 20150129211800 vdirsyncer-0.4.1-py2.7.egg
    15-02-10T12:00:42 <== STOR vdirsyncer-0.4.2-py2.7.egg
    15-02-10T12:00:42 <== MFMT 20150210095652 vdirsyncer-0.4.2-py2.7.egg

**Comment by lavv17** [comment]
MFMT result is ignored by lftp. These errors must come from elsewhere.
Please turn on debug in lftp for clarification.

**Comment by quite** [comment]
---- local cwd is `/home/quite/src-install/vdirsyncer--untitaker'
    mirror(0x9d9fbb0) enters state INITIAL_STATE
    mirror(0x9d9fbb0) enters state CHANGING_DIR_SOURCE
    mirror(0x9d9fbb0) enters state MAKE_TARGET_DIR
    ---> MKD dist
    <--- 257 Directory /u/dist/ created
    ---- CWD path to be sent is `/u/dist'
    ---> CWD dist
    mirror(0x9d9fbb0) enters state CHANGING_DIR_TARGET
    <--- 250 command succesful (/u/dist/)
    mirror(0x9d9fbb0) enters state GETTING_LIST_INFO
    ---> PASV
    <--- 227 Entering Passive Mode (192,168,0,8,190,131)
    ---- Connecting data socket to (192.168.0.8) port 48771
    ---- Data connection established
    0:0 translated to pair 0:0 (0,0)
    0 translated to pair 0:0 (0,0)
    ---> LIST
    <--- 150 Directory listing for /u/dist/
    0:0 translated to pair 0:0 (0,0)
    0 translated to pair 0:0 (0,0)
    buffer: EOF on FD 6
    ---- Got EOF on data connection
    ---- Closing data socket
    <--- 226 Directory send OK.
    ---> PASV
    <--- 227 Entering Passive Mode (192,168,0,8,190,131)
    ---- Connecting data socket to (192.168.0.8) port 48771
    ---- Data connection established
    0:0 translated to pair 0:0 (0,0)
    0 translated to pair 0:0 (0,0)
    ---> NLST
    <--- 150 Directory listing for /u/dist/
    buffer: EOF on FD 6
    ---- Got EOF on data connection
    ---- Closing data socket
    <--- 226 Directory send OK.
    ---> TYPE I
    <--- 200 Switching to mode TYPE I
    mirror(0x9d9fbb0) enters state TARGET_REMOVE_OLD_FIRST
    mirror(0x9d9fbb0) enters state WAITING_FOR_TRANSFER
    FileCopy(0x9da6408) enters state INITIAL
    mirror(0x9d9fbb0) enters state WAITING_FOR_TRANSFER
    FileCopy(0x9da6408) enters state DO_COPY
    opened FD 6
    (/home/quite/src-install/vdirsyncer--untitaker/dist/vdirsyncer-0.3.2-py2.7.egg)
    copy-peer: EOF on FD 6
    copy: get hit eof
    copy: waiting for put confirmation
    FileCopy(0x9da6408) enters state CONFIRM_WAIT
    ---> PASV
    <--- 227 Entering Passive Mode (192,168,0,8,190,131)
    ---- Connecting data socket to (192.168.0.8) port 48771
    ---- Data connection established
    0:0 translated to pair 0:0 (0,0)
    0 translated to pair 0:0 (0,0)
    ---> ALLO 84842
    <--- 500 ALLO not understood
    ---> STOR vdirsyncer-0.3.2-py2.7.egg
    <--- 150 Binary data connection
    ---- Closing data socket
    <--- 226 transfer complete
    ---> MFMT 20141207210210 vdirsyncer-0.3.2-py2.7.egg
    <--- 500 - could not set lastModified timestamp (this is most likely an
    android limitation)
    copy: put confirmed store
    FileCopy(0x9da6408) enters state GET_DONE_WAIT
    copy: get is finished - all done
    FileCopy(0x9da6408) enters state ALL_DONE
    FileCopy(0x9da6f08) enters state INITIAL
    mirror(0x9d9fbb0) enters state WAITING_FOR_TRANSFER
    FileCopy(0x9da6f08) enters state DO_COPY
    opened FD 8
    (/home/quite/src-install/vdirsyncer--untitaker/dist/vdirsyncer-0.3.4-py2.7.egg)
    closed FD 6
    copy-peer: EOF on FD 8
    copy: get hit eof
    copy: waiting for put confirmation
    FileCopy(0x9da6f08) enters state CONFIRM_WAIT
    ---> PASV
    <--- 227 Entering Passive Mode (192,168,0,8,190,131)
    ---- Connecting data socket to (192.168.0.8) port 48771
    ---- Data connection established
    0:0 translated to pair 0:0 (0,0)
    0 translated to pair 0:0 (0,0)
    ---> STOR vdirsyncer-0.3.4-py2.7.egg
    <--- 150 Binary data connection
    ---- Closing data socket
    <--- 226 transfer complete
    ---> MFMT 20141227204305 vdirsyncer-0.3.4-py2.7.egg
    <--- 500 - could not set lastModified timestamp (this is most likely an
    android limitation)
    copy: put confirmed store
    FileCopy(0x9da6f08) enters state GET_DONE_WAIT
    copy: get is finished - all done
    FileCopy(0x9da6f08) enters state ALL_DONE
    FileCopy(0x9da6508) enters state INITIAL
    mirror(0x9d9fbb0) enters state WAITING_FOR_TRANSFER
    FileCopy(0x9da6508) enters state DO_COPY
    opened FD 6
    (/home/quite/src-install/vdirsyncer--untitaker/dist/vdirsyncer-0.4.1-py2.7.egg)
    closed FD 8
    copy-peer: EOF on FD 6
    copy: get hit eof
    copy: waiting for put confirmation
    FileCopy(0x9da6508) enters state CONFIRM_WAIT
    ---> PASV
    <--- 227 Entering Passive Mode (192,168,0,8,190,131)
    ---- Connecting data socket to (192.168.0.8) port 48771
    ---- Data connection established
    0:0 translated to pair 0:0 (0,0)
    0 translated to pair 0:0 (0,0)
    ---> STOR vdirsyncer-0.4.1-py2.7.egg
    <--- 150 Binary data connection
    ---- Closing data socket
    <--- 226 transfer complete
    ---> MFMT 20150129211800 vdirsyncer-0.4.1-py2.7.egg
    <--- 500 - could not set lastModified timestamp (this is most likely an
    android limitation)
    copy: put confirmed store
    FileCopy(0x9da6508) enters state GET_DONE_WAIT
    copy: get is finished - all done
    FileCopy(0x9da6508) enters state ALL_DONE
    FileCopy(0x9da68f8) enters state INITIAL
    mirror(0x9d9fbb0) enters state WAITING_FOR_TRANSFER
    FileCopy(0x9da68f8) enters state DO_COPY
    opened FD 8
    (/home/quite/src-install/vdirsyncer--untitaker/dist/vdirsyncer-0.4.2-py2.7.egg)
    closed FD 6
    copy-peer: EOF on FD 8
    copy: get hit eof
    copy: waiting for put confirmation
    FileCopy(0x9da68f8) enters state CONFIRM_WAIT
    ---> PASV
    <--- 227 Entering Passive Mode (192,168,0,8,190,131)
    ---- Connecting data socket to (192.168.0.8) port 48771
    ---- Data connection established
    0:0 translated to pair 0:0 (0,0)
    0 translated to pair 0:0 (0,0)
    ---> STOR vdirsyncer-0.4.2-py2.7.egg
    <--- 150 Binary data connection
    ---- Closing data socket
    <--- 226 transfer complete
    ---> MFMT 20150210112730 vdirsyncer-0.4.2-py2.7.egg
    <--- 500 - could not set lastModified timestamp (this is most likely an
    android limitation)
    copy: put confirmed store
    FileCopy(0x9da68f8) enters state GET_DONE_WAIT
    copy: get is finished - all done
    FileCopy(0x9da68f8) enters state ALL_DONE
    mirror(0x9d9fbb0) enters state TARGET_REMOVE_OLD
    mirror(0x9d9fbb0) enters state TARGET_CHMOD
    closed FD 8
    ---> SITE CHMOD 644 vdirsyncer-0.3.2-py2.7.egg
    <--- 500 SITE CHMOD 644 vdirsyncer-0.3.2-py2.7.egg not understood
    mirror(0x9d9fbb0) enters state FINISHING
    mirror(0x9d9fbb0) enters state DONE

**Comment by lavv17** [comment]
I think this mirror option should help:
```
-p,      --no-perms                don't set file permissions
```

**Comment by quite** [comment]
Right, it did. And now I understand why.

Just have to try and remember -p!
