### ISSUE TITLE
lftp cannot authenticate against syncplify.me sftp windows server

### ISSUE THREAD

**Issue by pasha74** [lavv17/lftp#125]
Hello,

I was trying to login via SFTP to a windows machine running syncplify.me SSHD server (http://www.syncplify.me/download.html) and lftp -d hangs at "FEAT negotiation" string. Filezilla regularly logs in and operates.

I was browsing the internet and the makers of this server report that there has been an authentication problem with sftp CLI client on linux, which gets cleared by enabling MD5 auth in server. Unfortunately this does not solve the issue with lftp. http://kb.syncplify.me/index.php/linux-sftp-client-error-6-invalid-packet-solution/#more-606

Looks like there is something about how lftp authenticates to sshd to inquire.
Thanks
Pasha

**Comment by lavv17** [comment]
You have to specify correct protocol in the URL. Like this:
```
open sftp://user@example.org
```
