### ISSUE TITLE
How can I permanently disable directory caching in lftp?

### ISSUE THREAD

**Issue by mcandre** [lavv17/lftp#126]
I attempted to configure my `$HOME/.lftp.rc` to permanently disable directory caching (it has a nasty habit of never bloody updating).

https://raw.githubusercontent.com/mcandre/dotfiles/master/.lftp.rc

But no matter how I try to write this configuration, it seems to have no effect. What is the correct syntax for this?

**Comment by lavv17** [comment]
The correct file name is ~/.lftprc or ~/.lftp/rc
