### ISSUE TITLE
Ignore case on mirror?

### ISSUE THREAD

**Issue by CodeBrauer** [lavv17/lftp#131]
Hey there.

How can I ignore the case of a file?

I want to copy all `*.tif | *.tiff | *.TIF *.TIFF` files from another ftp server so my regex looks like this:

```regex
\.(tiff?)$
```

In [pure regex](http://www.regexr.com/3agd7) this would be my solution (ignore case flag):
```regex
/\.(tiff?)$/ig
```

How can this be solved / or does glob already ignore the case?

---

Whole command:

```sh
# ...
FILES="\.(tiff?)$"

lftp -u $FTP_LOGIN,$FTP_PASSWORD $FTP_HOST << EOF
    set ftp:ssl-allow no
    mirror -ne -i $FILES --log=logs/$DATE_TODAY.log $REMOTE_DIR $LOCAL_DIR
    quit
EOF
```

**Comment by lavv17** [comment]
Currently there is no way to specify case ignore flag. But you can use [Tt][Ii][Ff][Ff]?

**Comment by CodeBrauer** [comment]
Thank you for your comment!

`[Tt][Ii][Ff]([Ff])?` works great. not the prettiest way, but it will do the job.

http://regexr.com/3ahl8
