### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by rubenski** [lavv17/lftp#132]
Hi,

We are connecting to a URL using lftp. The IP for this URL has changed and since this happened we see the error "Fatal error: Host key verification failed" when the mget command is run.

What should we do to accept the host key again?

**Comment by lavv17** [comment]
Either connect to the host using plain ssh and accept the key, or "set sftp:auto-confirm yes" in lftp

**Comment by wheelq** [comment]
`lftp -e "set sftp:auto-confirm yes;set ssl:verify-certificate no;ls -la" -p 22 fish://localhost`
Results in:
`ls: ls -la: Fatal error: Host key verification failed`

Also tried with set ssl:verify-certificate off;set ssl:verify-certificate false; etc

**Comment by segidev** [comment]
> `lftp -e "set sftp:auto-confirm yes;set ssl:verify-certificate no;ls -la" -p 22 fish://localhost`
> Results in:
> `ls: ls -la: Fatal error: Host key verification failed`
> 
> Also tried with set ssl:verify-certificate off;set ssl:verify-certificate false; etc

@wheelq For me it worked with `lftp -c "set sftp:auto-confirm yes ; open -u $USERNAME,$PASSWORD sftp://$HOST ; mirror -e -R -p ./source dest ; quit"`

So i used **-c** instead of **-e**

Probably that helps?

**Comment by gabrr** [comment]
@segidev it worked to me too, thanks man

**Comment by gabrr** [comment]
I put this way:

lftp -c "set sftp:auto-confirm yes ; open -u $USERNAME sftp://$HOST

then it require the password

**Comment by wheelq** [comment]
> 
> 
> > `lftp -e "set sftp:auto-confirm yes;set ssl:verify-certificate no;ls -la" -p 22 fish://localhost`
> > Results in:
> > `ls: ls -la: Fatal error: Host key verification failed`
> > Also tried with set ssl:verify-certificate off;set ssl:verify-certificate false; etc
> 
> @wheelq For me it worked with `lftp -c "set sftp:auto-confirm yes ; open -u $USERNAME,$PASSWORD sftp://$HOST ; mirror -e -R -p ./source dest ; quit"`
> 
> So i used **-c** instead of **-e**
> 
> Probably that helps?

that's the point, I have to use `-e` instead of `-c`

**Comment by wheelq** [comment]
> Either connect to the host using plain ssh and accept the key, or "set sftp:auto-confirm yes" in lftp

how is that a solution? that's a workaround which doesnt work in my environment

**Comment by segidev** [comment]
> > > `lftp -e "set sftp:auto-confirm yes;set ssl:verify-certificate no;ls -la" -p 22 fish://localhost`
> > > Results in:
> > > `ls: ls -la: Fatal error: Host key verification failed`
> > > Also tried with set ssl:verify-certificate off;set ssl:verify-certificate false; etc
> > 
> > 
> > @wheelq For me it worked with `lftp -c "set sftp:auto-confirm yes ; open -u $USERNAME,$PASSWORD sftp://$HOST ; mirror -e -R -p ./source dest ; quit"`
> > So i used **-c** instead of **-e**
> > Probably that helps?
> 
> that's the point, I have to use `-e` instead of `-c`

Did you try to us -c with your command?

**Comment by wheelq** [comment]
> 
> 
> > > > `lftp -e "set sftp:auto-confirm yes;set ssl:verify-certificate no;ls -la" -p 22 fish://localhost`
> > > > Results in:
> > > > `ls: ls -la: Fatal error: Host key verification failed`
> > > > Also tried with set ssl:verify-certificate off;set ssl:verify-certificate false; etc
> > > 
> > > 
> > > @wheelq For me it worked with `lftp -c "set sftp:auto-confirm yes ; open -u $USERNAME,$PASSWORD sftp://$HOST ; mirror -e -R -p ./source dest ; quit"`
> > > So i used **-c** instead of **-e**
> > > Probably that helps?
> > 
> > 
> > that's the point, I have to use `-e` instead of `-c`
> 
> Did you try to use -c with your command?

Are you serious? :) **I have to use -e**

> - I have to use black pen, but it doesnt work
> - Have you tried the red one?
>

**Comment by segidev** [comment]
From the manual it does basically the same except that -e doesnt exit

> > > > > `lftp -e "set sftp:auto-confirm yes;set ssl:verify-certificate no;ls -la" -p 22 fish://localhost`
> > > > > Results in:
> > > > > `ls: ls -la: Fatal error: Host key verification failed`
> > > > > Also tried with set ssl:verify-certificate off;set ssl:verify-certificate false; etc
> > > > 
> > > > 
> > > > @wheelq For me it worked with `lftp -c "set sftp:auto-confirm yes ; open -u $USERNAME,$PASSWORD sftp://$HOST ; mirror -e -R -p ./source dest ; quit"`
> > > > So i used **-c** instead of **-e**
> > > > Probably that helps?
> > > 
> > > 
> > > that's the point, I have to use `-e` instead of `-c`
> > 
> > 
> > Did you try to use -c with your command?
> 
> Are you serious? :) **I have to use -e**
> 
> > * I have to use black pen, but it doesnt work
> > * Have you tried the red one?

Why do you need to use -e? -c simply combines the part outside of your -e into one command then exits. What is the problem with using it?

**Comment by wheelq** [comment]
> From the manual it does basically the same except that -e doesnt exit
> 
> > > > > > `lftp -e "set sftp:auto-confirm yes;set ssl:verify-certificate no;ls -la" -p 22 fish://localhost`
> > > > > > Results in:
> > > > > > `ls: ls -la: Fatal error: Host key verification failed`
> > > > > > Also tried with set ssl:verify-certificate off;set ssl:verify-certificate false; etc
> > > > > 
> > > > > 
> > > > > @wheelq For me it worked with `lftp -c "set sftp:auto-confirm yes ; open -u $USERNAME,$PASSWORD sftp://$HOST ; mirror -e -R -p ./source dest ; quit"`
> > > > > So i used **-c** instead of **-e**
> > > > > Probably that helps?
> > > > 
> > > > 
> > > > that's the point, I have to use `-e` instead of `-c`
> > > 
> > > 
> > > Did you try to use -c with your command?
> > 
> > 
> > Are you serious? :) **I have to use -e**
> > > * I have to use black pen, but it doesnt work
> > > * Have you tried the red one?
> 
> Why do you need to use -e? -c simply combines the part outside of your -e into one command then exits. What is the problem with using it?

Sarcastic response: because if I use -c OS will blow up
Normal response: because I have to, doesn't matter why, I have to, I do not want a workaround, I need an explanation why it doesn't work because I have to use it and there are no exceptions

**Comment by herdianf** [comment]
On my case, I got it working with this command:

`lftp -c "set sftp:auto-confirm yes; set sftp:connect-program \"ssh -a -x -o UserKnownHostsFile=/dev/null\"; open -u $USERNAME,$PASSWORD sftp://$SFTPHOST; find -l; quit"`
