### ISSUE TITLE
Feature request: send password only when needed

### ISSUE THREAD

**Issue by wwat** [lavv17/lftp#133]
I would like to send the password only if it is asked for by the server. So, we would specify the password, but if an SSH key is enough for authentication, then it should not send it, and if we do specify the password, then it should only send it on a by need basis. 

The use case is basically that we want to obtain a recursive listing of any remote ftp or sftp server as fast as possible with the most flexibility (passwords/ssh keys being present or not) (and nothing else).

**Comment by lavv17** [comment]
Lftp does not send password unless asked by the server. If you observe a different behavior,  send debug output

**Comment by wwat** [comment]
The password prompt comes from the ssh program, I think. Do you also handle that case?

**Comment by lavv17** [comment]
Yes, exactly. Turn on debug in lftp and see.

**Comment by wwat** [comment]
Do you have something like a test suite which demonstrates that it *does* work in various cases? If not, why not?

**Comment by lavv17** [comment]
You are welcome to create one.
