### ISSUE TITLE
Issue with accentued characters uploaded via SFTP

### ISSUE THREAD

**Issue by MoOx** [lavv17/lftp#134]
Hi,

First of all, thanks for this nice tool.

I am having an issue when doing a transfer over SFTP with files that contains accented characters.

When I upload a file containing a character like `é`, it is transformed to `e´` (e + [combined acute accent](http://www.fileformat.info/info/unicode/char/0301/index.htm).

The results is that a lot of my images are broken on my website because urls in my html have the correct accent (é: `%C3%A9`), but then Apache need the 2 characters (so to get image working I need to use `e%CC%81`).

I am on OS X 10.10, using iTerm 2. Everything is in utf-8 so far. Even my SFTP (gandi.net simple hosting).

I've tried some stuff that didn't help:

- set ftp:list-options -a;
- set ftp:use-utf8;
- set file:charset utf8;
- set ftp:charset utf8;
- set sftp:charset utf8;

No changes from what I see.

Here is my script (value in braces has been changed)

```
#!/usr/bin/env zsh

HOST="{...}"
USER="{...}"
PASS="{...}"
SFTPURL="sftp://$USER:$PASS@$HOST"
LCD="~/{local}"
RCD="/{remote}"
DELETE="--delete"
lftp -c "
open '$SFTPURL';
lcd $LCD;
cd $RCD;
ls;
mirror \
 --verbose \
 --use-cache \
 --allow-chown \
 --allow-suid \
 --no-umask \
 --parallel=2 \
 --exclude-glob .git/ \
 --exclude-glob .DS_Store \
 --exclude-glob node_modules/ \
 $1 $2
“
```

Any idea ?

**Comment by MoOx** [comment]
This thread is interesting http://stackoverflow.com/questions/12643402/convert-unicode-decomposition-when-transferring-files-to-web-server

**Comment by MoOx** [comment]
FYI, if I use a classic ftp client (like Transmit or Cyberduck), I don't get this kind of issues.

**Comment by wheelq** [comment]
why do you use  --use-cache ?

**Comment by MoOx** [comment]
Why not ? 
I don't remember. I think I found that somewhere on the interweb :)

**Comment by wheelq** [comment]
Well I just never found really good reason to use this option. Sorry for
the off-topic.

**Comment by lavv17** [comment]
Is the local file name properly encoded? Is the name changed when uploading? Does the name change when uploading using other tools (plain sftp)?

**Comment by MoOx** [comment]
> Is the local file name properly encoded?

Yes

> Is the name changed when uploading?

Yes

> Does the name change when uploading using other tools (plain sftp)?

Nope, like I said before:

> if I use a classic ftp client (like Transmit or Cyberduck), I don't get this kind of issues.

**Comment by lavv17** [comment]
Try set file:charset UTF-8

пт, 6 марта 2015, 10:31, Maxime Thirouin <notifications@github.com>:

**Comment by MoOx** [comment]
Same result :/

**Comment by MoOx** [comment]
I am getting the same issue with sshfs, so the issue isn't probably lftp fault. Closing for now.
