### ISSUE TITLE
Password not working

### ISSUE THREAD

**Issue by Tibba** [lavv17/lftp#136]
Hi guys, i noticed that if i have a password that ends with ! i cannot login
ex: lftp -d -u test,test! -e "dir" sftp://sftp.test.com

Please give me some ideas how i may enter the password to work.

Thank you

**Comment by Tibba** [comment]
Hi, i also noticed that using $ in the password causes the same issue.

Thank you

**Comment by lavv17** [comment]
You have to quote special shell characters using backslash or quotes.

пт, 13 марта 2015, 19:50, Tibba <notifications@github.com>:
