### ISSUE TITLE
add --with-readline to configure

### ISSUE THREAD

**Issue by areis422** [lavv17/lftp#145]

**Comment by areis422** [comment]
BUMP

**Comment by areis422** [comment]
Bump. Still not picking up custom locations.

**Comment by lavv17** [comment]
Please try latest development snapshot http://lftp.yar.ru/ftp/devel/lftp-4.6.5.90.tar.gz

**Comment by areis422** [comment]
Still not working in 4.7.1

**Comment by lavv17** [comment]
Are the options -I and -L passed to the compiler/linker?

сб, 23 апр. 2016 г. в 23:36, Andrew Reis <notifications@github.com>:

**Comment by areis422** [comment]
Hi Alex,

I would assume those flags are added when the options are specified during the run of ./configure

Thanks,
Drew

**Comment by lavv17** [comment]
Please describe what is required to support the alternative location
properly.
4 мая 2016 г. 19:27 пользователь "Andrew Reis" <notifications@github.com>
написал:

**Comment by lavv17** [comment]
Please send the command lines to compile and link lftp with the custom library locations. Then I'll try to improve configure options to get that command lines.

**Comment by areis422** [comment]
I'm not a developer so I have no idea. Use examples from the OpenSSH or 
OpenSSL projects. OpenSSH DOES successfully link against my manually 
compiled zlib library.

Drew
