### ISSUE TITLE
Mirror: overwrite files without deleting them first

### ISSUE THREAD

**Issue by stefanhenze** [lavv17/lftp#148]
I'm trying to mirror into an FTP server that does some sanity checking before any action. For example, I can't delete a file if it's referenced by another file.

This is the command I'm using
````
lftp -u user,pass -p 21 ftp.cratejoy.com -e "cd /remoteDir; mirror -v --ignore-time -R -p --dry-run localDir .; exit"
````

I get this output:
````
cd ok, cwd=/remoteDir                            
Removing old file `html/header.html'                                                
Transferring file `html/header.html'
get -e -O SERVER:21/remoteDir/html file:localDir/html/header.html
Removing old file `html/index.html'
Transferring file `html/index.html'
get -e -O SERVER:21/remoteDir/html file:localDir/html/index.html
Total: 10 directories, 73 files, 0 symlinks                                
Modified: 2 files, 0 symlinks
````

I tried adding or removing `--delete-first` or `-e` without any difference in this order.

It would be great to have an option that would just overwrite the existing file without deleting it first.

**Comment by mglauche** [comment]
I have a similiar problem, removing the changed files first on the remote server does trigger some more business logic than just overwriting them. I'm really missing a -dont-delete-first flag ...

**Comment by mglauche** [comment]
to fix my local problem i did comment out the line 321 of src/MirrorJob.cc (remove_target=true;)
Any idea why this line is called? Is it on purpose or is it a bug?

(using the command "mirror -R -v -n --ignore-size src dest" to sync files to a remote location)

**Comment by lavv17** [comment]
Please test ec1f252
