### ISSUE TITLE
Any way to not follow symlinks and copy them as symlinks ?

### ISSUE THREAD

**Issue by MoOx** [lavv17/lftp#149]
I would like to get symlinks pushed as they are. Currently when lftp read a symlinks it follows it and so copy contents to the remote directory.
I didn't find anything related to that in the `man`.

**Comment by lavv17** [comment]
Which protocol do you use? What command in lftp do you run for "pushing"?

**Comment by MoOx** [comment]
sftp with --reverse (local to distant folder)

**Comment by lavv17** [comment]
mirror to sftp supports creation of remote symlinks. Please send output of mirror -vvv and also debug output (turn it on by command "debug").

**Comment by dsnopek** [comment]
Should this work for mirroring from remote to local via SFTP as well? It's not for me, but maybe I need to set some option? Thanks!

**Comment by lavv17** [comment]
If "cls -l" shows symlink targets, then mirror should create them as well.
