### ISSUE TITLE
Error parsing "connect-program" arguments that having whitespace in it

### ISSUE THREAD

**Issue by bankyadam** [lavv17/lftp#150]
We wanted to use LFTP with Corkscrew tunnelling to connect to an SFTP using a proxy. However, we couldn't, because in [SFtp.cc @ line 154](https://github.com/lavv17/lftp/blob/master/src/SFtp.cc#L154), the argument processing simply splits them by space `" "` character, but our command did look like this:

```
lftp -c "set sftp:connect-program 'ssh -ax -o ProxyCommand=\"/usr/bin/corkscrew proxy.example.com 5678 %h %p\"'; open -u 'username','password' sftp://sftp.example.com:21; cls -1; bye;'
```

**Comment by lavv17** [comment]
The best way to solve this problem for now is to create a short shell script and call it as the connect program.

**Comment by lavv17** [comment]
I'll add an entry to BUGS file for now.

**Comment by himslm01** [comment]
This issue seems to be quite a problem for corporate users behind socks proxies. I understand there is a work-around of writing a script to pass as the sftp:connect-program parameter, but just having this closed issue and a comment in the BUGS file in the source repository is less than ideal.

**Comment by lavv17** [comment]
I think I can pass the whole command to the shell for parsing. Would that
help?

ср, 29 марта 2017, 19:41 Mark Himsley <notifications@github.com>:

**Comment by lavv17** [comment]
Please test whether #333 fixes the problem for you.

**Comment by himslm01** [comment]
I'd love to test, but on a fresh git clone the command `./autogen.sh && make` fails with:

`*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.19 but the autoconf macros are from gettext version 0.18`

Sorry, whilst at work today I haven't had a moment to investigate and fix that.
