### ISSUE TITLE
Support HTTP digest authentication

### ISSUE THREAD

**Issue by ciffel** [lavv17/lftp#151]
In current version, it only send basic auth.
Please consider to support HTTP digest authentication.

**Comment by lavv17** [comment]
Is it really important considering availability of https?

**Comment by ciffel** [comment]
It is not only available in https but also in http. Some websites deprecate basic authentication and only support digest auth. I think lftp can determine which method to use by the  WWW-Authenticate header got from server 401 response header.
Thank you.

**Comment by lavv17** [comment]
I have just started https://github.com/lavv17/lftp/tree/http-digest-auth branch. It cannot do digest auth yet, but it's going to.

**Comment by lavv17** [comment]
please try 80b64dd, digest auth seems to work.
