### ISSUE TITLE
mirror -R and overwrite

### ISSUE THREAD

**Issue by alienglow** [lavv17/lftp#153]
I am referring to this message in the mailing list. http://www.mail-archive.com/lftp%40uniyar.ac.ru/msg02731.html.
Basically can we have a reverse mirror which will overwrite files to the remote FTP without checking both size and time. Your suggestion to first remove the remote directory before starting mirror (rm -r) is not an option as I may have some file which are created on the remote which I don't want to delete. I have this issue when sometimes I am restoring backups of websites and have to overwrite remote with old files. Maybe we can have new option which ignores both like --ignore-time-size

Kind regards,

Alienglow

**Comment by lavv17** [comment]
Maybe mirror without options will do. By default mirror overwrites target files with older versions unless given --only-newer option.

**Comment by alienglow** [comment]
Thank you for your reply, but it doesn't work.

Please see below example.

Local file is file1

# cat file1
test

# ls -l file1
-rw-r--r-- 1 root root 5 Jun 15 07:09 file1

When I run mirror
lftp xxxxx@xxx.xxx.xxx.xxx:/> mirror -c --verbose --reverse /ftp /
Transferring file `file1'
Total: 1 directory, 1 file, 0 symlinks
New: 1 file, 0 symlinks
5 bytes transferred

Now I change the content of file1, but keep size the same.
# cat file1
1234

I set modified date to old.
# touch -d "01 Jan" file1

# ls -l file1
-rw-r--r-- 1 root root 5 Jan  1 00:00 file1

When I run mirror now, the file is not uploaded.
lftp xxxxx@xxx.xxx.xxx.xxx:/> mirror -c --verbose --reverse /ftp /
Total: 1 directory, 1 file, 0 symlinks

So if the file size remains the same and the modified date is older, then mirror doesn't copy. I was asking about this feature, as I need this sometimes to overwrite files with old backups. Deleting the remote directory will work but I will lose files which are created on remote and not there locally.

Thanks and regards,

Alienglow.

**Comment by lavv17** [comment]
Ok, I see now. The reason is that mirror does not trust remote timestamps. Often uploading a file changes its modification time to the current time.

The fix would be either to make an option for mirror to trust timestamps or make remote protocol back-ends report if they can preserve timestamps on upload.

**Comment by lavv17** [comment]
Try f858208 which adds mirror --upload-older option.

**Comment by alienglow** [comment]
Many thanks. I may not be able to test the new version immediately, but will do this sometime soon.

Thanks and regards,

Alienglow

**Comment by alienglow** [comment]
Sorry doesn't seem to work.

lftp xxxxx@xxx.xxx.xxx.xxx:/> mirror -c --upload-older --verbose --reverse /ftp /
Transferring file `file1'
Modified: 1 file, 0 symlinks
lftp xxxxx@xxx.xxx.xxx.xxx:/>

I get this message but the file doesn't get copied. I also don't see the "xx bytes transferred" message, which comes after successful transfer.

Thanks,
Alienglow.

**Comment by lavv17** [comment]
Works for me. Please turn on debug and see what exactly happens.

**Comment by alienglow** [comment]
lftp xxxxx@xxx.xxx.xxx.xxx:/> mirror -c --upload-older --verbose --reverse /ftp /
---> MKD /
<--- 550 /: File exists
---> TYPE A
<--- 200 Type set to A
---> PASV
<--- 227 Entering Passive Mode (xxx,xxx,xxx,xxx,208,45).
---- Connecting data socket to (xxx,xxx,xxx,xxx) port 53293
---- Data connection established
---> LIST
<--- 150 Opening ASCII mode data connection for file list
Certificate: xxxxxxxxxxxxxxxxxx
 Issued by: xxxxxxxxxxxxxxxxxxx
WARNING: Certificate verification: Not trusted
WARNING: Certificate verification: certificate common name doesn't match requested host name ‘xxx.xxx.xxx.xxx’
---- Got EOF on data connection
---- Closing data socket
<--- 226 Transfer complete
---> TYPE I
<--- 200 Type set to I
---> MDTM file1
<--- 213 20141231230000
lftp xxxxx@xxx.xxx.xxx.xxx:/>

**Comment by lavv17** [comment]
Don't use -c option. It makes lftp try to continue upload instead of
overwriting files.

2015-06-17 5:36 GMT+03:00 alienglow <notifications@github.com>:

> lftp xxxxx@xxx.xxx.xxx.xxx:/> mirror -c --upload-older --verbose
> --reverse /ftp /
> ---> MKD /
> <--- 550 /: File exists
> ---> TYPE A
> <--- 200 Type set to A
> ---> PASV
> <--- 227 Entering Passive Mode (xxx,xxx,xxx,xxx,208,45).
> ---- Connecting data socket to (xxx,xxx,xxx,xxx) port 53293
> ---- Data connection established
> ---> LIST
> <--- 150 Opening ASCII mode data connection for file list
> Certificate: xxxxxxxxxxxxxxxxxx
> Issued by: xxxxxxxxxxxxxxxxxxx
> WARNING: Certificate verification: Not trusted
> WARNING: Certificate verification: certificate common name doesn't match
> requested host name ‘xxx.xxx.xxx.xxx’
> ---- Got EOF on data connection
> ---- Closing data socket
> <--- 226 Transfer complete
> ---> TYPE I
> <--- 200 Type set to I
> ---> MDTM file1
> <--- 213 20141231230000
> lftp xxxxx@xxx.xxx.xxx.xxx:/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavv17/lftp/issues/153#issuecomment-112627249>.
>



-- 
   Alexander.

**Comment by alienglow** [comment]
Sorry that doesn't help. Same result without -c

lftp xxxxx@xxx.xxx.xxx.xxx:/> mirror --upload-older --verbose --reverse /ftp /
---- local cwd is `/ftp'
---> MKD /
<--- 550 /: File exists
---> TYPE A
<--- 200 Type set to A
---> PASV
<--- 227 Entering Passive Mode (xxx,xxx,xxx,xxx,222,206).
---- Connecting data socket to (xxx,xxx,xxx,xxx) port 57038
---- Data connection established
0:0 translated to pair 0:0 (0,0)
0 translated to pair 0:0 (0,0)
---> LIST
<--- 150 Opening ASCII mode data connection for file list
Certificate: xxxxxxxxxxxxxxxxxx
 Issued by: xxxxxxxxxxxxxxxxxx
WARNING: Certificate verification: Not trusted
WARNING: Certificate verification: certificate common name doesn't match requested host name ‘xxx.xxx.xxx.xxx’
---- Got EOF on data connection
---- Closing data socket
<--- 226 Transfer complete
---> TYPE I
<--- 200 Type set to I
---> MDTM file1
<--- 213 20141231230000
lftp xxxxx@xxx.xxx.xxx.xxx:/>

Kind regards,

Alienglow

**Comment by lavv17** [comment]
What is the local time-stamp of file1?

**Comment by alienglow** [comment]
Local
-rw-r--r-- 1 root root 5 Jan  1 00:00 file1

Remote
-rw-r--r-- 1 ftpuser ftpgroup 5 Jan  1 00:00 file1

Currently both timestamps are the same, filesize is same, the content is different. That is what I am trying to achieve. Have a option for reverse mirror, which when given, lftp shld do a blind overwrite of the remote. Don't check time, don't check size, just blindly overwrite.

Thanks,

Alienglow.

**Comment by lavv17** [comment]
Yet another option is needed to re-transfer seemingly same files. How would you suggest to name it? --transfer-all or something else?

**Comment by alienglow** [comment]
Thank you. I will leave this to you. I am fine with "--transfer-all"

regards,

Alienglow

**Comment by alienglow** [comment]
Actually do we need another option. What is the behaviour if both options "--ignore-time" and "--ignore-size" are given together? Should this not have the same effect as "--transfer-all"?

regards,

Alienglow

**Comment by lavv17** [comment]
No, those options mean the reverse: files with different time/size won't be transferred.

**Comment by lavv17** [comment]
Done. Please try f86bc8a

**Comment by alienglow** [comment]
Works thank you for your time and patience.

Kind regards,

Alienglow
