### ISSUE TITLE
Misleading documentation for cmd:fail-exit

### ISSUE THREAD

**Issue by uhliarik** [lavv17/lftp#155]
Hi,

Description of problem:

This is what lftp man page says about the cmd:fail-exit option:

       cmd:fail-exit (boolean)
              if true, exit when an unconditional (without || and && at
              begin) command fails.

The description is misleading in two ways, or more precisely, mixing two different things together. First, lftp does not exit immediately after the failed command; instead, it waits for the user to input one more command (which is not executed). Second, it is this other command, not the failed one, which must not begin with a logical operator. The failed command can well be a conditional one:

# lftp -e 'set cmd:fail-exit yes'
lftp :~> !true
lftp :~> && !false
lftp :~> !true
#

To make the actual behaviour clear in the documentation, I propose the following formulation:

       cmd:fail-exit (boolean)
              if true, exit when a command fails and the following command is
              unconditional (i.e. does not begin with || or &&). lftp exits
              after the unconditional command is issued without executing it.

Component version:
lftp-4.0.9

**Comment by lavv17** [comment]
fixed in 1150a44
