### ISSUE TITLE
Code with no effect

### ISSUE THREAD

**Issue by uhliarik** [lavv17/lftp#157]
Hi,

I'm proposing another patch. I propose, that code property in Reply_STATUS class should be int instead of unsigned int, because in file SFTP.cc on line 1528, you have this code:

```C
if(code>=0 && code<sizeof(text_table)/sizeof(*text_table)) 
    return text_table[code];
```

If you don't want to change datatype of code property, then expression ```code>=0``` should be removed from if statement.

Patch is following:

```Patch
diff -Naurp lftp-4.4.8.orig/src/SFtp.h lftp-4.4.8/src/SFtp.h
--- lftp-4.4.8.orig/src/SFtp.h	2013-04-17 14:21:49.000000000 +0200
+++ lftp-4.4.8/src/SFtp.h	2015-06-01 14:38:54.765685501 +0200
@@ -569,7 +569,7 @@ private:
    class Reply_STATUS : public Packet
    {
       int protocol_version;
-      unsigned code;
+      int code;
       xstring message;
       xstring language;
    public:
```

**Comment by lavv17** [comment]
On one hand, the code cannot be negative. OTOH, an extra check does no harm and is optimized out by the compiler. When the type of "code" is somewhere away from the actual use, it's not clear that it cannot be negative, and the check makes any reader confident that the code is correct.
