### ISSUE TITLE
ssl:check-hostname doesn't work with openssl

### ISSUE THREAD

**Issue by mohicks** [lavv17/lftp#158]
There's no checking of the ssl:check-hostname in lftp_ssl_openssl::check_certificate() when
the cert_hostcheck() function fails.  Patch follows:

diff -up lftp-4.3.6/src/lftp_ssl.cc lftp-4.3.6.mod/src/lftp_ssl.cc
--- lftp-4.3.6/src/lftp_ssl.cc  2012-01-24 04:38:25.000000000 -0500
+++ lftp-4.3.6.mod/src/lftp_ssl.cc      2015-06-02 14:25:58.688163170 -0400
@@ -1385,18 +1385,21 @@ void lftp_ssl_openssl::check_certificate
         set_cert_error("invalid cert name field (cannot convert from UTF8)");
     }
 
+    bool check_hostname = ResMgr::QueryBool("ssl:check-hostname", hostname);
     if(cert_error)
       /* error already detected, pass through */
       ;
     else if(!peer_CN) {
       set_cert_error("unable to obtain common name from peer certificate");
     }
-    else if(!cert_hostcheck((const char *)peer_CN, hostname)) {
+    else if(check_hostname) {
+      if (!cert_hostcheck((const char *)peer_CN, hostname)) {
         set_cert_error(xstring::format("certificate subject name %s does not match "
-              "target host name %s", quote_n(0,(const char *)peer_CN), quote_n(1,hostname)));
-    }
-    else {
-      Log::global->Format(9, "Certificate verification: common name: %s matched\n", quote((char*)peer_CN));
+                "target host name %s", quote_n(0,(const char *)peer_CN), quote_n(1,hostname)));
+      }
+      else {
+        Log::global->Format(9, "Certificate verification: common name: %s matched\n", quote((char*)peer_CN));
+      }
     }
     if(peer_CN)
       OPENSSL_free(peer_CN);

**Comment by lavv17** [comment]
Please see https://github.com/lavv17/lftp/blob/master/src/lftp_ssl.cc#L1351
