### ISSUE TITLE
Dealing with files of zero size with mirror mode

### ISSUE THREAD

**Issue by benjojo** [lavv17/lftp#165]
I have a setup where a FUSE filesystem does not know what the file size is of the file before it makes it, because of this. When customers log into the SFTP, They see all of their log files as zero bytes.

sftp handles this by trying to get the zero byte file anyway, and then ending up with more than zero bytes, and it's fairly happy with that.

However when moving customers to the idea of automatically downloading these logs, lftp comes up, In this example command:

`lftp sftp://benjojo.co.uk\@<hostsnipped>@<hostsnipped>:<hostsnipped> -e 'mirror --verbose -c / /home/ben/loogs/rollinglogs/'`

We try and mirror the log files from the SFTP directory on to disk (as log files are removed after 3 days), In this case it gets the file list from the server, and then instantly makes 2000~ zero byte files, without checking with the remote host that the files had more in them.

I tried to use `--ignore-size` but that only applies to the selection of files to download

` --ascii ` is the only thing that does make this slightly work, however since the gzip'd files are transferred in ascii mode, they are slightly corrupted.

Is there a switch that I can force the "ignore the fact that the file is zero bytes" behaviour that ` --ascii ` has, but without the downside that ` --ascii ` has in that it give me the files back in ascii?

Perhaps this could be a useful flag for those who have strange file systems that sometimes lie on directory listings  :)

**Comment by benjojo** [comment]
So my fairly scary work around this right now is grabbing a the source and doing this patch:

```diff
diff --git a/src/FileCopy.cc b/src/FileCopy.cc
index 95d6027..8f78cd5 100644
--- a/src/FileCopy.cc
+++ b/src/FileCopy.cc
@@ -1051,7 +1051,7 @@ void FileCopyPeerFA::OpenSession()
    current->Timeout(0);        // mark it MOVED.
    if(mode==GET)
    {
-      if(size!=NO_SIZE && size!=NO_SIZE_YET && seek_pos>=size && !ascii)
+      if(/*size!=NO_SIZE && size!=NO_SIZE_YET && seek_pos>=size && !ascii*/ false)
       {
       past_eof:
         debug((10,"copy src: seek past eof (seek_pos=%lld, size=%lld)\n",
```

Is there any chance we can add another `--ascii` but that only applies to this statement?

**Comment by lavv17** [comment]
Please try 93abe01
