### ISSUE TITLE
Incremental mirror/backup ?

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#166]
It is possible to mirror/backup, cause when i do it alway scan whole folders and it subfolders and i have a lot of dirs so the mirror/backup takes loooong time.

**Comment by lkraav** [comment]
How do you suggest `lftp` determines what has changed? This sounds like a job for https://github.com/git-ftp/git-ftp

**Comment by scriptzteam** [comment]
okay so, i have this script, which will only download nfo,sfv, but now rar/zips etc, i run this script once and everything is fine, but when i run it the second time it will start scan the same folders over remote ftp again even they are already in my local directory/backup directory

#!/bin/bash
login=""
pass=""
host=""
port=""
remote_dir="/"
local_dir="/my_backup"

  lftp -u $login,$pass $host -p $port << EOF
set mirror:exclude-regex ^.*\.v.*$\|^.*\.av.*$\|^.*\.m.*$\|^.*\.0.*$\|^.*\.fla.*$\|^.*\.mp.*$\|^.*\.r.*$\|^.*\.zip.*$\|^.*\[.*$
set net:timeout 5
set net:reconnect-interval-base 5
mirror -c -P0 --only-newer --log=synctorrents.log --ignore-time $remote_dir $local_dir 
 quit
EOF

**Comment by lavv17** [comment]
With 9f50a70 mirror can be given the option --recursion=missing or --recursion=newer. Please try to see if it fits you.

**Comment by scriptzteam** [comment]
Thank you :) Also when i have it installed by apt-get, do i need to remove it and install it from github source?
