### ISSUE TITLE
assertion failed: "!node->next && !node->prev" when finishing "wait all"

### ISSUE THREAD

**Issue by notr1ch** [lavv17/lftp#168]
Hello,
I am experiencing intermittent assertion failures when waiting on a bunch of parallel job downloads with "wait all" after invoking lftp with -f to run a script.

Assertion:
#3  0x00007f0f8e88b2d2 in __GI___assert_fail (assertion=0x51038d

"!node->next && !node->prev", file=0x510385 "xlist.h", line=57,
function=0x510400

Example script:
get http://url/1/1mb &
get http://url/2/1mb &
get http://url/3/1mb &
get http://url/4/1mb &
[...]
wait all
exit

Debug output:
http://pastebin.com/raw.php?i=iUALayQX

Stack trace:
http://pastebin.com/raw.php?i=pALq1e4V

I originally reported this bug to Debian as I am using Debian 8, however after reviewing the Debian patches I don't believe this is distribution-specific and there has been little progress on the Debian bug report. You can view the original report at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785236

**Comment by lavv17** [comment]
Can you run lftp under valgrind, please? I suspect it might be freed memory
dereference.

2015-07-01 14:56 GMT+03:00 Richard Stanway <notifications@github.com>:

> Hello,
> I am experiencing intermittent assertion failures when waiting on a bunch
> of parallel job downloads with "wait all" after invoking lftp with -f to
> run a script.
>
> Assertion:
> #3 <https://github.com/lavv17/lftp/issues/3> 0x00007f0f8e88b2d2 in
> __GI___assert_fail (assertion=0x51038d
> "!node->next && !node->prev", file=0x510385 "xlist.h", line=57,
> function=0x510400
>
> Example script:
> get http://url/1/1mb &
> get http://url/2/1mb &
> get http://url/3/1mb &
> get http://url/4/1mb &
> [...]
> wait all
> exit
>
> Debug output:
> http://pastebin.com/raw.php?i=iUALayQX
>
> Stack trace:
> http://pastebin.com/raw.php?i=pALq1e4V
>
> I originally reported this bug to Debian as I am using Debian 8, however
> after reviewing the Debian patches I don't believe this is
> distribution-specific and there has been little progress on the Debian bug
> report. You can view the original report at
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785236
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavv17/lftp/issues/168>.
>



-- 
   Alexander.

**Comment by notr1ch** [comment]
I updated my script to invoke lftp under valgrind for all transfers. It's been running for over a week in this setup and in typical fashion this has stopped the bug from manifesting :). The only interesting output was some invalid memory reads inside libidn which I've included here just in case.

==13024== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
==12977== Invalid read of size 4
==12977==    at 0x5E186CB: idna_to_ascii_4z (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.12)
==12977==    by 0x5E18927: idna_to_ascii_8z (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.12)
==12977==    by 0x5E18989: idna_to_ascii_lz (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.12)
==12977==    by 0x493C79: xidna_to_ascii(char const*) (misc.cc:1013)
==12977==    by 0x4D1FA6: Http::SendMethod(char const*, char const*) (Http.cc:313)
==12977==    by 0x4D3718: Http::SendRequest(char const*, char const*) (Http.cc:626)
==12977==    by 0x4DBC85: Http::SendRequest(char const*) (Http.h:94)
==12977==    by 0x4D65A6: Http::Do() (Http.cc:1359)
==12977==    by 0x46A560: SMTask::ScheduleThis() (SMTask.cc:204)
==12977==    by 0x46A6F5: SMTask::Schedule() (SMTask.cc:243)
==12977==    by 0x411154: Job::WaitDone() (Job.cc:549)
==12977==    by 0x4081BB: main (lftp.cc:589)
==12977==  Address 0x7da84fc is 12 bytes inside a block of size 14 alloc'd
==12977==    at 0x4C2AF2E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12977==    by 0x5E18744: idna_to_ascii_4z (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.12)
==12977==    by 0x5E18927: idna_to_ascii_8z (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.12)
==12977==    by 0x5E18989: idna_to_ascii_lz (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.12)
==12977==    by 0x493C79: xidna_to_ascii(char const*) (misc.cc:1013)
==12977==    by 0x4D1FA6: Http::SendMethod(char const*, char const*) (Http.cc:313)
==12977==    by 0x4D3718: Http::SendRequest(char const*, char const*) (Http.cc:626)
==12977==    by 0x4DBC85: Http::SendRequest(char const*) (Http.h:94)
==12977==    by 0x4D65A6: Http::Do() (Http.cc:1359)
==12977==    by 0x46A560: SMTask::ScheduleThis() (SMTask.cc:204)
==12977==    by 0x46A6F5: SMTask::Schedule() (SMTask.cc:243)
==12977==    by 0x411154: Job::WaitDone() (Job.cc:549)
==12977==
==12977== Invalid read of size 4
==12977==    at 0x5E186E0: idna_to_ascii_4z (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.12)
==12977==    by 0x5E18927: idna_to_ascii_8z (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.12)
==12977==    by 0x5E18989: idna_to_ascii_lz (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.12)
==12977==    by 0x493C79: xidna_to_ascii(char const*) (misc.cc:1013)
==12977==    by 0x4D1FA6: Http::SendMethod(char const*, char const*) (Http.cc:313)
==12977==    by 0x4D3718: Http::SendRequest(char const*, char const*) (Http.cc:626)
==12977==    by 0x4DBC85: Http::SendRequest(char const*) (Http.h:94)
==12977==    by 0x4D65A6: Http::Do() (Http.cc:1359)
==12977==    by 0x46A560: SMTask::ScheduleThis() (SMTask.cc:204)
==12977==    by 0x46A6F5: SMTask::Schedule() (SMTask.cc:243)
==12977==    by 0x411154: Job::WaitDone() (Job.cc:549)
==12977==    by 0x4081BB: main (lftp.cc:589)
==12977==  Address 0x7da85a0 is 16 bytes inside a block of size 18 alloc'd
==12977==    at 0x4C2AF2E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12977==    by 0x5E18744: idna_to_ascii_4z (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.12)
==12977==    by 0x5E18927: idna_to_ascii_8z (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.12)
==12977==    by 0x5E18989: idna_to_ascii_lz (in /usr/lib/x86_64-linux-gnu/libidn.so.11.6.12)
==12977==    by 0x493C79: xidna_to_ascii(char const*) (misc.cc:1013)
==12977==    by 0x4D1FA6: Http::SendMethod(char const*, char const*) (Http.cc:313)
==12977==    by 0x4D3718: Http::SendRequest(char const*, char const*) (Http.cc:626)
==12977==    by 0x4DBC85: Http::SendRequest(char const*) (Http.h:94)
==12977==    by 0x4D65A6: Http::Do() (Http.cc:1359)
==12977==    by 0x46A560: SMTask::ScheduleThis() (SMTask.cc:204)
==12977==    by 0x46A6F5: SMTask::Schedule() (SMTask.cc:243)
==12977==    by 0x411154: Job::WaitDone() (Job.cc:549)

**Comment by notr1ch** [comment]
I think this may have been a Debian packaging issue as I've been running the version of lftp included with Stretch and I'm no longer experiencing any issues.
