### ISSUE TITLE
Exit code when using max-errors and mirror

### ISSUE THREAD

**Issue by cassiobsilva** [lavv17/lftp#169]
Hello, I'm trying to mirror a remote folder to my local machine with the --max-errors option configured to 5. Everything goes fine until the end of the execution, when the exit code ($?) appears to be 1 instead of the success one. Is there any way that I can get the success exit code when just some files throw errors and the fail exit code to another error, like a connection issue happens?

**Comment by NicolasBertrand** [comment]
Hi,
I noticed the same problem with lftp 4.6.0-1 on debian jessie.
The command,
lftp ftp://xxx:yy@10.10.10.10 -e set xfer:log true; mirror --verbose=3 -Rc /data/folder /rfolder/ ; quit
finish with return code =1.

**Comment by NicolasBertrand** [comment]
To be more detailled I have en exit code 0 when running it on bash, but 1 when running it inside a ptyhon script with subprocess: 
Sample code:
```python 
  def run_lftp(self):
        sync = SP.Popen(self.cmd, stdout = SP.PIPE, stderr = SP.PIPE)
        (stdout, stderr) = sync.communicate()
        logger.debug( stdout)
        if sync.returncode:
            _msg = "FTP command failed return code: {}".format(sync.returncode)
            logger.error(_msg)
            logger.error(stderr)
```

**Comment by cassiobsilva** [comment]
Hi Nicolas,

We found out that was the character encoding of the server that was causing problems. Some file names had special characters. After we changed to UTF8, the exit code is back to normal.
