### ISSUE TITLE
Unable to disable FEAT for certain connection methods

### ISSUE THREAD

**Issue by severach** [lavv17/lftp#172]
LFTP | Version 4.6.3a, Arch Linux

This will perform FEAT negotiation.

    lftp 'ftp://foo:bar@0.0.0.0/' -e 'set ftp:ssl-allow false; set ftp:use-feat false; ls; quit'

To prevent FEAT I can rearrange it like this.

    lftp -e 'set ftp:ssl-allow false; set ftp:use-feat false; open ftp://foo:bar@0.0.0.0; ls; quit'

or just remove the slash

    lftp 'ftp://foo:bar@0.0.0.0' -e 'set ftp:ssl-allow false; set ftp:use-feat false; cd /; ls; quit'

The implicit `cd` should not move the implicit `open` before the set statements.

**Comment by lavv17** [comment]
Not a bug. The commands after -e are executed after the implicit open and cd. It's so by design, so you should either use explicit open or put the settings to rc files.

**Comment by avengerx** [comment]
I REALLY missed a commandline flag where I could set up the runtime settings to lftp. Like git allows us to `-c '<name>=<value>'`
