### ISSUE TITLE
lftp 4.6.2 always delete old file on mirror --reverse

### ISSUE THREAD

**Issue by xuefer** [lavv17/lftp#173]
mirror -a -c -v --reverse ./ ./
Removing old file `cm-12.1-20150730-UNOFFICIAL-pisces.zip'
Transferring file `cm-12.1-20150730-UNOFFICIAL-pisces.zip'

CTRL+c
Interrupt

mirror -a -c -v --reverse ./ ./
Removing old file `cm-12.1-20150730-UNOFFICIAL-pisces.zip'
Transferring file `cm-12.1-20150730-UNOFFICIAL-pisces.zip'

while using
put -c cm-12.1-20150730-UNOFFICIAL-pisces.zip
it can resume, which mean the server is OK with resume

**Comment by lavv17** [comment]
mirror checks the file modification date/time and it's size before continuing the transfer to prevent file corruption in some cases. Please see what is the file modification time before the second mirror run.

**Comment by xuefer** [comment]
when i press ctrl+c, file size on remote  is smallerthan local one, file mtime on remote one is always for when the file start upload

**Comment by lavv17** [comment]
maybe --ignore-time option will help if the remote mtime is not newer.

**Comment by xuefer** [comment]
yeah, --ignore-time works for uploading. is there any chance for mirror -c to work without --ignore-time when upload? depends on the ftp server behavior? is there even an ftp server which behave "correctly" for lftp. is this behavior standard specified? or unspecified..

for the record: i'm doing upload, want mirror to resume on big files, remote mtime is always newer than local time when the upload is stopped in the middle
