### ISSUE TITLE
net:reconnect-interval-base does NOT work in the first retry

### ISSUE THREAD

**Issue by jordicenzano** [lavv17/lftp#181]
If you execute this command: 
`lftp 'http://NO_FTP_SERVER_IP'  -e 'set net:max-retries 3;set net:reconnect-interval-multiplier 1;set net:reconnect-interval-max 3;set net:reconnect-interval-base 2;mkdir -p "/HELLO"; quit'`
In first retry uses the default value of net:reconnect-interval-base = 30s, and in the 2nd and 3rd retry it uses the correct value of 2s that we set
Thanks!

**Comment by lavv17** [comment]
You should use -c option with explicit open after set commands.

вт, 8 сент. 2015, 22:35, Jordi Cenzano <notifications@github.com>:

**Comment by jordicenzano** [comment]
Thanks a lot for the answer, it worked!. And sorry for my late late late reply!!!
