### ISSUE TITLE
No readline-devel found

### ISSUE THREAD

**Issue by wheelq** [lavv17/lftp#182]
./configure fails with:

checking for readline... configure: error: need installed readline-devel package

System output:

 zypper se libreadline*
Loading repository data...
Reading installed packages...

S | Name               | Summary              | Type
--+--------------------+----------------------+--------
i | libreadline5       | The Readline Library | package
i | libreadline5-32bit | The Readline Library | package

System: SUSE Linux Enterprise Server 11 (x86_64)

**Comment by lavv17** [comment]
Install the development part of readline.

**Comment by wheelq** [comment]
there isnt any :)

**Comment by lavv17** [comment]
http://software.opensuse.org/package/readline-devel
