### ISSUE TITLE
[wish] [mirror+reverse] upload files with a temp name, then move/replace them instead of overwriting or deleting

### ISSUE THREAD

**Issue by Deevad** [lavv17/lftp#188]
Hi,

In Lftp, when uploading files with the mirror reverse option, Lftp propose only two options when the file already exist:
1. Overwriting: Directly overwrite the file
2. Delete file then write
In the two cases, the file online is not available for usage during the upload time. ( eg. if my upload takes 2 minutes, during 2 minutes the old file will be not avaible because or deleted, or being written.).

I would be interested by a third method:
1. Uploading a file with a temporary name on server
2. When the file is fully uploaded (100%) rename it to overwrite the original. 
This way the file online keeps available during the upload, and the switch is instant.

For reference, I paste here a screenshot of FileZilla doing something similar to what I describe by default: It creates hidden files .pureftp-upload.xx.xx.xxxx.xxxxxxx on the server during the upload time, then rename to instantly overwrite exising file.

![2015-10-12_screenshot_001](https://cloud.githubusercontent.com/assets/4021867/10419724/4b84ec48-7080-11e5-9ae5-2415acd8b3a3.png)

Thank you for Lftp, I use it a lot on my webcomic Pepper&Carrot to upload pages ( http://www.peppercarrot.com/ ), and getting a new option like the one I describe would prevent a problem I'm facing right now: when I update a comic page with LFTP ; the file can't be accessed via the website and it display the comic with a missing page. It affect reading and understanding the story if someone load the page at the same moment.

**Comment by lavv17** [comment]
I think this feature is there already: try "set xfer:use-temp-file yes"

**Comment by Deevad** [comment]
Many thanks @lavv17 , that's super awesome and it works perfectly ! I love Lftp :+1:

**Comment by jgoux** [comment]
@Deevad Hello, were you able to solve this issue ?
I'm stuck at : 
```
When the file is fully uploaded (100%) rename it to overwrite the original.
This way the file online keeps available during the upload, and the switch is instant.
```

Related issue : https://github.com/lavv17/lftp/issues/353

**Comment by Deevad** [comment]
Hi @jgoux ,yes I'm using what @lavv17 adviced: ```"set xfer:use-temp-file yes"``` as an additional option. One just need a recent version of lftp to get the option available.

**Comment by jgoux** [comment]
I assume you're using Filezilla Server on Linux ? I think their implementation isn't the same because on Windows the renaming step fails when there is an existing file with the same name (instead of overwriting it)

**Comment by Deevad** [comment]
@jgoux : exact. I'm using FileZilla and LFTP on a GNU/Linux desktop ( Linux Mint 18.1 Cinnamon ).

**Comment by cheyenne-shao** [comment]
Do you add that to the /etc/lftp.conf file on Ubuntu? I did that, but then this error shows for my lftp session: 
xfer:use-temp-file: no such variable. Use `set -a' to look at all variables.

The LFTP version I have on my linux is: 
LFTP | Version 4.3.3
