### ISSUE TITLE
Getting a nonexistent file deletes a local file

### ISSUE THREAD

**Issue by amluto** [lavv17/lftp#191]
If I set xfer:clobber to 1 and do:

    lftp user@host:dir> get foo
    get: Access failed: No such file (foo)

Then a pre-existing file called ```foo``` gets deleted.  I would expect ```foo``` to be preserved unless the download actually starts.

**Comment by lavv17** [comment]
I think it is not deleted but renamed with ~ suffix. Try "set xfer:make-backup no" to turn off that feature.

**Comment by amluto** [comment]
That's probably it.  I think it's still suboptimal, though.

**Comment by lavv17** [comment]
Please test this patch.
[revert-backup-diff.txt](https://github.com/lavv17/lftp/files/19283/revert-backup-diff.txt)
