### ISSUE TITLE
mirror creates empty dirs not matching the include regex

### ISSUE THREAD

**Issue by bthebaudeau** [lavv17/lftp#192]
With the following command:
```
mirror -epL --scan-all-first --no-symlinks --loop -i '^test/.*$' ftp://server/folder /path-to-dest-folder
```

If `ftp://server/folder` contains `test/` and a few other directories, e.g. `dir1/` and `dir2/`, then `test/` is mirrored as expected, but `dir1/` and `dir2/` are created as well as all their subdirectories, without files.

`dir1/` and `dir2/` should not be created at all (not mirroring the files that they may contain is not sufficient) in that case because they do not match the include regular expression.

Note that removing `--scan-all-first` does not help, and `--no-empty-dirs` would not be a solution because it would also avoid the mirroring of empty directories matching the include regular expression (i.e. under `test/` in the example above).

**Comment by lavv17** [comment]
When you use a single -i or -I option, all directories are included by default (to allow recursion). Try explicit "-x ." before "-i" to exclude all directories explicitly.

**Comment by bthebaudeau** [comment]
Thanks, it works.

The following paragraph from the man page was a bit confusing:
```
       Include and exclude options can be specified multiple times. It means that a file  or  direc‐
       tory  would  be  mirrored  if  it matches an include and does not match to excludes after the
       include, or does not match anything and the first check is exclude. Directories  are  matched
       with a slash appended.
```

**Comment by Silex** [comment]
This does not seem to work. As soon as I have `-x .`, lftp just stops immediatly.
