### ISSUE TITLE
INSTALL out of date

### ISSUE THREAD

**Issue by LukeOwncloud** [lavv17/lftp#194]
I just tried to compile lftp. File ``INSTALL`` did not help at all. It mentions ``./configure`` which does not exist, and does not mention ``./autogen.sh``.

Please update the INSTALL file.

**Comment by lavv17** [comment]
INSTALL was meant for building from a source archive (tar.gz), not from
github.

2015-10-23 11:11 GMT+03:00 LukeOwncloud <notifications@github.com>:

> I just tried to compile lftp. File INSTALL did not help at all. It
> mentions ./configure which does not exist, and does not mention
> ./autogen.sh.
>
> Please update the INSTALL file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavv17/lftp/issues/194>.
>



-- 
   Alexander.

**Comment by LukeOwncloud** [comment]
Just created readme file INSTALL_GITHUB -> https://github.com/lavv17/lftp/pull/196
