### ISSUE TITLE
./autogen cannot find Makefile.in

### ISSUE THREAD

**Issue by LukeOwncloud** [lavv17/lftp#195]
After installing dependencies:

    sudo apt-get install gnulib gnutls-bin libgnutls28-dev

``./autogen.sh`` failed:

    ....
    checking whether memmem is declared... (cached) yes
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: error: cannot find input file: `Makefile.in'

At the beginning ``./autogen.sh`` told me to run `aclocal -I m4`. Is this necessary?

**Comment by lavv17** [comment]
Read the messages from autogen.sh carefully, they should contain some hints
on why automake did not generate Makefile.in


2015-10-23 11:17 GMT+03:00 LukeOwncloud <notifications@github.com>:

> After installing dependencies:
>
> sudo apt-get install gnulib gnutls-bin libgnutls28-dev
>
> ./autogen.sh failed:
>
> ....
> checking whether memmem is declared... (cached) yes
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: error: cannot find input file: `Makefile.in'
>
> At the beginning ./autogen.sh told me to run aclocal -I m4. Is this
> necessary?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavv17/lftp/issues/195>.
>



-- 
   Alexander.

**Comment by LukeOwncloud** [comment]
Adding `set -e` help to find the error:

	Running automake --gnu  ...
	configure.ac:235: error: required file 'build-aux/ltmain.sh' not found
	trio/Makefile.am:3: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')

According to https://www.gnu.org/software/automake/manual/html_node/Error-required-file-ltmain_002esh-not-found.html `libtoolize` should be called explicitly by the compile script.
After manually calling `libtoolize`, `./autogen.sh` succeeded.

Please consider adding  `set -e` and `libtoolize` to your `./autogen.sh`. Thanks!

**Comment by lavv17** [comment]
I've updated autogen.sh to run libtoolize when LT_INIT found in configure.ac.
Please check.

2015-10-25 14:31 GMT+03:00 LukeOwncloud <notifications@github.com>:

> Closed #195 <https://github.com/lavv17/lftp/issues/195>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavv17/lftp/issues/195#event-444822663>.
>



-- 
   Alexander.
