### ISSUE TITLE
edit: create new file if it doesn't exist

### ISSUE THREAD

**Issue by arekm** [lavv17/lftp#197]
Would be nice to make "edit" working also when remote file doesn't exist. If would behave like regular editor (vim etc) -> creating files if it doesn't already exist.

Scanario:
lftp remote.server
edit newfile.php
...

Currently:
> edit newfile.php
get: Brak dostępu: 550 Can't open newfile.php: No such file or directory

lftp 4.6.4

ps. previously I was using my edit alias with script for that, that behaved like this wishlist says. Not sure about how previous lftp own edit alias behaved

**Comment by lavv17** [comment]
please test 9dbf23ac89031129bdf39d8dd461c83617e0a2cb

**Comment by arekm** [comment]
Works, thanks!
