### ISSUE TITLE
Y/N Warning mechanism and an auto backing up file system When in file overwrites

### ISSUE THREAD

**Issue by razcakappa** [lavv17/lftp#199]
In everyday working users (mostly developers on remote project connecting via ftp) always set "xfer:clobber on" Because they need to edit files locally and instantly upload to the destination and vise versa. 
In this kind of scenario the most problem users face is they accidentally overwriting files. (Think about some project or files which are not version controlled)

I'm suggesting 2 points,

1. Implement a y/n situation on file overwrite when the "xfer:clobber on"
2. Implement an auto backing up file mechanism when in file overwrite.
e.g: index.html will "mv" to index.html.bk.{today-date-version}

I'm currently trying to do this on my fork. Just let me know if this features are useless and I hope this feature isn't implemented yet. If it is, please kindly ignore this and apologies for your time.

**Comment by lavv17** [comment]
Automatic backup is feasible, just don't delete the backup file. Y/N
question is not in-line with lftp architecture and spirit.

сб, 28 нояб. 2015, 6:35, razcakappa <notifications@github.com>:

**Comment by razcakappa** [comment]
Is it OK to make a new "set" parameter for this backup feature?
set file:auto-backup on/off

**Comment by lavv17** [comment]
please try 9d51177
