### ISSUE TITLE
mirror -R ... mkdir fails

### ISSUE THREAD

**Issue by lembi0** [lavv17/lftp#200]
Hi there.

I'm running into some issues If i try using
*mirror -R {localpath} {remotepath}*
and lftp needs to create a directory on the remote machine. It looks like it tries to send
*mkdir ftp://user@...remote_ip.../path/to/create*

So this tries to open a second/simultaneous connection to the remote machine? Problem i have is that the remote machine is accepting only one single connection and lftp fails to create the folder (can't log in). Is there an option to solve this, so lftp only uses 
*mkdir path/to/create*

Thanks in advance
Alex

**Comment by lembi0** [comment]
ah sorry.... I'm using version 4.3.6 on a Raspberry... is the behavior the same in the newest version?

**Comment by lavv17** [comment]
lftp does not open another connection unless it is told to do so, e.g. by -P (--parallel) or --use-pget options, mirror:parallel or mirror:use-pget-n settings. The URL in mkdir does not make lftp create a new connection if there is another idle connection.

**Comment by lembi0** [comment]
ok, thanks.
I tried this with another ftp server - it's working there. Seems to be a problem with the ftp server implementation on the remote system itself. If i try this by typing
*mkdir /path/to/create* on the console it works, and
*mkdir ftp://user@...remote_ip.../path/to/create*
doesn't ...hm... is there a way to tell *mirror* not to send the *ftp://...* after the command mkdir?

**Comment by lavv17** [comment]
Turn on debug in lftp to see what exactly is being sent to the server.

пт, 4 дек. 2015, 20:09, lembi0 <notifications@github.com>:

**Comment by lembi0** [comment]
log and debug is on...

from the logfile (i've changed user and pass to "admin" for testing)
*mkdir ftp://admin:admin@10.9.130.23/gzip
mkdir ftp://admin:admin@10.9.130.23/history
mkdir ftp://admin:admin@10.9.130.23/js
...*


and debug
*10.9.130.23 ---> MKD /gzip
10.9.130.23 <--- 550 error creating: /gzip
10.9.130.23 ---- CWD path to be sent is `/gzip'
10.9.130.23 ---> CWD /gzip
10.9.130.23 <--- 550 /gzip invalid directory
10.9.130.23 ---> MKD /history
10.9.130.23 <--- 550 error creating: /history
10.9.130.23 ---- CWD path to be sent is `/history'
10.9.130.23 ---> CWD /history
10.9.130.23 <--- 550 /history invalid directory
10.9.130.23 ---> MKD /js
10.9.130.23 <--- 550 error creating: /js
10.9.130.23 ---- CWD path to be sent is `/js'
10.9.130.23 ---> CWD /js
10.9.130.23 <--- 550 /js invalid directory*

all of them fail if the full path incl. *ftp://user:pass@ ...* is sent.

**Comment by lavv17** [comment]
Does the server report TVFS in the FEAT reply?

сб, 5 дек. 2015, 20:13, lembi0 <notifications@github.com>:

**Comment by lembi0** [comment]
No, i think it doesn't even understand FEAT :)
It's an FTP implementation for embedded systems (based on uIP). Following commands seem to be supported

(from the source-code - I have it here, but i don't really understand it).

*static const T_FTP_CMD_LOOKUP ftp_cmd_lookup[]=
{
	{ "USER", Ftp_cmd_user_P },
	{ "CWD" , Ftp_cmd_cwd_P },
	{ "DELE", Ftp_cmd_dele_P },
	{ "LIST", Ftp_cmd_list_P },
	{ "MDTM", Ftp_cmd_mdtm_P },
	{ "MKD" , Ftp_cmd_mkd_P },
	{ "XMKD", Ftp_cmd_xmkd_P },
	{ "NLST", Ftp_cmd_tbd_P },	/* not yet supported */
	{ "NOOP", Ftp_cmd_noop_P }, 
	{ "PASS", Ftp_cmd_pass_P },
	{ "PASV", Ftp_cmd_pasv_P },
	{ "PORT", Ftp_cmd_port_P },	/* not yet supported */
	{ "PWD" , Ftp_cmd_pwd_P },
	{ "XPWD", Ftp_cmd_xpwd_P },
	{ "CDUP", Ftp_cmd_cdup_P },
	{ "QUIT", Ftp_cmd_quit_P },
	{ "RETR", Ftp_cmd_retr_P },
	{ "RMD" , Ftp_cmd_rmd_P },
	{ "RNFR", Ftp_cmd_rnfr_P },
	{ "RNTO", Ftp_cmd_rnto_P },
	{ "XRMD", Ftp_cmd_xrmd_P },
	{ "SIZE", Ftp_cmd_size_P },
	{ "STAT", Ftp_cmd_stat_P },
	{ "STOR", Ftp_cmd_stor_P },
	{ "SYST", Ftp_cmd_syst_P },
	{ "TYPE", Ftp_cmd_type_P }
};*

**Comment by lavv17** [comment]
can you please test ec4b31c?

**Comment by lavv17** [comment]
Please try latest development snapshot http://lftp.yar.ru/ftp/devel/lftp-4.6.5.90.tar.gz

**Comment by lembi0** [comment]
Sorry, i missed the notification about your post to ec4b31c :(

Took me a while to compile the dev version :) (not really familiar with these things). But it looks like it works now. :o) ... Does this include the changes of ec4b31c?
I'll do some more testing.

**Comment by lembi0** [comment]
...really seems to work :) ...cool!
But i have another "problem"... think i'm doing something wrong.
I've stored the local files and subfolders which i want to sync on the remote machine in
**/path/to/folder/UPLOAD** ... if i try:
:/> mirror -c -R /path/to/folder/UPLOAD/

lftp is creating the folder UPLOAD on the remote machine... i think this is not really wrong :). But what can i do if i just want to upload the content and subfolders of UPLOAD to the remote machine. Is there something like **/path/to/folder/UPLOAD/* ** that only the content of UPLOAD is uploaded and not the folder UPLOAD itself is created on the remote host?

**Comment by lavv17** [comment]
Add a point like this: UPLOAD/.

пн, 14 дек. 2015, 22:52, lembi0 <notifications@github.com>:

**Comment by lembi0** [comment]
Unfortunately it fails again, if i do so. lftp is sending the command
*mkdir /foldername* (including the "/") if the folder doesn't exist on the remote machine. Think this should only be
*mkdir foldername* ?

**Comment by lavv17** [comment]
Probably the problem was fixed incompletely. The root directory case was
not covered.

вт, 15 дек. 2015, 14:18, lembi0 <notifications@github.com>:

**Comment by lavv17** [comment]
f30a043 should be more complete, please test.

**Comment by lembi0** [comment]
Thanks lavv17. I'll try it later, when I'm at home.

**Comment by lembi0** [comment]
Sorry, i didn't get it to run yesterday... did something wrong with the compiler. But now it works...
... and it works perfect!! I can't find errors any more and all folders/files are applied correctly.
Thank's a lot for the work.

**Comment by lavv17** [comment]
Thanks for testing!

**Comment by lembi0** [comment]
Thanks for the modifications :)
