### ISSUE TITLE
windows command execution 

### ISSUE THREAD

**Issue by wheelq** [lavv17/lftp#201]
Is it possible to execute windows command over lftp? I have sftp server running on the windows machine. I execute command using following command:

```
ssh -n windows_box "c:\runme.cmd"
```

Is this achievable using lftp? I tried sftp, fish, no success

**Comment by lavv17** [comment]
With fish protocol it could be possible if the windows computer has
unix-style commands available. The "quote" command in lftp sends the
command to remote side for execution.

пт, 11 дек. 2015, 13:13, Michal Wiczynski <notifications@github.com>:

**Comment by wheelq** [comment]
That's the problem. Windows allows to connect and execute a command using ssh -n, but the fish protocol sends: " echo FISH:;/bin/sh" while the windows sftp server expects just commands. Is there any way  " echo FISH:;/bin/sh" coul dbe removed by a switch or a parameter?

**Comment by lavv17** [comment]
Fish and sftp are completely different protocols, so it's not possible

вт, 15 дек. 2015, 13:32, Michal Wiczynski <notifications@github.com>:

**Comment by wheelq** [comment]
I know that's why I am asking if it is possible to use lftp and do something like: "ssh -n windows_box "c:\runme.cmd" :)

**Comment by lavv17** [comment]
Is it really an sftp-only server? Which clients can use it? What's required?
