### ISSUE TITLE
error verifying files

### ISSUE THREAD

**Issue by duelistjp** [lavv17/lftp#206]
this may very well be expected behavior or user error but i have been having trouble with rar files transferred via sftp using lftp with segmented and parallel downloads being broken.  i turned on xfer:verify and keep getting BEGIN failed--compilation aborted at /usr/share/lftp/verify-file line 23. on every file i transfer.  is this something common you know the problem on looking at the verify-file the line it mentions only has 

use String::CRC32;

in it.

**Comment by lavv17** [comment]
You have to install that perl module. Either from the Linux distribution or
from CPAN.

вс, 24 янв. 2016, 0:51, duelistjp <notifications@github.com>:

**Comment by lavv17** [comment]
`cpan String::CRC` should help.
