### ISSUE TITLE
Throughput issues with FTPES

### ISSUE THREAD

**Issue by graxlop** [lavv17/lftp#209]
Hello,

There seems to be an artificial limitation on throughput on a per-connection basis when downloading via FTPES. The test was done on lftp 4.6.5 (built from source), compiled against OpenSSL 1.0.2e and several different Linux distros and kernel versions, between two machines via gigabit (<1ms RTT). There's always a 23MB/s per connection limitation on the transfer when using FTPES, CPU usage is very minimal and switching over to plain FTP yields full line speed at 115MB/s with a single connection.

The problem also seems to get worse as the RTT increases, down to 7MB/s per connection when the RTT is increased to 70ms, for example.

Any thoughts appreciated! Thanks.

**Comment by lavv17** [comment]
I suspect it is related to ssl internal buffer size. Which ssl library do you use, OpenSSL or GNUTLS?

**Comment by lavv17** [comment]
OpenSSL has default buffer of just 17k to hold a single TLS packet of maximum size. _I don't know if OpenSSL is capable of pipelining several TLS packets._ If it can, to speed up the download you need to increase the buffer size on the *sending* side, that is on the server.

OTOH, for uploading lftp itself should increase the buffer on local side. I can do that, provided that OpenSSL can use that enlarged buffer for pipelining.

**Comment by graxlop** [comment]
I'm only able to reproduce this with lftp, using other clients such as cURL (linked against OpenSSL 1.0.2e) or FileZilla (GnuTLS) both give the same throughput as plain FTP. This is all being tested under the same conditions, the only difference being the FTP client used.

**Comment by lavv17** [comment]
Do other clients use encrypted data transfers?

пт, 12 февр. 2016, 20:54, graxlop <notifications@github.com>:

**Comment by graxlop** [comment]
Yes, both use encryption on data transfers.

**Comment by lavv17** [comment]
Ok, I'll check to see what I can do to improve ssl transfer speed.

**Comment by lavv17** [comment]
Can you provide strace output for curl doing an encrypted transfer?

сб, 13 февр. 2016, 22:52, graxlop <notifications@github.com>:

**Comment by graxlop** [comment]
Here's the output. I cut the tail end of it off, as it was very large. It should include all of the relevant bits, though.

http://pastebin.com/6WBee1wg

**Comment by lavv17** [comment]
Ok, now I see it's not a buffer size problem. I'll try to find the bug and
fix it.

вт, 16 февр. 2016, 11:52, graxlop <notifications@github.com>:

**Comment by lavv17** [comment]
I think I have found the bug and fixed it (5b869b4a6f69b1667c617ee558a5bfca42adb0f5), along with a few other performance optimization in [ssl-optimize](https://github.com/lavv17/lftp/tree/ssl-optimize) branch. Please test.

**Comment by graxlop** [comment]
Looks good now, I'm seeing the same throughput as curl (115MB/s) on gigabit.

Thanks

**Comment by lavv17** [comment]
merged to master.
