### ISSUE TITLE
Cannot compile LFTP on Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by lordspace** [lavv17/lftp#210]
Update: The steps from 2devnull from https://github.com/lavv17/lftp/issues/58 helped me compile it successfully.

I managed to overcome most of the issues by installing these ubuntu packages that showed up during the configure session.
```
apt-get install libreadline6 libreadline6-dev pkg-config gnutls-bin
```

Calling "make" failed miserably and I couldn't continue. 

The reason that I decided to compile it is I've run into issues where some php files were partially transferred. I noticed that some WordPress plugins broke because during the transfer some characters were truncated around php comments.

lftp_tinfo.cc: In function âvoid init_terminfo()â:
lftp_tinfo.cc:53:33: error: âsetuptermâ was not declared in this scope
    if(setupterm(NULL, 1, &errret) == ERR)
                                 ^
lftp_tinfo.cc:53:38: error: âERRâ was not declared in this scope
    if(setupterm(NULL, 1, &errret) == ERR)
                                      ^
lftp_tinfo.cc: In function âconst char* get_string_term_cap(const char*, const char*)â:
lftp_tinfo.cc:71:63: error: âtigetstrâ was not declared in this scope
    const char *ret = tigetstr(const_cast<char *>(terminfo_cap));
                                                               ^
make[1]: *** [lftp_tinfo.lo] Error 1
make[1]: Leaving directory `/lftp-4.6.5/src'
make: *** [all-recursive] Error 1

**Comment by lavv17** [comment]
try to install ncurses-dev or termcap-dev

**Comment by lavv17** [comment]
ca71203 should improve configure checks to output an error early.
