### ISSUE TITLE
lftp is not c++11/14 compatible - fails to build on latest Fedora

### ISSUE THREAD

**Issue by thozza** [lavv17/lftp#212]
lftp fails to be build with default CXXFLAGS on latest Fedora.

The build log can be found here - https://bugzilla.redhat.com/attachment.cgi?id=1125194
For the moment we are going to workaround it by using `-std=gnu++03`.

The downstream bug if you are interested is in - https://bugzilla.redhat.com/show_bug.cgi?id=1307711

**Comment by lavv17** [comment]
It seems to be a gnulib problem

пт, 19 февр. 2016, 18:34, Tomas Hozza <notifications@github.com>:

**Comment by uhliarik** [comment]
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/74YWUCBM7KR2FCACH3WQNTX75WB76JSD/#UY3VX3W7XEXYTUKHG5BALU4ACUD7ZLGE

**Comment by uhliarik** [comment]
In lftp 4.7.0 problem disappeared. Feel free to close this bug.
