### ISSUE TITLE
missing "last mod" date once every 39 files in webdav interactive ls

### ISSUE THREAD

**Issue by drzraf** [lavv17/lftp#213]
* Connect to webdav, in *interactive* mode
* List a directory having more than 40 files
* Once every 39 files list, the  timestamp / Last-Modified date is shown as "-"

In large directories it seems to apply to non-interactive listing too, but less frequently (2 files among 710)

**Comment by lavv17** [comment]
Please try be325f3

**Comment by drzraf** [comment]
I've reworked and reduced directory since the report, but I tried on many directories including one containing 90 files and didn't observed the issue anymore. I'd say it's fixed!

Thank you very much!
