### ISSUE TITLE
lftp doesn't fall back to ipv4 if ipv6 is broken

### ISSUE THREAD

**Issue by lf-** [lavv17/lftp#216]
I had a broken ipv6 setup that wasn't allowing any ipv6 traffic through, only v4. lftp did not handle this gracefully, and ended up sitting there "Connecting..." when I used pget to download a file.

The behaviour that should occur is that lftp gracefully falls back to ipv4 and continues.

**Comment by lavv17** [comment]
Please turn on debug to see what happens. Lftp should try all server addresses in turn.
