### ISSUE TITLE
mirror + xfer:use-temp-file broken with SFTP

### ISSUE THREAD

**Issue by stevegee58** [lavv17/lftp#217]
mirror + xfer:use-temp-file works fine for FTP and SFTP in cases where the destination file doesn't exist.  However if a file with the same name exists on the destination lftp fails with SFTP.  The upload still works correctly with FTP in this case.
Here's a sanitized example:
lftp -u username:password sftp://192.168.1.1/home/steve/ -e "set xfer:temp-file-name *.partial;set xfer:use-temp-file true;set mirror:overwrite false;mirror -R --verbose=3 source_dir dest_dir;quit"
I've confirmed that the username has access to the destination and the destination is correctly specified in the command line.

Here's the sanitized output:
cd ok, cwd=/home/steve
Removing old file `existing_file'
Transferring file `existing_file'
mirror: Access failed: Failure (existing_file.partial)
Modified: 1 file, 0 symlinks
45988296 bytes transferred in 4 seconds (11.16 MiB/s)
1 error detected

**Comment by lavv17** [comment]
please try ce554c3

**Comment by stevegee58** [comment]
I applied the patch to the 4 files of the latest release version 4.6.5.  However it behaves exactly the same as it did before.

**Comment by lavv17** [comment]
Please turn on debug in lftp and send me the output.

**Comment by stevegee58** [comment]
[debuglog.txt](https://github.com/lavv17/lftp/files/172029/debuglog.txt)
It looks like it's not deleting the existing file before renaming the *.partial, so the rename fails.

**Comment by lavv17** [comment]
Ok, I see a problem - it tries to remove the temporary file, but it needs to remove the target file before rename. I'll try to fix it.

**Comment by lavv17** [comment]
Probably dcca98b4edc07797cfb6008c13ecb71571f2e349 will fix the problem by removing the old file before rename. It turned out that sftp v<5 does not support rename options at all.

**Comment by stevegee58** [comment]
It works correctly now.  Thanks for you help!
