### ISSUE TITLE
lftp problem with put -a command

### ISSUE THREAD

**Issue by jlmartinezm** [lavv17/lftp#219]
we are haveing some problems with the lftp lftp-4.0.9-1.el6_5.1.x86_64 over Red Hat Enterprise Linux Server release 6.5 

we are havin problem with some ftp servers when we use "put -a"

some times still waiting for respond if we use "put-a" and if we send the same file to the same sftp server with no "-a" works fine.

this problem impact to our automacly process.

Could you please help us? 

with just "put -a prueba.txt"   still in this step
`prueba.txt' at 37 3b/s [Sending data]

with just "put prueba.txt
put prueba.txt
37 bytes transferred

**Comment by lavv17** [comment]
I suspect this bug was fixed in 2012. Please try a current lftp version. Or use binary transfer mode if possible.

**Comment by jlmartinezm** [comment]
Binary transfer works fine, but not when we user ascii -a, on sftp

we are working with the last release supported by redhat on redhat 6.5.
Could you please confirm lftp-4.0.9-1.el6_5.1.x86_64 is the last one
suppoted by redhat 6.5?

witch release solve the issue?

thanks so much

*BBVA*
*José Luis Martínez Mártínez*
* SPT Middleware*
*Te.- +34 91 807 51 80 - Ext. 72180 - josel.martinezm.contractor@bbva.com
<josel.martinezm.contractor@bbva.com>*

*Tecnica de Sistemas  - Monitores DBDC - CPD Europa Batanes 3, Planta 1,
28760 Tres Cantos*
Antes de imprimir este mensaje, por favor comprueba que es necesario
hacerlo. Before you print this message please consider if it is really
necessary



2016-03-17 12:55 GMT+01:00 Alexander V. Lukyanov <notifications@github.com>:

> I suspect this bug was fixed in 2012. Please try a current lftp version.
> Or use binary transfer mode if possible.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lavv17/lftp/issues/219#issuecomment-197845560>
>

-- 


"Este mensaje está dirigido de manera exclusiva a su destinatario y puede 
contener información privada y confidencial. No lo reenvíe, copie o 
distribuya a terceros que no deban conocer su contenido. En caso de haberlo 
recibido por error,  rogamos lo notifique al remitente y proceda a su 
borrado, así como al de cualquier documento que pudiera adjuntarse.

 Por favor tenga en cuenta que los correos enviados vía Internet no 
permiten garantizar la confidencialidad de los mensajes ni su transmisión 
de forma íntegra.

 Las opiniones expresadas en el presente correo pertenecen únicamente al 
remitente y no representan necesariamente la opinión del Grupo BBVA."

 "This message is intended exclusively for the adressee and may contain 
privileged and confidential information. Please, do not disseminate, copy 
or distribute it to third parties who should not receive it. In case you 
have received it by mistake, please inform the sender and delete the 
message and attachments from your system.

 Please keep in mind that e-mails sent by Internet do not allow to 
guarantee neither the confidentiality or the integrity of the messages 
sent."

**Comment by lavv17** [comment]
It was fixed in 4.3.5, see commit d812466b0a9c5db37ed0541440d6d93cc24db8e5

**Comment by jlmartinezm** [comment]
is thsi fix on redhat 6.5?

thanks

*BBVA*
*José Luis Martínez Mártínez*
* SPT Middleware*
*Te.- +34 91 807 51 80 - Ext. 72180 - josel.martinezm.contractor@bbva.com
<josel.martinezm.contractor@bbva.com>*

*Tecnica de Sistemas  - Monitores DBDC - CPD Europa Batanes 3, Planta 1,
28760 Tres Cantos*
Antes de imprimir este mensaje, por favor comprueba que es necesario
hacerlo. Before you print this message please consider if it is really
necessary



2016-03-23 12:34 GMT+01:00 Alexander V. Lukyanov <notifications@github.com>:

> It was fixed in 4.3.5, see commit d812466
> <https://github.com/lavv17/lftp/commit/d812466b0a9c5db37ed0541440d6d93cc24db8e5>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lavv17/lftp/issues/219#issuecomment-200307228>
>

-- 


"Este mensaje está dirigido de manera exclusiva a su destinatario y puede 
contener información privada y confidencial. No lo reenvíe, copie o 
distribuya a terceros que no deban conocer su contenido. En caso de haberlo 
recibido por error,  rogamos lo notifique al remitente y proceda a su 
borrado, así como al de cualquier documento que pudiera adjuntarse.

 Por favor tenga en cuenta que los correos enviados vía Internet no 
permiten garantizar la confidencialidad de los mensajes ni su transmisión 
de forma íntegra.

 Las opiniones expresadas en el presente correo pertenecen únicamente al 
remitente y no representan necesariamente la opinión del Grupo BBVA."

 "This message is intended exclusively for the adressee and may contain 
privileged and confidential information. Please, do not disseminate, copy 
or distribute it to third parties who should not receive it. In case you 
have received it by mistake, please inform the sender and delete the 
message and attachments from your system.

 Please keep in mind that e-mails sent by Internet do not allow to 
guarantee neither the confidentiality or the integrity of the messages 
sent."
