### ISSUE TITLE
Skip folder(s) that exist on local?

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#222]
So i am doing mirror command and want to skip folders that exist on local (for example they was previously mirrored and do not need to be checked again), those that are on remote and not on local lftp will procceed and download to local, is there a way to do this? :)

**Comment by lavv17** [comment]
Try "mirror --recursion=missing".

**Comment by scriptzteam** [comment]
i tried, got on folder this and exited, inside folder TEST_FOLDER old processed subdirectories and also new, no new being processed just exited:

---> MDTM TEST_FOLDER
<--- 550  TEST_FOLDER: not a plain file.

**Comment by scriptzteam** [comment]
anyone? still can not do it ... mirror --recursion=missing not works --

`---> TYPE I
<--- 200 Type set to I.
---> MDTM FOLDER
<--- 550 FOLDER: not a plain file.
---> QUIT
<--- 221- Goodbye
<--- 221
---- Closing control socket`
