### ISSUE TITLE
Can't get source from ftp server

### ISSUE THREAD

**Issue by uhliarik** [lavv17/lftp#224]
Hi Alexandr,

I'm maintainer of lftp package in Fedora. In new lftp release (4.7.0) I'm not able to download it from ftp://ftp.yar.ru/pub/source/. In spec file, I used this URL which worked before:
ftp://ftp.yar.ru/pub/source/%{name}/%{name}-%{version}.tar.xz

Now, I found on your website, that you changed URL to http://lftp.yar.ru/ftp/ , which is OK, but in case, you release new version and you will move old version, to directory OLD, I won't be able to automatically build lftp.

Solution would be to add also the newest version to directory old, or have all versions in the same directory. What do you think?

**Comment by lavv17** [comment]
I'll just leave all versions in the same directory. I don't think it will create any problems.

**Comment by uhliarik** [comment]
@lavv17 thanks, it is much better :)
