### ISSUE TITLE
Partial file extension

### ISSUE THREAD

**Issue by neersighted** [lavv17/lftp#225]
When downloading files, it is useful to have some sort of extension (such as '.crdownload' or '.partial', etc) to avoid any programs trying to open or process the partially complete file.

An extension such as '.lftp' would be useful. Files that are not yet complete end with this extension, and are renamed once the download is complete.

**Comment by lavv17** [comment]
Please try "set xfer:use-temp-file yes" and "set xfer:temp-file-name *.lftp" (in case you like the extension .lftp).
