### ISSUE TITLE
Compile --with-openssl doesnt compile with openssl

### ISSUE THREAD

**Issue by Schroeffu** [lavv17/lftp#230]
I am doing ./configure --with-openssl on Debian 8.3,  libssl-dev:amd64 and libssl1.0.0:amd64 is installed. Configure runs through, but after make & make install, there seems no OpenSSL included, and connection fails with 

Fatal error: SSL_connect: unknown protocol

```
root@vps:/tmp/lftp4.7.1# lftp -v
LFTP | Version 4.7.1 | Copyright (c) 1996-2016 Alexander V. Lukyanov
(...)
Libraries used: Readline 6.3, Expat 2.1.0, zlib 1.2.8
```

LDD: 

```
root@vps:/tmp/lftp4.7.1# ldd /usr/local/bin/lftp | grep ssl
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f81062b1000)
```

What am I doing wrong?
LFTP 4.7.1

**Comment by lavv17** [comment]
It's compiled with openssl. libssl is part of openssl.

For the "unknown protocol" problem, it may be related to ssl versions mismatch on the client and the server, or maybe the server uses explicit SSL by "AUTH" command, so that you don't need to use ftps URL scheme. Please provide more details.
