### ISSUE TITLE
new mirror option --Remove-source-dirs : always deletes mirror SOURCE path

### ISSUE THREAD

**Issue by jtwill** [lavv17/lftp#233]
The new mirror option, --Remove-source-dirs, is great, except for one issue. It always deletes the base source dir that is specified to the mirror command. While I suppose this may be the desired behavior for some, I think the most people expect it to only delete subdirectories of the specified source directory.

There are a number of ways this issue could be resolved:

1) If the source dir is specified with a trailing slash '/' , then do NOT delete the base source directory. Otherwise, do delete it.

2) Have two different options, --Remove-source-dirs and --Remove-source-subdirs

3) Change the default behavior to never delete the base source directory

Any of those options would be fine with me. But I do think it is important to have the capability to NOT delete the base source directory.

**Comment by 2devnull** [comment]
+1

I have the same issue. It is also not even stopping at the Source directory, but it is traversing up and deleting all directories (I am assuming those that are empty?).
