### ISSUE TITLE
lftp continuing reverse-recursive mirror on webdav

### ISSUE THREAD

**Issue by drzraf** [lavv17/lftp#236]
Yet another one in the section dav/cloud + lftp reverse mirror.
Reverse-mirroring (uploading) a one-level deep directory (directory only containing files) mirror ignore existing files.
But when reverse-mirroring a two-level deep directory, ``mirror -R`` try to re-upload everything (at least ``--dry-run`` mode does)
I could later provide a trace in case the issue would not be obvious to track down.

**Comment by lavv17** [comment]
Please send debug output. If possible, access to a test account would be helpful.

**Comment by drzraf** [comment]
I could not reproduce anymore, I may have been wrong in the first place. Let's close for now (and sorry for the noise)

**Comment by drzraf** [comment]
I think I found the issue.
I have the local directory "photos".
And a remote directory "Photos".

The following processes correctly:
```
$ echo "lcd photos; mirror -Rv ./ ./Photos/" | lftp https://....com/remote.php/webdav/
mkdir -p ..../remote.php/webdav/Photos/                 
```

But the following does not and this is unexpected (because of the rsync-like trailing-slash to in "./photos/"):
```
echo "mirror -Rv ./photos/ ./Photos/" | lftp https://...com/remote.php/webdav/
mkdir -p ..../remote.php/webdav/Photos/photos/          
```

**Comment by lavv17** [comment]
It's a documented feature: 

> If the target directory ends with a slash (except the root), the source base name is appended to target directory name.

Maybe an exception should be added for the case when the source directory also ends with a slash.
