### ISSUE TITLE
"put" from named pipe not working under Cygwin 2.5.1 (x64)

### ISSUE THREAD

**Issue by bobdole4prez** [lavv17/lftp#239]
Hi there,

If I do `mkfifo pipe` in the Cygwin Bash terminal, and then do `put pipe` from within lftp, I get:
`put: /pathto/pipe: Communication error on send`.

This happens whether or not I've already opened the pipe for writing.  I am using lftp 4.6.5, the version packaged with Cygwin 2.5.1.  Not sure if the problem is with lftp or Cygwin...

Thank you for this great program!

**Comment by lavv17** [comment]
I can put a fifo on Linux. I think it's a cygwin-specific problem.

**Comment by bobdole4prez** [comment]
Yes, it works for me too in Linux.  It's too bad that it doesn't work 
under Cygwin.  Would it be more appropriate to report this issue to the 
Cygwin developers?

Thank you.

**Comment by lavv17** [comment]
Yes, I think so.

ср, 18 мая 2016, 17:05 bobdole4prez <notifications@github.com>:
