### ISSUE TITLE
gnutls >= 1.0.0 configure error on Debian wheezy

### ISSUE THREAD

**Issue by mloskot** [lavv17/lftp#24]
I'm trying to build lftp from git on Debian Wheezy with GnuTLS 2.12 installed from  libgnutls-dev](http://packages.debian.org/wheezy/libgnutls-dev) package and I'm getting this error:

```
...
checking for tgetstr... yes
checking for readline... yes
./configure: line 46751: syntax error near unexpected token `LIBGNUTLS,'
./configure: line 46751: `   PKG_CHECK_MODULES(LIBGNUTLS, gnutls >= 1.0.0,'
```

I guess, it is possible this error is related to [compile problems with >=gnutls-2.7.0](http://www.mail-archive.com/lftp@uniyar.ac.ru/msg03408.html). It looks this post hasn't been followed up, so the patch has not been applied.

**Comment by davehouser1** [comment]
Was having the same problem had to install the following:
- `sudo apt install pkg-config`
- `sudo apt install libgnutls28-dev`
