### ISSUE TITLE
feature request: --ignore-existing option to mirror

### ISSUE THREAD

**Issue by drzraf** [lavv17/lftp#245]
Because that's a useful option.

Sample use-case:
A given tree is shared among two hosts but a part of the subtree somehow overlap (a "reference" and a "slave/modified/compressed" version).
`--ignore-existing` helps uploading from the slave only the missing files, without overriding original files.

**Comment by lavv17** [comment]
doesn't --only-missing option do?

**Comment by drzraf** [comment]
> doesn't --only-missing option do?

that would be a good option-name too
(would just need to see how it "integrates" with other options)

**Comment by lavv17** [comment]
I mean it's already there.

**Comment by drzraf** [comment]
oh!
(but no documented in `help mirror`)

**Comment by lavv17** [comment]
I think it's necessary to add "see the man page" to the help, as it's not
complete.

чт, 26 мая 2016, 15:44 Raphaël Droz <notifications@github.com>:
