### ISSUE TITLE
Mirror and repeat

### ISSUE THREAD

**Issue by cassiobsilva** [lavv17/lftp#248]
Hello,

I was trying to use the mirror option with `--loop` active to copy files again if an error occurs, but the mirror ended without copying the files, so I tried using `repeat --while-ok mirror [..]` bit it didn't work out either and the mirror job begun to run in an endless loop.

The `--loop` option only works when the mirror there aren't any errors?
It is possible to combine the `-c 5` and `--while-ok` repeat options to stop when one of them are met?

Thanks

**Comment by lavv17** [comment]
If you want to retry mirror in case of an error, use repeat --until-ok.

чт, 2 июня 2016, 17:09 Cássio Böck <notifications@github.com>:
