### ISSUE TITLE
modified files are not reflected on target machine

### ISSUE THREAD

**Issue by Chintanvpatel** [lavv17/lftp#252]
Hello,

We are using lftp mirror command to upload src on target machine ( ftp ). But in some cases modified files are not uploaded.

Suppose i have file with below content.

`example-123`

When i run lftp mirror then it successfully uploaded on target machine. 

Later if i change file content as below

`example-456`

then file is not affected after running lftp mirror command. Because there is no character change in previous and current changes. 
But actually file content has been changed. so it should be uploaded. We are using below command

`mirror --reverse --parallel=10 -p --no-symlinks --no-perms --ignore-time --exclude .git/ $LFTPOPTIONS $SOURCEFOLDER $TARGETFOLDER`

May be because it compare only number of characters i don't know. 

Thanks,
Chintan Patel

**Comment by lavv17** [comment]
Don't use --ignore-time if you need to compare file modification times.

пт, 1 июля 2016, 8:25 Chintan V. Patel <notifications@github.com>:

**Comment by Chintanvpatel** [comment]
Hello @lavv17 ,
I need to compare files by its content not modification times. 
As you can see in my example that content is changed but content length is same. So it should marked as modified unless file content length of both files are same.

**Comment by lavv17** [comment]
Lftp cannot compare files by contents, only by size and modification time.
If remote server kept a checksum and could report it, then lftp could use
it, but it's not the case.

вс, 3 июля 2016, 14:26 Chintan V. Patel <notifications@github.com>:

**Comment by Chintanvpatel** [comment]
Ok @lavv17 . I understand. Thanks for clarification. Closing issue.
