### ISSUE TITLE
segmentation fault with CSWlftp 4.6.1

### ISSUE THREAD

**Issue by xuying23** [lavv17/lftp#255]
After I installed CSWlftp 4.6.1, I got segmentation fault right after I issue lftp without any option.

pstack core
core 'core' of 13979:   lftp
 fec8d100 baudrate (ffbffc2a, 1, ffbff534, 1, 145600, fe7df838) + 24
 fe7b7bb8 tgetent  (14af88, ffbffc2a, 0, 27cac, fe7df838, ffffffff) + 30
 fecfacb8 _rl_init_terminal_io (ffbffc2a, 1, fed1740c, fed1ba44, fed1ca00, 0) + e4
 fecdffd4 readline_initialize_everything (fed18da0, 100, 131b14, fed18de4, fed18dcc, 0) + c0
 fecdfe74 rl_initialize (0, 131ad8, 13c698, fed18db0, 0, fed18d98) + 34
 fecdeaf4 readline (137dd0, 0, 0, 0, 0, fed18dc8) + 44
 000499f0 lftp_readline (137dd0, fed1cb2c, fed1cb70, fed1b870, 369a, 131000) + 4
 00045704 _ZN14ReadlineFeeder7NextCmdEP7CmdExecPKc (14ad80, 13d9b8, 137dd0, 130000, ffbff7b4, 14ad80) + 60
 0004e730 _ZN7CmdExec2DoEv (13d9b8, 44bf0, 1029b0, 44be8, 1384b0, 13d9b8) + 3c0
 00086860 _ZN6SMTask12ScheduleThisEv (0, 130898, 130448, 130898, 577ebdc4, 13d9b8) + cc
 00086a58 _ZN6SMTask8ScheduleEv (130478, 1308a4, 0, 0, 140828, 140818) + ac
 0004bc08 _ZN3Job8WaitDoneEv (13d9b8, 13ce30, 0, 0, 49dd8, 130478) + 20
 000ff4a0 main     (1, ffbffac4, 130000, 14ad80, 130000, 13ce30) + 2b4
 00044960 _start   (0, 0, 0, 0, 0, 0) + 5c

Any idea?  I have 4.5.5 installed on other server without any issue.  I tried to remove 4.6.1 and install 4.5.5 on the server, but it still core dumped.  Maybe other dependency packages caused the issue?

**Comment by lavv17** [comment]
I think the issue belongs to the CSW packager.
