### ISSUE TITLE
Delaying before reconnect (above 200 seconds) error

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#256]
lftp -v
LFTP | Version 4.6.3a

sudo lftp -u user,pass 1.2.3.4 -p 50000 -e "set net:timeout 5;set net:reconnect-interval-base 5;set ftp:ssl-allow yes; set ssl:verify-certificate no"

Is there an way to skip that delay? or set it to maximal 5 seconds ?

**Comment by lavv17** [comment]
You can set net:reconnect-interval-base to 0 or set net:reconnect-interval-multiplier to 1

**Comment by sunadtudk** [comment]
just did :  
nano /etc/lftp.conf 
and insert (into the file): 
set net:reconnect-interval-base 0

**Comment by magicmaravell** [comment]
set net:reconnect-interval-base 0
worked for me
