### ISSUE TITLE
lftp crashes on tab completion

### ISSUE THREAD

**Issue by grw1983** [lavv17/lftp#258]
Connecting to a remote ssh-server via fish:// and then using TAB-completion
lftp instantly crashes. gdb bt shows:

> lftp user@host:~> cd /d
> Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff64d8c77 in __strcpy_sse2_unaligned () from /usr/lib/libc.so.6
> (gdb) bt
> #0  0x00007ffff64d8c77 in __strcpy_sse2_unaligned () from /usr/lib/libc.so.6
> #1  0x00000000004dbae4 in Fish::SendMethod() ()
> #2  0x00000000004dd35d in Fish::Do() ()
> #3  0x0000000000484b73 in SMTask::Roll(SMTask*) ()
> #4  0x00000000004e7f95 in GenericParseListInfo::Do() ()
> #5  0x0000000000484ca5 in SMTask::ScheduleThis() ()
> #6  0x0000000000484e89 in SMTask::Schedule() ()
> #7  0x0000000000440c3a in ?? ()
> #8  0x00007ffff7434867 in gen_completion_matches () from /usr/lib/libreadline.so.6
> #9  0x00007ffff7434a40 in rl_complete_internal () from /usr/lib/libreadline.so.6
> #10 0x00007ffff742bd37 in _rl_dispatch_subseq () from /usr/lib/libreadline.so.6
> #11 0x00007ffff742c1c2 in readline_internal_char () from /usr/lib/libreadline.so.6
> #12 0x00007ffff742c8e5 in readline () from /usr/lib/libreadline.so.6
> #13 0x0000000000441c46 in lftp_readline ()
> #14 0x000000000043dfe4 in ReadlineFeeder::NextCmd(CmdExec*, char const*) ()
> #15 0x0000000000446dc1 in CmdExec::Do() ()
> #16 0x0000000000484ca5 in SMTask::ScheduleThis() ()
> #17 0x0000000000484e89 in SMTask::Schedule() ()
> #18 0x00000000004440c5 in Job::WaitDone() ()
> #19 0x000000000043b873 in main ()

KR,
grw

**Comment by lavv17** [comment]
Should be fixed in 4.7.3

**Comment by grw1983** [comment]
Right you are. Thank you!
