### ISSUE TITLE
how to use debug level

### ISSUE THREAD

**Issue by sinasalek** [lavv17/lftp#261]
I'm very confused regarding debug levels. appreciate any help
According to manual something like this should work. but it still print everything. Is this a bug?
I want to run it via cron, and throw error only when something is wrong

```
lftp -c "
  debug 2
  open $HOST
  user $USERNAME $PASSWORD
  mirror --parallel=5 --use-pget-n=5 $DIRECTION $REMOVE $ALL -v $BACKUP_REPOSITORY $FOLDER
  bye;
"
```

**Comment by lavv17** [comment]
There is README.debug-levels file which describes what different debug levels should mean.

**Comment by sinasalek** [comment]
I read that, although change debug level changes the output event when is set it to 0, but i'm unable to stop lftp from printing the following kind of logs, i'm using it in cron so it's important that it does not print anything unless there is an error otherwise i keep receiving email :
`
    ---- Connecting to backup.goldtagmail.com (91.98.99.18) port 21
    ---- Connecting to backup.goldtagmail.com (91.98.99.18) port 21
    <--- 250 CWD successful. "/incremental/data" is current directory.
    <--- 220-FileZilla Server 0.9.58 beta
`

**Comment by sinasalek** [comment]
I just realize that it was caused by -v in mirror command. i removed it.

**Comment by lavv17** [comment]
"debug off" should completely turn off debug messages.

чт, 15 сент. 2016, 11:38 Sina Salek <notifications@github.com>:
