### ISSUE TITLE
Create directory on local if 550 Permission Denied

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#263]
Why lftp do not create directory even if its 550 Permission Denied (from remote server)?

I see that lftp show that directory as output in local so why not created it?

**Comment by lavv17** [comment]
Is there a point in creating empty directories?
As it is done now, lftp creates local directory after it **cd** to the remote one.

**Comment by scriptzteam** [comment]
yes there is since the directory has info in dir name :)

can it just mirror everything, if there is dir on remote create it locally? even 550 error? isnt there any option like --ignore or so ...

**Comment by lavv17** [comment]
Please try df44e62f9b4902f4cf9b7d10a46819c2db00c011
