### ISSUE TITLE
Is cache really works?

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#264]
So i did this:

mirror -c -P0 --loop --use-cache --only-newer

when i run it again it getting info about dirs from remote folders, i need to skip that as i have all dirs on local, any way to skip this? 

STRUCTURE:

FOLDER1  
|-->SUB-FOLDER1  
      |-->SUB-FOLDER11  
|-->SUB-FOLDER2  
|-->SUB-FOLDER3  

FOLDER2  
|-->SUB-FOLDER1  
FOLDER3  
|-->SUB-FOLDER1

**Comment by lavv17** [comment]
I would guess that some information is missing (cannot be retrieved) so lftp tries to get it again.

**Comment by scriptzteam** [comment]
where is cache file located? so i can check cache file

**Comment by lavv17** [comment]
Lftp cache is memory only.

вт, 23 авг. 2016, 16:06 [sCRiPTz-TEAM] <notifications@github.com>:
