### ISSUE TITLE
Older than & Recursion missing Commands

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#265]
So what i am tryin to do is when remote folder is older than 15min it will download it, but i need "--recursion=missing" but the if on remote server is folder created before 1 minute i got it on local too but only empty folder, why lftp create folder on local server if its not older than defined 15min?

Command:

mirror -c -P0 --loop --use-cache --only-newer --older-than=now-15minutes --recursion=missing

**Comment by lavv17** [comment]
The option --older-than is only applied to plain files.

пт, 26 авг. 2016, 20:28 [sCRiPTz-TEAM] <notifications@github.com>:
