### ISSUE TITLE
What is for and against gnutls vs openssl?

### ISSUE THREAD

**Issue by AndrewSav** [lavv17/lftp#266]
In the contexts of this project, what are considerations I need to keep in mind when I choose to compile against gnutls or openssl? Are there any differences? Other impact?

**Comment by lavv17** [comment]
AFAIK, the main reason for GNU TLS was OpenSSL license. Technically they are very similar with some performance difference. In my experience OpenSSL is faster.

**Comment by AndrewSav** [comment]
Thank you! Any cross-platform consideration you might be aware of?
