### ISSUE TITLE
After losing internet connection for a couple of minutes, lftp didn't start the download again

### ISSUE THREAD

**Issue by rpgdev** [lavv17/lftp#268]
I was in the middle of a big download today when my internet connection at home went off for about 6 minutes. I thought that lftp would resume my download automatically after the network came back online but that wasn't the case. I was able to resume the download again after using the -c option but I'm wondering if there is a way for lftp to restart the download automatically after the network comes back up?

This is the command I used:
`queue pget -n 15 damn.iso`

This is the output I got when the connection went off: 
```
pget-chunk: damn.iso: ssh: Could not resolve hostname server.com: Name or service not known
pget-chunk: damn.iso: ssh: Could not resolve hostname server.com: Name or service not known
pget-chunk: damn.iso: ssh: Could not resolve hostname server.com: Name or service not known
pget-chunk: damn.iso: ssh: Could not resolve hostname server.com: Name or service not known
pget: damn.iso: ssh: Could not resolve hostname server.com: Name or service not known
```

I'm looking into some of the settings but I get confused. Would setting `dns:fatal-timeout` never effectively work for what I want to do? Or should I look into `net:reconnect-interval-*`? Or set `*:max-retries 0`? All those options seem to work on similar things but I'm not sure which one should I use to solve the issue. A little clarification would be appreciated.

**Comment by lavv17** [comment]
This error message from ssh is considered fatal, it says that the host name
doesn't exist.

ср, 7 сент. 2016, 6:36 rpgdev <notifications@github.com>:

**Comment by rpgdev** [comment]
Right but it was because the internet went off for a couple of minutes. Isn't that the error that it throws every time that happens?

**Comment by lavv17** [comment]
01dd0de may help a bit. The real solution would be to fix ssh (and/or libresolv, glibc) so that temporary DNS errors are reported properly.

It could be also possible to modify lftp to do name resolution inside lftp and pass numeric host addresses in turn to ssh.

**Comment by rpgdev** [comment]
There's no way to deal with that scenario via the settings then? It's not convenient to modify the code just because of this edge case. I was more interested in changing a setting or something. Do I take it that there isn't one to deal with this particular situation then?

**Comment by lavv17** [comment]
Unfortunately, there is no setting in lftp to control this. But you can try to modify /etc/nsswitch.conf; with `hosts: files dns` line I get `ssh: Could not resolve hostname no-such-name.com: Temporary failure in name resolution`.

**Comment by rpgdev** [comment]
I thought there would be a clean way to do it but I guess I'll just get by with it as it is. It doesn't happen often and the download can be restarted anyway. Thanks for taking the time to answer.

**Comment by lavv17** [comment]
I think the cleanest way is to change /etc/nsswitch.conf so that correct error message is shown by ssh.
