### ISSUE TITLE
feature request: globa/regexp for current directory entries and mirror command

### ISSUE THREAD

**Issue by arekm** [lavv17/lftp#270]
Hi.

What I'm missing in lftp is glob/regex support for mirroring current directory entries, so I could do:
````
queue mirror -c Dir0*
````

There is -i/-I option but according to manual it works only on files and not current level directory entries, so doesn't seem usable for my scenario.

**Comment by lavv17** [comment]
Please try ebc2ba3 (`mirror -F dir0*`)
FYI, -i/-I work on directories too, but they need a trailing slash to match.

**Comment by arekm** [comment]
Hm, doesn't fully work. I've tried to copy my music where I had like 10 directories matching that pattern:

````
queue mirror -F MusicAlbum*02*
````

but lftp started only 4 which seems to be matching my setting

````
set mirror:parallel-transfer-count 4
````
so I assume it somehow applied that limit. But it should start all 10 transfers, or queue them etc. With current behaviour I'm unable to mirror my music albums and still have to mirror one by one after first 4.

btw. documenting options for mirror in man page only is very misleading. I never know these tons of option existed :) (yes, there is "See lftp(1) for a complete list of options." in "help mirror" but I think I never saw such way in any other program, so wasn't expecting that).

**Comment by arekm** [comment]
Can't reproduce :( Works fine now in my testing. So it could me some mistake on my part when doing previous testing.

Thanks.
