### ISSUE TITLE
Case-insensitive completion

### ISSUE THREAD

**Issue by moll** [lavv17/lftp#271]
Hey,

A great FTP/SFTP app, but a thing has been bugging me for years: forced case-sensitive [auto]completion. Is there a way to have Lftp complete stuff case-insensitively when pressing tab? Shouldn't Lftp's Readline library really read the completion settings from `~/.inputrc` as GNU Readline's manpage hints?

Thanks!

**Comment by lavv17** [comment]
In lftp it's controlled by "cmd:cls-completion-default" setting. Try adding -i option there and see if it solves the problem.

**Comment by moll** [comment]
Superb. That did the trick! Thank you very much!

**Comment by goyalyashpal** [comment]
> "cmd:cls-completion-default" setting. Try adding -i option there

should it be made default?
