### ISSUE TITLE
Download files with specific extension while --newer-than=now-2days

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#272]
So is there a way i can download files with specific extension while --newer-than=now-2days, so for example all files newer than 2 days will be downloaded, but older than 2 days files will be downloaded ONLY with specific extension.

Thx!

**Comment by lavv17** [comment]
You can use two distinct mirror commands for that.

пт, 23 сент. 2016, 21:46 [sCRiPTz-TEAM] <notifications@github.com>:

**Comment by scriptzteam** [comment]
Ah easy thx so much! :)
