### ISSUE TITLE
lftp build fails with GCC-6.2 (ARC and ARM architectures)

### ISSUE THREAD

**Issue by vlad-zakharov** [lavv17/lftp#273]
Hi,
I tried to build lftp-4.7.3 from release tarball for both ARC and ARM architectures with GCC-6.2 and following errors occurred:

```
In file included from FileCopy.cc:39:0:
../lib/math.h: In function ‘int signbit(float)’:
../lib/math.h:2577:1: error: ‘int signbit(float)’ conflicts with a previous declaration
 _GL_MATH_CXX_REAL_FLOATING_DECL_2 (signbit)
 ^
In file included from .../output/br/lftp-armgcc6/host/usr/arm-buildroot-linux-uclibcgnueabi/include/c++/6.2.0/math.h:36:0,
                 from ../lib/math.h:27,
                 from FileCopy.cc:39:
.../output/br/lftp-armgcc6/host/usr/arm-buildroot-linux-uclibcgnueabi/include/c++/6.2.0/cmath:681:3: note: previous declaration ‘constexpr bool std::signbit(float)’
   signbit(float __x)
   ^~~~~~~
In file included from FileCopy.cc:39:0:
../lib/math.h: In function ‘int signbit(double)’:
../lib/math.h:2577:1: error: ‘int signbit(double)’ conflicts with a previous declaration
 _GL_MATH_CXX_REAL_FLOATING_DECL_2 (signbit)
 ^
In file included from .../output/br/lftp-armgcc6/host/usr/arm-buildroot-linux-uclibcgnueabi/include/c++/6.2.0/math.h:36:0,
                 from ../lib/math.h:27,
                 from FileCopy.cc:39:
.../output/br/lftp-armgcc6/host/usr/arm-buildroot-linux-uclibcgnueabi/include/c++/6.2.0/cmath:685:3: note: previous declaration ‘constexpr bool std::signbit(double)’
   signbit(double __x)
   ^~~~~~~
In file included from FileCopy.cc:39:0:
../lib/math.h: In function ‘int signbit(long double)’:
../lib/math.h:2577:1: error: ‘int signbit(long double)’ conflicts with a previous declaration
 _GL_MATH_CXX_REAL_FLOATING_DECL_2 (signbit)
 ^
```

Seems like lftp/lib.math.h header conflicts with GCC headers.

**Comment by lavv17** [comment]
Since lib/math.h is provided by gnulib, this issue should be redirected to
gnulib developers.

вт, 27 сент. 2016, 18:02 Vlad Zakharov <notifications@github.com>:

**Comment by awiouy** [comment]
Any update/fix for this issue?
Thank you in advance

**Comment by lavv17** [comment]
Have you reported the problem to gnulib developers?

**Comment by vlad-zakharov** [comment]
Hi, I have reported to gnulib mailing list, but I still haven't received any response.
Link to my e-mail:
http://lists.gnu.org/archive/html/bug-gnulib/2016-09/msg00071.html

**Comment by lavv17** [comment]
Just compiled with gcc version 6.2.1 20160916 (Red Hat 6.2.1-2) (GCC) - no problems

**Comment by drzraf** [comment]
same compile error on Debian 9, x86-64, gcc 4.6.3.0-4

**Comment by fragtion** [comment]
Seeing this on Ubuntu stable (with current packages), as well. gcc 7.3.0.

Do we know if any temporary workaround? I just want to compile binaries of latest git tree... Tx.

> Making all in src
> make[2]: Entering directory '/usr/local/src/lftp/lftp-github/src'
> /bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -MT PollVec.lo -MD -MP -MF .deps/PollVec.Tpo -c -o PollVec.lo PollVec.cc
> In file included from PollVec.cc:20:0:
> ../lib/config.h:1664:5: warning: option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++ [-Wpragmas]
>      _Pragma ("GCC diagnostic ignored \"-Wmissing-prototypes\"") \
>      ^
> mv -f .deps/PollVec.Tpo .deps/PollVec.Plo
> /bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -MT SMTask.lo -MD -MP -MF .deps/SMTask.Tpo -c -o SMTask.lo SMTask.cc
> In file included from SMTask.cc:20:0:
> ../lib/config.h:1664:5: warning: option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++ [-Wpragmas]
>      _Pragma ("GCC diagnostic ignored \"-Wmissing-prototypes\"") \
>      ^
> mv -f .deps/SMTask.Tpo .deps/SMTask.Plo
> /bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -MT ProcWait.lo -MD -MP -MF .deps/ProcWait.Tpo -c -o ProcWait.lo ProcWait.cc
> In file included from ProcWait.cc:20:0:
> ../lib/config.h:1664:5: warning: option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++ [-Wpragmas]
>      _Pragma ("GCC diagnostic ignored \"-Wmissing-prototypes\"") \
>      ^
> mv -f .deps/ProcWait.Tpo .deps/ProcWait.Plo
> /bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -MT GetPass.lo -MD -MP -MF .deps/GetPass.Tpo -c -o GetPass.lo GetPass.cc
> In file included from GetPass.cc:20:0:
> ../lib/config.h:1664:5: warning: option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++ [-Wpragmas]
>      _Pragma ("GCC diagnostic ignored \"-Wmissing-prototypes\"") \
>      ^
> GetPass.cc: In function ‘const char* GetPass(const char*)’:
> GetPass.cc:50:9: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
>     write(tty_fd,prompt,strlen(prompt));
>     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> GetPass.cc:63:9: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
>     write(tty_fd,"\r\n",2);
>     ~~~~~^~~~~~~~~~~~~~~~~
> mv -f .deps/GetPass.Tpo .deps/GetPass.Plo
> /bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -MT ConnectionSlot.lo -MD -MP -MF .deps/ConnectionSlot.Tpo -c -o ConnectionSlot.lo ConnectionSlot.cc
> In file included from ConnectionSlot.cc:20:0:
> ../lib/config.h:1664:5: warning: option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++ [-Wpragmas]
>      _Pragma ("GCC diagnostic ignored \"-Wmissing-prototypes\"") \
>      ^
> mv -f .deps/ConnectionSlot.Tpo .deps/ConnectionSlot.Plo
> /bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -MT CharReader.lo -MD -MP -MF .deps/CharReader.Tpo -c -o CharReader.lo CharReader.cc
> In file included from CharReader.cc:20:0:
> ../lib/config.h:1664:5: warning: option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++ [-Wpragmas]
>      _Pragma ("GCC diagnostic ignored \"-Wmissing-prototypes\"") \
>      ^
> mv -f .deps/CharReader.Tpo .deps/CharReader.Plo
> /bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -MT Cache.lo -MD -MP -MF .deps/Cache.Tpo -c -o Cache.lo Cache.cc
> In file included from Cache.cc:20:0:
> ../lib/config.h:1664:5: warning: option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++ [-Wpragmas]
>      _Pragma ("GCC diagnostic ignored \"-Wmissing-prototypes\"") \
>      ^
> mv -f .deps/Cache.Tpo .deps/Cache.Plo
> /bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -MT LsCache.lo -MD -MP -MF .deps/LsCache.Tpo -c -o LsCache.lo LsCache.cc
> In file included from LsCache.cc:20:0:
> ../lib/config.h:1664:5: warning: option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++ [-Wpragmas]
>      _Pragma ("GCC diagnostic ignored \"-Wmissing-prototypes\"") \
>      ^
> mv -f .deps/LsCache.Tpo .deps/LsCache.Plo
> /bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -MT FileAccess.lo -MD -MP -MF .deps/FileAccess.Tpo -c -o FileAccess.lo FileAccess.cc
> In file included from FileAccess.cc:20:0:
> ../lib/config.h:1664:5: warning: option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++ [-Wpragmas]
>      _Pragma ("GCC diagnostic ignored \"-Wmissing-prototypes\"") \
>      ^
> ../lib/config.h:1664:5: warning: option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++ [-Wpragmas]
>      _Pragma ("GCC diagnostic ignored \"-Wmissing-prototypes\"") \
>      ^
> mv -f .deps/FileAccess.Tpo .deps/FileAccess.Plo
> /bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio   -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -MT ResMgr.lo -MD -MP -MF .deps/ResMgr.Tpo -c -o ResMgr.lo ResMgr.cc
> In file included from ResMgr.cc:20:0:
> ../lib/config.h:1664:5: warning: option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++ [-Wpragmas]
>      _Pragma ("GCC diagnostic ignored \"-Wmissing-prototypes\"") \
>      ^
> ../lib/config.h:1664:5: warning: option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++ [-Wpragmas]
>      _Pragma ("GCC diagnostic ignored \"-Wmissing-prototypes\"") \
>      ^
> In file included from ResMgr.cc:26:0:
> ../lib/math.h: In function ‘int signbit(float)’:
> ../lib/math.h:2576:1: error: ‘int signbit(float)’ conflicts with a previous declaration
>  _GL_MATH_CXX_REAL_FLOATING_DECL_2 (signbit)
>  ^
> In file included from /usr/include/c++/7/math.h:36:0,
>                  from ../lib/math.h:27,
>                  from ResMgr.cc:26:
> /usr/include/c++/7/cmath:668:3: note: previous declaration ‘constexpr bool std::signbit(float)’
>    signbit(float __x)
>    ^~~~~~~
> In file included from ResMgr.cc:26:0:
> ../lib/math.h: In function ‘int signbit(double)’:
> ../lib/math.h:2576:1: error: ‘int signbit(double)’ conflicts with a previous declaration
>  _GL_MATH_CXX_REAL_FLOATING_DECL_2 (signbit)
>  ^
> In file included from /usr/include/c++/7/math.h:36:0,
>                  from ../lib/math.h:27,
>                  from ResMgr.cc:26:
> /usr/include/c++/7/cmath:672:3: note: previous declaration ‘constexpr bool std::signbit(double)’
>    signbit(double __x)
>    ^~~~~~~
> In file included from ResMgr.cc:26:0:
> ../lib/math.h: In function ‘int signbit(long double)’:
> ../lib/math.h:2576:1: error: ‘int signbit(long double)’ conflicts with a previous declaration
>  _GL_MATH_CXX_REAL_FLOATING_DECL_2 (signbit)
>  ^
> In file included from /usr/include/c++/7/math.h:36:0,
>                  from ../lib/math.h:27,
>                  from ResMgr.cc:26:
> /usr/include/c++/7/cmath:676:3: note: previous declaration ‘constexpr bool std::signbit(long double)’
>    signbit(long double __x)
>    ^~~~~~~
> Makefile:2205: recipe for target 'ResMgr.lo' failed
> make[2]: *** [ResMgr.lo] Error 1
> make[2]: Leaving directory '/usr/local/src/lftp/lftp-github/src'
> Makefile:1613: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/usr/local/src/lftp/lftp-github'
> Makefile:1558: recipe for target 'all' failed
> make: *** [all] Error 2
> root@jnb1:/usr/local/src/lftp/lftp-github# gcc --version
> gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
> Copyright (C) 2017 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> root@jnb1:/usr/local/src/lftp/lftp-github#

**Comment by tolot27** [comment]
Any fix on this?
