### ISSUE TITLE
Is set net:socket-bind-ipv4 ignored?

### ISSUE THREAD

**Issue by haisamido** [lavv17/lftp#274]
The below sftp command works, where I bind to a specific ip address:
` sftp -o BindAddress=172.31.4.24 user@example.com`

However, when I do 'ls' in lftp after setting the net:socket-bind-ipv4 lftp never connects:
```
lftp sftp://user@example.com
lftp user@example.com:~> set net:socket-bind-ipv4 172.31.4.24
lftp user@example.com:~> ls
`ls' at 0 [Connecting...]
```

so I've put the set command in ~/.lftp/rc and still not able to connect to remote host.

I'm using the following version:
`LFTP | Version 4.4.8 | Copyright (c) 1996-2013 Alexander V. Lukyanov`

on:
`Linux x86_64 x86_64 x86_64 GNU/Linux`

**Comment by haisamido** [comment]
interestingly this works:
`set sft:connect-program ssh -a -x -b 172.31.4.24`

**Comment by haisamido** [comment]
ls

**Comment by lavv17** [comment]
The setting net:socket-bind-ipv4 is only applied to sockets created by lftp
itself, not ones created by external programs like ssh.

вт, 27 сент. 2016, 18:48 Haisam Ido <notifications@github.com>:

**Comment by haisamido** [comment]
I see! So what I did here:

`set sftp:connect-program ssh -a -x -b 172.31.4.24`

a good work around or is there an alternative?

**Comment by lavv17** [comment]
I think it is the right way to bind ssh to an address.

чт, 29 сент. 2016, 16:48 Haisam Ido <notifications@github.com>:
