### ISSUE TITLE
Temporary freeze when using fallocate with NTFS in Linux

### ISSUE THREAD

**Issue by dikei** [lavv17/lftp#275]
Step to reproduce:

1. Set file:use-fallocate to true
2. `pget` a big file to a NTFS filesystem in Linux

What happen:
1. lftp freezes while allocating the file
2. After the file allocation is completed, the program resume operation as normal

My guess is because ntfs-3g does not support fallocate, posix_fallocate is emulated with inefficient read-write, which is extremely slow.

**Comment by dikei** [comment]
I just realized that this issue is similar to #257 
May be you should mention it in the documents of file:use-fallocate .

**Comment by lavv17** [comment]
Please try 357c7c2bcfb595df1b355720a4cd7a995e2b8703

**Comment by dikei** [comment]
Looking good. The program no longer hangs when allocating files with that commit.
