### ISSUE TITLE
Lftp reads wrong permissions over ftps

### ISSUE THREAD

**Issue by AndreaGiardini** [lavv17/lftp#277]
I'm using lftp with duplicity to backup my server to a remote NAS. The Nas has a folder called `Backup_Andrea` that my user can access over ftps and write file on it.

When duplicity runs the following commands with lftp the operation fails:

```
Running 'lftp -c 'source /tmp/duplicity-Wv7Tf8-tempdir/mkstemp-0YrdAE-1;put '/tmp/duplicity-Wv7Tf8-tempdir/mktemp-tuCZ9B-3' -o 'Backup_Andrea/owncloud/duplicity-full.20161001T082403Z.vol1.difftar.gz''' failed with code 1 (attempt #1)
Error is:
put: /tmp/duplicity-Wv7Tf8-tempdir/mktemp-tuCZ9B-3: Access failed: 552 Disk full - please upload later (Backup_Andrea/owncloud/duplicity-full.20161001T082403Z.vol1.difftar.gz)
```

The disk on the remote NAS not full and i have write access. In fact the following command works:
```
Running 'lftp -c 'source /tmp/duplicity-Wv7Tf8-tempdir/mkstemp-0YrdAE-1;cd 'Backup_Andrea';put '/tmp/duplicity-Wv7Tf8-tempdir/mktemp-tuCZ9B-3' -o 'owncloud/duplicity-full.20161001T082403Z.vol1.difftar.gz''' failed with code 1 (attempt #1)
Error is:
put: /tmp/duplicity-Wv7Tf8-tempdir/mktemp-tuCZ9B-3: Access failed: 552 Disk full - please upload later (Backup_Andrea/owncloud/duplicity-full.20161001T082403Z.vol1.difftar.gz)
```

**Comment by AndreaGiardini** [comment]
Actually... it might be a problem in the NAS Ftp server... This is ftpd --debug

```
---- Connecting data socket to (MYIP) port MYPORT
---- Data connection established
---> ALLO 52430267
<--- 552 Disk full - please upload later
---> STOR Backup_Andrea/owncloud/duplicity-inc.20161001T083537Z.to.20161001T085032Z.vol1.difftar.gz
---> ABOR
---- Closing aborted data socket

```

**Comment by AndreaGiardini** [comment]
Indeed...

Deleting this if and recompiling fixes the problem (the upload completes successfully)
https://github.com/lavv17/lftp/blob/master/src/ftpclass.cc#L2137

What do you think about it?

**Comment by AndreaGiardini** [comment]
Just to add more details...

My user can't write to `/` but only inside `Backup_Andrea`. When lftp sends the ALLO command with the size of the file that it is about to send the server replies (more or less) correctly that it shouldn't write there.

If you want i can make a pull request removing those lines, they seems quite unnecessary to me (also the comment in the code is stating that)

**Comment by lavv17** [comment]
Use 'set ftp:use-allo no'.

сб, 1 окт. 2016, 12:36 Andrea Giardini <notifications@github.com>:

**Comment by AndreaGiardini** [comment]
Indeed... it works :) Thanks!
