### ISSUE TITLE
Mirror only dirs/file IN BETWEEN DEFINED TIME possible?

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#283]
Mirror only dirs/file IN BETWEEN DEFINED TIME possible?

Example non working `mirror --older-than=now-5minutes --newer-than=now-2days`

The dirs/files should be NOT newer than 5 minutes and NOT older than 2 days, any way of doing this in ONE mirror command?

**Comment by lavv17** [comment]
Looks like this should work. What is the problem exactly?
