### ISSUE TITLE
[Feature] Check if specific named directory or file exist on remote source

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#284]
So what about to have in lftp that we can check if specific named directory or file exist on remote source, if for example in dir /TEST/blahblah/myfile.ext is exist the mirror will start its job, if not, no mirror just skip it

possible?

**Comment by lavv17** [comment]
There are .empty and .notempty hidden undocumented commands (TODO: document them) which can be used for that:
`glob -f .notempty file*.txt && mget file*.txt`
The problem with current glob is that it does not really check for file existence if there is no glob meta-characters.

**Comment by lavv17** [comment]
So for your case:
`glob -f .notempty TEST/blahblah/myfile.ex[t] && mirror`

**Comment by lavv17** [comment]
Hey! I've just found **glob** options **--exist** and **--not-exist** which can be used to solve your problem. Try

`glob --exist TEST/blahblah/myfile.ex[t] && mirror`

It looks better than .notempty hack (although uses it internally). And the options are documented in the man page!

**Comment by scriptzteam** [comment]
Thx really great!

This works well on files but how to check if folder [SOMETHING] - ( 100M 20F - COMPLETE ) - [SOMETHING] exists,

So it becomes -` SOMETHING `can be anything like in regex *
`100M `can be for example 14440M so again like *M
`20F `can become 500F so like *F
- `COMPLETE `part stays

can ther be a regex if folder exists like this :  `[*] - ( * * - COMPLETE ) - [*]`

**Comment by lavv17** [comment]
Sure, just quote the square brackets, as they have a special meaning in the
glob pattern.

ср, 4 янв. 2017, 14:19 [sCRiPTz-TEAM] <notifications@github.com>:

**Comment by scriptzteam** [comment]
the problem is now that it will just stuck at first subfolder and dont go deeper and on the first subfolder there is no the folder with COMPLETE only in next sub-sub folder

I do this cmd:

`glob --exist -d "\[SOMETHING\] \- \( * \) \- \[SOMETHING\]" && mirror --exclude ".{140,}" --exclude "/[^/]{64,}" -c --loop --use-cache --newer-than=now-1hour --recursion=newer $remote_dir $local_dir`

like it goes this way:

/SOME_FOLDER/some_sub/ <-- here it stuck
/SOME_FOLDER/some_sub/some_more_sub_folder/[SOMETHING] - ( 100M 20F - COMPLETE ) - [SOMETHING] <-- there is that dolder

**Comment by lavv17** [comment]
You can use "glob * */* */*/*" (you get the idea) if you know the maximum
depth.

ср, 4 янв. 2017, 14:33 [sCRiPTz-TEAM] <notifications@github.com>:
