### ISSUE TITLE
mirror doesn't copy files starting with ~ (tilde) character (4.7.2-1, debian testing)

### ISSUE THREAD

**Issue by sda2b** [lavv17/lftp#285]
Hello, I have a small issue with lftp (4.7.2-1, Debian Testing) 

I'm using "mirror -c -P4 --delete" to mirror a folder on my server to local. 

The folder on my server contains files starting with ~ (tilde) but lftp doesn't save them to local.

There was no issues when I was running Debian Jessie (4.6.0-1+deb8u1)

Thanks for your help.

**Comment by lavv17** [comment]
Which protocol do you use? I cannot reproduce it with ftp.
