### ISSUE TITLE
when "base href" does not begn with "http:" nothing is downloaded.

### ISSUE THREAD

**Issue by MadMaverick9** [lavv17/lftp#286]
Example: http://download.virtualbox.org/virtualbox/4.2.16/

Nothing is downloaded, because the "base href" html tag does not begin with "http:".

Possible patch:

```
--- ./src/HttpDir.cc.orig       2016-02-20 20:57:52.000000000 +0000
+++ ./src/HttpDir.cc    2016-10-31 00:48:47.609485691 +0000
@@ -760,7 +760,11 @@
    {
       if(base_href)
       {
-        base_href->set(link_target);
+         if (link_target.begins_with("//")) {
+           base_href->set((new xstring("http:"))->append(link_target));
+         } else {
+           base_href->set(link_target);
+         }
         Log::global->Format(10,"Using base href=%s\n",base_href->get());
       }
       return tag_len;
```

**Comment by lavv17** [comment]
Thanks for report!
But I think link_target should be prefixed in all possible links. Besides, your patch creates a memory leak (the new xstring goes astray).
Please see if 5a9b6f7 fixes the problem.

**Comment by MadMaverick9** [comment]
Wow - that was fast!

Thanks - that fixed it.
