### ISSUE TITLE
LFTP in combination with WordMove really slow

### ISSUE THREAD

**Issue by Walkeezy** [lavv17/lftp#289]
Hi

I'm using LFTP on a Ubuntu machine in combination with [WordMove](https://github.com/welaika/wordmove). Since last friday all transfers with LFTP are awfully slow and I'm getting the following message after every transferred file:

`mirror: edit-form-advanced.php: file size decreased during transfer`

Any idea what's causing this? Would be glad if someone could point me in the right direction.

Thanks!

**Comment by lavv17** [comment]
Please check the lftp version being used. Upgrade to the last one, then
enable debug in lftp and send the output to me.

пн, 14 нояб. 2016 г. в 17:56, Kevin Walker <notifications@github.com>:

**Comment by Walkeezy** [comment]
Nevermind, switched to using Wordmove with SSH instead of FTP.
