### ISSUE TITLE
Skip long titled paths?

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#293]
Using latest lftp and latest ubuntu.

`mirror: Access failed: /home/bleh/blah/blaaah/bleeh/SOMEOTHERDIR/muchDIR/suuuuuuuuuuuuuuuuuuuuuuuuuuuuuppppppppppppppppppppppeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrlllllllloooooooooonnnnngggggggggfoldeeeeerrr/suuuuuuuuuuuuuuuuuuuuuuuuuuuuuppppppppppppppppppppppeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrlllllllloooooooooonnnnngggggggggfile.test: File name too long`

**Comment by lavv17** [comment]
I think it is an operating system or a file system limitation. How do you suppose lftp should handle it?

**Comment by scriptzteam** [comment]
I use ubuntu latest, anyway lftp should skip those like **--skip-long-titled** and some parameter or without

**Comment by scriptzteam** [comment]
it is really not great now since i have repeat until-ok set on mirror, and when it comes to that loong files it just repeating the same that "File name too long" and wont proceed mirror on other folders, anywa to skip that??

**Comment by lavv17** [comment]
Try --exclude ".{128,}"

**Comment by scriptzteam** [comment]
Thx so much! seems for now it works great, regardz.

:)
