### ISSUE TITLE
Assertion `!x.heap_index' failed

### ISSUE THREAD

**Issue by mvanleeu** [lavv17/lftp#295]
I compiled lftp 4.7.4 from source on a intel based QNAP system. When executing "mirror" or even "lftp -v" command, I get:
``` lftp: xheap.h:129: void xheap<T>::remove(xheap<T>::node&) [with T = Timer]: Assertion `!x.heap_index' failed.
Aborted ```

I haven't done extensive testing, but it looks like apart from printing the warning, in most cases the command functions properly nonetheless.

Host used to compile and to run lftp
- QNAP TS-459U+ running QTS v4.2.2 Build 20161102
- Intel(R) Atom(TM) CPU D525, 1Gb Ram
- uname -a  ->    Linux TT-NFS01 3.4.6 #1 SMP Wed Nov 2 12:20:57 CST 2016 x86_64 unknown
- lftp 4.7.4
- Optware / ipkg version 0.99.163
- Libraries used: Readline 6.1, Expat 2.0.1, GnuTLS 2.6.5, zlib 1.2.5   (Note that I compiled some of those libraries used, as they were either not available via Optware, or not found by configure script. In general, getting lftp compiled was quite hard due to some Qnap related quirks, like "file" command being in "/opt/bin")

[config.log.gz](https://github.com/lavv17/lftp/files/626845/config.log.gz)
[config.status.gz](https://github.com/lavv17/lftp/files/626844/config.status.gz)

_Not sure how to report bugs, including enough details for this problem, so **please me know if more details are needed**, or how I could help identify the problem / testing patches._

**Comment by lavv17** [comment]
Please run lftp under gdb and when it faults type "info stack" or just "bt", post the output.

**Comment by mvanleeu** [comment]
Have no access to github now, but recompiled from scratch and the problem
seems to be fixed. No assertion warning anymore.
Will update GitHub over the weekend, but you could already change the
status if you want.

**Comment by mvanleeu** [comment]
Could not reproduce again after recompilation.
