### ISSUE TITLE
lftp unable to download itself from official web page

### ISSUE THREAD

**Issue by arekm** [lavv17/lftp#297]
lftp 4.7.3 is not able to download itself:

````
lftp -c 'set ssl:verify-certificate no; set net:max-retries 3; set http:user-agent "PLD/Builder(v0.35)"; pget -n 10 -c "https://lftp.yar.ru/ftp/lftp-4.7.4.tar.xz" -o "lftp-4.7.4.tar.xz.tmp"'
````

and in lftp-4.7.4.tar.xz.tmp html page is saved.

I guess it is more server side/web page script issue (since curl/wget are able to download it just fine) but reporting here anyway with a hope it can be fixed.

**Comment by ml-** [comment]
Looks like the server doesn't like your user-agent string.

**Comment by lavv17** [comment]
I'll fix it soon.

вс, 4 дек. 2016, 23:54 Matthias Lisin <notifications@github.com>:

**Comment by lavv17** [comment]
Should be fixed now.

**Comment by arekm** [comment]
Works, thanks.

**Comment by arekm** [comment]
I guess you whitelisted our user-agent... and unfortunately we use different user agents in different places. Other place uses:
wget --user-agent=PLD/distfiles https://lftp.yar.ru/ftp/lftp-4.7.4.tar.xz
and that breaks things again.

No better way for that paywall? Maybe if referer header is not empty then paywall else direct download?

**Comment by ml-** [comment]
I think you'd be better off using a common user-agent instead of opening issues for each of your bots or whatever.

Also shame on you for calling it paywall. It's actually just the download page.

**Comment by lavv17** [comment]
I already have the referer check. I think I will white list PLD substring.

пн, 5 дек. 2016, 16:01 Arkadiusz Miśkiewicz <notifications@github.com>:

**Comment by arekm** [comment]
Hm, then referer check should be enough. This command:

 wget -d -S --user-agent "zupa" -d -S https://lftp.yar.ru/ftp/lftp-4.7.4.tar.xz

doesn't send referer at all, so server could just send xz directly. But in my testing html page is downloaded.

**Comment by lavv17** [comment]
Whitelisted PLD/. Please check if everything is ok now.
My intention was to show a gentle reminder to interactive users. Sorry if it bothered you.

**Comment by arekm** [comment]
That did the job. Thanks again.
