### ISSUE TITLE
When using temp files, `--continue` doesn't work

### ISSUE THREAD

**Issue by lobianco** [lavv17/lftp#298]
Hey there!

I'm using `lftp` (version `4.7.2`) to upload local files to a remote server. I've noticed that if I instruct it to use temp files, the `--continue` option doesn't work. The transfers just begin from byte 0 and the remote files are overwritten. Here's my function:

```bash
push_files ()
{   
    lftp -u <user,pass> sftp://server-ip << EOF
    set file:charset "UTF-8"
    set sftp:charset "UTF-8"
    set sftp:connect-program "ssh -a -x"
    set sftp:auto-confirm true
    set xfer:temp-file-name "*.copying.ignore"
    set xfer:use-temp-file true
    set mirror:use-pget-n 35
    set mirror:parallel-transfer-count 5
    set mirror:parallel-directories true
    mirror -R --continue "$1" "$2"
    quit
EOF
}
```

I've confirmed that `--continue` does work as expected when I comment out these two lines from above:

>    \# set xfer:temp-file-name "*.copying.ignore"
>    \# set xfer:use-temp-file true

If there's any more info I can provide, please let me know!

**Comment by lavv17** [comment]
Please test 9163759c5503ef0011af11e59071d010b46cc609
