### ISSUE TITLE
Resolver.cc:321:10: error: member reference base type 'const char' is not a structure or union

### ISSUE THREAD

**Issue by Schamschula** [lavv17/lftp#306]
While compiling lftp 4.7.5 under macOS (10.12.2 using MacPorts) I get the following errors:

Resolver.cc:321:10: error: member reference base type 'const char' is not a structure or union
      if(IN6_IS_ADDR_LINKLOCAL(address) && scope==0) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/netinet6/in6.h:292:7: note: expanded from macro 'IN6_IS_ADDR_LINKLOCAL'
        (((a)->s6_addr[0] == 0xfe) && (((a)->s6_addr[1] & 0xc0) == 0x80))
          ~~~^ ~~~~~~~
Resolver.cc:321:10: error: member reference base type 'const char' is not a structure or union
      if(IN6_IS_ADDR_LINKLOCAL(address) && scope==0) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/netinet6/in6.h:292:37: note: expanded from macro 'IN6_IS_ADDR_LINKLOCAL'
        (((a)->s6_addr[0] == 0xfe) && (((a)->s6_addr[1] & 0xc0) == 0x80))
                                        ~~~^ ~~~~~~~

I've attached the full build log file:
[lftp-4.7.5-main.log.gz](https://github.com/lavv17/lftp/files/688543/lftp-4.7.5-main.log.gz)

**Comment by fornwall** [comment]
I hit the same issue when compiling.

The problem seems to be line 322 in Resolver.cc:

```c++
if(IN6_IS_ADDR_LINKLOCAL(address) && scope==0) {
```

Here address is `const char *`, but IN6_IS_ADDR_LINKLOCAL should take a `const struct in6_addr *`. It may be that the platform which lftp has been compiled on previously hides the error by casting.
