### ISSUE TITLE
dumping logs to stdout

### ISSUE THREAD

**Issue by arekm** [lavv17/lftp#309]
Recently (probably 4.7.4) lftp started to print downloaded files to console like:

````
2017-01-08 11:26:44 fish://host@server/path/somefile -> /mnt/somefile 0-314646272 3.05 MiB/s
````
where it didn't do that before.
Defaults seem to be

````
> set -a |grep xfer:log
set xfer:log yes
set xfer:log-file ""
````

But manual disagrees
````
       xfer:log (boolean)
              when true, lftp logs transfers to a file from xfer:log-file setting.

       xfer:log-file (path to file)
              the file to log transfers to. Default is ~/.local/share/lftp/transfer_log or ~/.lftp/transfer_log.
````

Should xfer:log be false by default (resonable IMO) and xfer:log_file to what manual says? (conditional default is weird though)

**Comment by lavv17** [comment]
should be fixed in dce9a49f351f56b6aa3b453086b67389c50c5307, please test.

**Comment by severach** [comment]
Something bad has happened. These options have completely disappeared.

**xfer:log: invalid compatibility alias. Use `set -a' to look at all variables.**

```
$ pacman -Q lftp
lftp 4.7.6-1

lftp :~> version
LFTP | Version 4.7.6 | Copyright (c) 1996-2017 Alexander V. Lukyanov
lftp :~> set -a
...
set xfer:keep-backup no
(where did they go)
set xfer:make-backup yes
...

lftp :~> version
LFTP | Version 4.7.5 | Copyright (c) 1996-2017 Alexander V. Lukyanov
lftp :~> set -a
...
set xfer:keep-backup no
set xfer:log yes
set xfer:log-file ""
set xfer:make-backup yes
...


```

I tried switching to the `set log::` options but these output the command detail and not the one line summary that I need.

**Comment by severach** [comment]
Comparing the set vars between 4.7.5 and 4.7.6 I see they have been renamed and a new one has been added?
````
Names 4.7.5
set xfer:log yes        
set xfer:log-file ""    
set xfer:max-log-size 1M

***

Names 4.7.6
set log:enabled/xfer yes          
set log:file/xfer ""
set log:max-size 1M               
set log:show-time/xfer yes
````

**Comment by lavv17** [comment]
The old names should work for compatibility, I'll fix it.

пт, 17 февр. 2017, 4:32 Chris Severance <notifications@github.com>:

**Comment by lavv17** [comment]
xfer:log fixed in 9a32e0d

log:max-size does not include xfer tag as it applies to all logs. If you want to limit size of a specific log file, use the closure (xfer or debug are currently available).

**Comment by lavv17** [comment]
No feedback, assuming fixed.

**Comment by severach** [comment]
I'm using the new log options and they are logging exactly as the old ones did before. I have not tested the old options.

**Comment by lavv17** [comment]
So is there a problem with the logging?

**Comment by severach** [comment]
Logging is fine. I switched my script to the new names. I haven't tried switching back to the old names so I don't know anything about them.

**Comment by StNick** [comment]
Sorry to dig up an old thread, but I am battling to get the summary line to show up when I wrap lftp in a node child_process.  I have set  set log:file/xfer "" and I am seeing the lines that look like:
2018-08-13 23:20:06 sftp://blah.com/private/file.zip -> /home/nick/file.zip 0-99256

But the one I am really after is the summary line:
12347832 bytes transferred in 12 seconds (17.28 MB/sec)

I am using pget or mirror, depending on whether I am fetching a single file or a folder and I want to be able to see what the final byte count and speed was.  This summary line contains the info I need, but it only seems to be displayed if the file transfer takes a certain amount of time, and/or was segmented.  What are the rules around this?  Is there a better way for me to get the information I'm after?

**Comment by lavv17** [comment]
Try cmd:interactive setting

пн, 13 авг. 2018, 14:40 Nick Soper <notifications@github.com>:

**Comment by StNick** [comment]
Fantastic!  That works, thanks.
