### ISSUE TITLE
QUESTION: "set xfer:verify-command"

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#310]
So i set set xfer:verify-command with some scripts i found over net, none worked out :D
Can you tell me please what set xfer:verify-command do? do it check every single file in log file? or what variables can i use from lftp and pipe it to my script?

**Comment by lavv17** [comment]
Probably you also need to set xfer:verify to the value "yes".

ср, 11 янв. 2017, 15:55 [sCRiPTz-TEAM] <notifications@github.com>:

**Comment by scriptzteam** [comment]
Yeas i did not works either, i do not see cksfv calculating anything :)

Tried this one - https://www.mail-archive.com/lftp@uniyar.ac.ru/msg02361.html

**Comment by lavv17** [comment]
Does it work if you run the script by hand? The argument is the file to be
checked.

ср, 11 янв. 2017, 18:42 [sCRiPTz-TEAM] <notifications@github.com>:

**Comment by scriptzteam** [comment]
Let me check :)

**Comment by scriptzteam** [comment]
root@root:/ENGLISH/MP3/0111/Yesyes-Need_More-WEB-2017-PITY# 
cat 00-yesyes-need_more-web-2017.sfv
01-yesyes-need_more-efb15874.mp3 efb15874

sh sfv_check /ENGLISH/MP3/0111/Yesyes-Need_More-WEB-2017-PITY/01-yesyes-need_more-efb15874.mp3

sfv_check: 34: sfv_check: /ENGLISH/MP3/0111/Yesyes-Need_More-WEB-2017-PITY/01-yesyes-need_more-efb15874.mp3 \n\n: not found
sfv_check: 39: [: mp3: unexpected operator
cat: '*.sfv': No such file or directory
SFV check 01-yesyes-need_more-efb15874.mp3: No SFV data found for this file!

**Comment by lavv17** [comment]
There are some internal problems with the script. Does it have execute
permission (chmod +x)?

ср, 11 янв. 2017, 18:49 [sCRiPTz-TEAM] <notifications@github.com>:

**Comment by scriptzteam** [comment]
`chmod +x sfv_check`, time ago :)

ls -alt
-rwxr-xr-x  1 root root    3733 Jan 11 15:04 sfv_check

**Comment by scriptzteam** [comment]
AAAnd finally when i copied the check script file into directory ta-daaa it worked so i think it has something with paths, how can i import current path where the file is downloaded? 

```
cd /ENGLISH/MP3/0111/Yesyes-Need_More-WEB-2017-PITY/

# bash lftp-verify 01-yesyes-need_more-efb15874.mp3

SFV check 01-yesyes-need_more-efb15874.mp3: OK
```
