### ISSUE TITLE
Cannot mirror a really large directory

### ISSUE THREAD

**Issue by stetskevych** [lavv17/lftp#316]
I need to download files from a remote SFTP server, but lftp fails. I am not sure how many files there are or about their size, but they should be small (less than 1MB each). I do not control the remote SFTP server.
Can you please help?
```
> mget *
Segmentation fault(358189) [Receiving data]
```
```
> mirror download
xmalloc: out of virtual memory when trying to get 942746994 bytes
```

**Comment by lavv17** [comment]
Try using a 64 bit OS.

пт, 3 февр. 2017, 7:57 Vyacheslav Stetskevych <notifications@github.com>:

**Comment by stetskevych** [comment]
It is 64-bit.

```
LFTP | Version 4.4.8

/usr/bin/lftp: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2

Amazon Linux AMI 2016.09

$ uname -i
x86_64
```

**Comment by lavv17** [comment]
Please use a newer lftp version. There were a few problems with large
directories fixed. The newest version is 4.7.5

пт, 3 февр. 2017, 9:32 Vyacheslav Stetskevych <notifications@github.com>:
