### ISSUE TITLE
mirror feature request: flatten directory structure

### ISSUE THREAD

**Issue by roessland** [lavv17/lftp#319]
I have a remote FTP folder structure set up like this:
```
A
   2017-02-09
      2017-02-09.1.txt
      2017-02-09.2.txt
      2017-02-09.3.txt
      [...]
   2017-02-08
      [...]
   ...
B
   2017-02-07
      [...]
   2017-02-06
      [...]
   ...
C
   2017-02-05
      [...]
   2017-02-04
      [...]
   ...
```

New files appear every few seconds, and every filename is globally unique. Since this folder structure is a bit annoying, I would like to flatten it into the target directory, producing a single directory with all the files.

I could use a bash script for this, but that would mess up the mirroring, wouldn't it?  A directory of symlinks is also a possibility, but not ideal.

**Comment by lavv17** [comment]
what do you suggest to do if file names conflict?
