### ISSUE TITLE
Assertion when mirroring file does not exist

### ISSUE THREAD

**Issue by rickydamelio** [lavv17/lftp#324]
I have a shell script which I use to pass an array of mirroring instructions to the lftp program. On earlier versions of the lftp program it didn't seem to matter if a file to be mirrored was inaccessible, it printed an error and moved on.

Now when this happens I am getting an assertion and my script stops.

> mirror: Access failed: 550 almanac: No such file or directory (/subdomains/nrl/httpdocs/live/feeds/m/almanac/m)
> mkdir: Access failed: /Users/ricky/.../almanac: No such file or directory
> Assertion failed: (transfer_count>0), function JobFinished, file MirrorJob.cc, line 242.
> 2016_ios_feed_scrape_script.sh: line 164: 70624 Abort trap: 6           lftp -u $ftp_username,$ftp_password -p 21 ftp.server.com  <<EOF

Is this assertion intended? What are the workarounds for this case if so?

**Comment by lavv17** [comment]
It is known bug which is already fixed on github. Thanks for report anyway!

чт, 2 марта 2017, 8:25 rickydamelio <notifications@github.com>:

**Comment by lavv17** [comment]
fixed by 579f41b58aad8f477a44e4d8fe62bc178ff39013 (dup of #320)
