### ISSUE TITLE
Cannot capture progress log from a script

### ISSUE THREAD

**Issue by stetskevych** [lavv17/lftp#330]
Hi Alexander!
I run lftp from a script using a here document as follows:

#!/bin/bash
echo "Starting transfer"
    lftp -p $port $protocol://$url <<EOT
    user $user $pass
    cd $remote_dir
    mput *
    quit
EOT
echo "Finished transfer"

Then I run this script from cron as follows:
*/10 * * * * ~/transfer_files.sh >/home/user/transfer_files.log 2>&1 

All I get in the  log is
> Starting transfer
> Finished transfer

How can I receive lftp progress output in the same log?

**Comment by lavv17** [comment]
To capture the status line, try "script" command.

чт, 16 марта 2017, 17:08 Vyacheslav Stetskevych <notifications@github.com>:

**Comment by stetskevych** [comment]
I'd prefer lftp to simply write it's progress to stdout/stderr.
Thanks anyway.

**Comment by lavv17** [comment]
The status line is not shown when the output is not a terminal.

**Comment by dustinbolton** [comment]
@lavv17 @stetskevych I tested the following setting to redirect the log to stdout when running from a script (don't forget to also enable to the log):
```
set log:file "/dev/stdout"
```

**Comment by lavv17** [comment]
The same can be achieved by "debug" command.

пн, 3 апр. 2017, 7:26 Dustin <notifications@github.com>:

**Comment by dustinbolton** [comment]
Accidentally removed the wrong comment. Original comment said: I tested the following setting to
 redirect the log to stdout when running from a script (don't forget to also
 enable to the log):
```
 set log:file "/dev/stdout"
```
