### ISSUE TITLE
put of empty files not possible in 4.7.x

### ISSUE THREAD

**Issue by teenooCH** [lavv17/lftp#332]
It is not possible to PUT an empty file anymore in version 4.7.x. This was not an issue in version 4.6.x

Tested with 4.7.3 and 4.7.6

**Comment by ml-** [comment]
I can not reproduce this with 4.7.7.

**Comment by teenooCH** [comment]
I'll try it with 4.7.7.
What FTP server did you use? We are using mostly ProFTPd and zOs/FTP

**Comment by ml-** [comment]
Tried with PureFTPd and bFTPd.
Are you sure it's a problem related to lftp and not the server software?

**Comment by teenooCH** [comment]
It is definitely a problem with lftp 4.7.x and ProFTPd. It does not exists in the combination lftp 4.6.x/ProFTPd.
I thought this is a general problem. I will do some research and come back here when I know more details.
Thank you for your answers
