### ISSUE TITLE
Run custom script after mirror with recursion done? Aka postprocess?

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#334]
Is there a way i can tell lftp to run custom script after each mirror recursion is done? I mean after every folder not after all mirrored folders ...

Like after it download one folder called 1.2.3.blah.blah it will run script.sh and in script.sh there will be args like $1 for full folder path and $2 for folder name etc :)

Thx!

**Comment by scriptzteam** [comment]
So any news on this? I think more users will agree sometimes its great to for example run custom script after mirror of folder or after mirror of single file do something with it :)

**Comment by lavv17** [comment]
There is possibility of running a script after transfer of a single file,
see xfer:verify-command setting.

пт, 7 апр. 2017, 21:33 [sCRiPTz-TEAM] <notifications@github.com>:

**Comment by scriptzteam** [comment]
i mean something like bash script? can be *.sh file run after?

**Comment by scriptzteam** [comment]
Thanks :)

**Comment by lavv17** [comment]
Do you still need to run a script after each directory processing?

вс, 9 апр. 2017, 9:50 [sCRiPTz-TEAM] <notifications@github.com>:

**Comment by scriptzteam** [comment]
I need to run it each FILE is mirrored as i will do in *.sh script move based on extension, but it still not works, any idea ?

**Comment by lavv17** [comment]
Did you enabled file verification by "set xfer:verify yes"?

чт, 13 апр. 2017, 15:34 [sCRiPTz-TEAM] <notifications@github.com>:

**Comment by scriptzteam** [comment]
It isnt set xfer:verify true ?

**Comment by ml-** [comment]
@scriptzteam Boolean settings can be one of (true, on, yes, 1, +) for a True value or one of (false, off, no, 0, -) for a False value.

**Comment by scriptzteam** [comment]
@ml and i said that here (above) https://github.com/lavv17/lftp/issues/334#issuecomment-293882832 "set xfer:verify true" so i ask @ lavv17 if there a difference between yes and true since in manual it say `when true` and not `when yes`

**Comment by lavv17** [comment]
True and yes are the same, no difference

чт, 13 апр. 2017, 17:21 [sCRiPTz-TEAM] <notifications@github.com>:

**Comment by scriptzteam** [comment]
Hmm then i am lost :D will try later again but none echo, also tried cp the file to a new location in bash script but not also works

**Comment by lavv17** [comment]
Try running the script by hand.

чт, 13 апр. 2017, 17:33 [sCRiPTz-TEAM] <notifications@github.com>:

**Comment by scriptzteam** [comment]
Thats the problem it works by hand, but via lftp not, even chmod `+x` set

**Comment by lavv17** [comment]
The output of verify-command is redirected to lftp itself and shown only if the exit code is non-zero as the verification error message. If you want to see the message, redirect to /dev/tty in the script.

**Comment by lavv17** [comment]
I've committed 8f2a91e debug message to see the verify-command being started.
