### ISSUE TITLE
Handling "421 Too many connections (8) from this IP" during mirror process?

### ISSUE THREAD

**Issue by dustinbolton** [lavv17/lftp#335]
If during a mirror process the server responds with as a "421 Too many connections..." error occurs, is there a way to either automatically or manually adjust the net:connection-limit to adapt to this without aborting the mirror process?

Due to situations beyond my control sometimes additional FTP connections from the same IP (from a non-lftp system) may be made during a mirror from the same IP but I would prefer to not have to always have the connection-limit set artificially low (for speed reasons) just to avoid this. I'm transferring a large number of files so the parallel connections are very helpful.  I'd like to either automatically or manually (or via script) bump the limit down so it can still proceed without hitting this limit over and over.

Perhaps a setting I'm missing, a key combination to pass in commands without aborting the mirror process, etc?

**Comment by lavv17** [comment]
I'll try to implement it. Thanks for suggestion!

вт, 4 апр. 2017, 1:49 Dustin <notifications@github.com>:

**Comment by dustinbolton** [comment]
Wonderful, thank you.

The following may be an overkill solution but something like the following would be ideal for my use case:

1. Once a "421 Too many connection errors..." error is received, reduce the connection limit, one at a time, until the "421 Too many connection errors..." error is no longer being received.
1. Wait a configurable number of minutes before either resetting back to the original connection-limit or ramping back up to the original connection-limit setting one connection at a time, stopping again for the defined amount of time if a "421" is received again before reaching the full limit.

Essentially this would allow the connection limit to "flex"/back off on demand while trying to maximize any available "slots" up to the maximum connection-limit.

Thanks in advance to whatever solution may come. You have built an absolutely beautiful piece of software.

**Comment by lavv17** [comment]
Can you provide me with all the "Too many" messages you know that ftp servers can produce? And when do they appear, after USER or PASS or?

**Comment by dustinbolton** [comment]
The first example seems to be most common by far, where 8 is the limit reached in this example.

```
421 Too many connections (8) from this IP
421 There are too many connections from your internet address.
421 Too many connections from this IP
421 Too Many Connections
421 Too many connections. Goodbye
```

It looks like the 421 "Too many" messages come shortly after connection, before USER or PASS is necessarily sent. I see a few instances where the logs show it just after USER and/or PASS but most cases of those if I look higher up in the log there was a connection made and it was just a parallel instance logging in between. It's a bit difficult to replicate since the log does not denote which parallel instance each log line is coming from and I'm having trouble replicating by throwing another app in the mix to try and get more precise logs because the FTP server begins refusing connections altogether often (perhaps an anti DDoS measure kicking in from all my connections?).

```
---- Connecting to _SERVER_ (_IP_) port 21
---- Got EOF on data connection
---- Closing data socket
<--- 421 Too many connections (8) from this IP
---> FEAT
---- Closing control socket
```

I may also se them after data socket connections. It's unfortunately difficult to tell from just the logs which parallel instance each log item is coming from for sure.
```
---- Connecting data socket to (_IP_) port 32184
<--- 421 Too many connections (8) from this IP
```

I can try and get some more precise timing if that would be helpful though it's proving a bit difficult.

**Comment by dustinbolton** [comment]
Actually, the data socket connection may not be resulting in a 421 Too Many connections message as my last reply stated as I tend to see a ```<--- 150 Accepted data connection``` shortly after that so it may just be limited to the first case.

**Comment by dustinbolton** [comment]
Trying this out with the Filezilla FTP server the 421 is returned after authenticating.  Filezilla at least allows you to configure the IP limit on a per-user basis so it waits until auth to determine if you are at your limit.

```
Status:      	Connecting to 192.168.0.209:21...
Status:      	Connection established, waiting for welcome message...
Response: 	220-FileZilla Server 0.9.60 beta
Response: 	220-written by Tim Kosse (tim.kosse@filezilla-project.org)
Response: 	220 Please visit https://filezilla-project.org/
Command:	AUTH TLS
Response: 	502 Explicit TLS authentication not allowed
Command:	AUTH SSL
Response: 	502 Explicit TLS authentication not allowed
Status:      	Insecure server, it does not support FTP over TLS.
Command:	USER site1
Response: 	331 Password required for site1
Command:	PASS *****
Response: 	421 Refusing connection. No more connections allowed from your IP.
Error:        	Could not connect to server
```

**Comment by lavv17** [comment]
Can you please try #337 ?

**Comment by dustinbolton** [comment]
I'm having trouble compiling on Mac OS unfortunately so I'm going to have to try again on another system later.

Ran into some issues having to remove the following line from configure.ac to stop complaints about duplicate entries in AC config:
AC_CONFIG_FILES([Makefile po/Makefile.in]) in configure.ac

Hit a dead end trying to get readline detected since it is keg-only and had to be symlinked:
checking for Readline headers in /usr/local/include/readline... not found
configure: error: cannot find readline library, install readline-devel package

Directory contains the following which either is not correct or readline rather than readline-devel but no luck getting that working on Mac properly I guess:
chardefs.h  history.h  keymaps.h  readline.h  rlconf.h	rlstdc.h  rltypedefs.h	tilde.h

I'll try again on another system later and hopefully get to testing #337 then.

**Comment by dustinbolton** [comment]
I'm able to successfully compile 4.7.7 by source but I cannot get #337 to make. Trying on Ubuntu 17.04 x86_64. Do you have any insight on the following? If I can get #337 going I'm happy to give it thorough testing with many servers.

```
In file included from ResMgr.cc:26:0:
../lib/math.h: In function ‘int signbit(float)’:
../lib/math.h:2576:1: error: ‘int signbit(float)’ conflicts with a previous declaration
 _GL_MATH_CXX_REAL_FLOATING_DECL_2 (signbit)
 ^
In file included from /usr/include/c++/6/math.h:36:0,
                 from ../lib/math.h:27,
                 from ResMgr.cc:26:
/usr/include/c++/6/cmath:691:3: note: previous declaration ‘constexpr bool std::signbit(float)’
   signbit(float __x)
   ^~~~~~~
In file included from ResMgr.cc:26:0:
../lib/math.h: In function ‘int signbit(double)’:
../lib/math.h:2576:1: error: ‘int signbit(double)’ conflicts with a previous declaration
 _GL_MATH_CXX_REAL_FLOATING_DECL_2 (signbit)
 ^
In file included from /usr/include/c++/6/math.h:36:0,
                 from ../lib/math.h:27,
                 from ResMgr.cc:26:
/usr/include/c++/6/cmath:695:3: note: previous declaration ‘constexpr bool std::signbit(double)’
   signbit(double __x)
   ^~~~~~~
In file included from ResMgr.cc:26:0:
../lib/math.h: In function ‘int signbit(long double)’:
../lib/math.h:2576:1: error: ‘int signbit(long double)’ conflicts with a previous declaration
 _GL_MATH_CXX_REAL_FLOATING_DECL_2 (signbit)
 ^
In file included from /usr/include/c++/6/math.h:36:0,
                 from ../lib/math.h:27,
                 from ResMgr.cc:26:
/usr/include/c++/6/cmath:699:3: note: previous declaration ‘constexpr bool std::signbit(long double)’
   signbit(long double __x)
   ^~~~~~~
Makefile:2205: recipe for target 'ResMgr.lo' failed
make[2]: *** [ResMgr.lo] Error 1
make[2]: Leaving directory '/home/ubuntu/337/lftp/src'
Makefile:1604: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/337/lftp'
Makefile:1549: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by magicmigration** [comment]
Unfortunately I'm still seeing issues with this. As you can see in this example too many connections were made for this server and all connections were closed. This was a mirror operation where it was mirroring between two different accounts on the same FTP server.

`07:30:00{ "message": "log_source: ---- CWD path to be sent is `/public_html'", "level": "info" }
07:30:00{ "message": "log_source: ---> CWD /public_html", "level": "info" }
07:30:00{ "message": "log_source: <--- 250 OK. Current directory is /public_html", "level": "info" }
07:30:00{ "message": "log_source: ---> PASV", "level": "info" }
07:30:00{ "message": "log_source: <--- 227 Entering Passive Mode (162,144,141,132,252,196)", "level": "info" }
07:30:00{ "message": "log_source: ---- Connecting data socket to (162.144.141.132) port 64708", "level": "info" }
07:30:00{ "message": "log_source: **** Data socket error (Connection refused) - reconnecting", "level": "info" }
07:30:00{ "message": "log_source: ---> MLSD", "level": "info" }
07:30:00{ "message": "log_source: ---> ABOR", "level": "info" }
07:30:00{ "message": "log_source: ---- Closing aborted data socket", "level": "info" }
07:30:00{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:05{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:05{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:05{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:05{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:10{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:11{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:11{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:11{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:16{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:16{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:16{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:16{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:21{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:21{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:21{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:21{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:26{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:26{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:26{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:26{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:31{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:31{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:31{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:31{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:36{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:36{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:36{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:36{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:36{ "message": "log_source: ---> QUIT", "level": "info" }
07:30:36{ "message": "log_source: <--- 221-Goodbye. You uploaded 0 and downloaded 0 kbytes.", "level": "info" }
07:30:36{ "message": "log_source: <--- 221 Logout.", "level": "info" }
07:30:36{ "message": "log_source: ---- Closing control socket", "level": "info" }`

**Comment by dustinbolton** [comment]
Unfortunately I'm still seeing issues with this. As you can see in this example too many connections were made for this server and all connections were closed. This was a mirror operation where it was mirroring between two different accounts on the same FTP server.

```07:30:00{ "message": "log_source: ---- CWD path to be sent is '/public_html'", "level": "info" }
07:30:00{ "message": "log_source: ---> CWD /public_html", "level": "info" }
07:30:00{ "message": "log_source: <--- 250 OK. Current directory is /public_html", "level": "info" }
07:30:00{ "message": "log_source: ---> PASV", "level": "info" }
07:30:00{ "message": "log_source: <--- 227 Entering Passive Mode (162,144,141,132,252,196)", "level": "info" }
07:30:00{ "message": "log_source: ---- Connecting data socket to (162.144.141.132) port 64708", "level": "info" }
07:30:00{ "message": "log_source: **** Data socket error (Connection refused) - reconnecting", "level": "info" }
07:30:00{ "message": "log_source: ---> MLSD", "level": "info" }
07:30:00{ "message": "log_source: ---> ABOR", "level": "info" }
07:30:00{ "message": "log_source: ---- Closing aborted data socket", "level": "info" }
07:30:00{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:05{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:05{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:05{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:05{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:10{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:11{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:11{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:11{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:16{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:16{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:16{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:16{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:21{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:21{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:21{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:21{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:26{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:26{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:26{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:26{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:31{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:31{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:31{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:31{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:36{ "message": "log_source: ---- Connecting to 162.144.141.132 (162.144.141.132) port 21", "level": "info" }
07:30:36{ "message": "log_source: <--- 421 Too many connections (8) from this IP", "level": "info" }
07:30:36{ "message": "log_source: ---> FEAT", "level": "info" }
07:30:36{ "message": "log_source: ---- Closing control socket", "level": "info" }
07:30:36{ "message": "log_source: ---> QUIT", "level": "info" }
07:30:36{ "message": "log_source: <--- 221-Goodbye. You uploaded 0 and downloaded 0 kbytes.", "level": "info" }
07:30:36{ "message": "log_source: <--- 221 Logout.", "level": "info" }
07:30:36{ "message": "log_source: ---- Closing control socket", "level": "info" }```
