### ISSUE TITLE
Compiling against non-system readline fails

### ISSUE THREAD

**Issue by areis422** [lavv17/lftp#336]
./configure --prefix=/usr --sysconfdir=/etc --with-expat=/opt/expat-2.2.0 --with-openssl=/usr --with-zlib=/opt/zlib-1.2.11 --with-readline=/opt/readline-7.0

During configure, seeing the following messages:
checking for Readline headers in /usr/include/readline... found
checking for Readline libraries... found
checking for Readline... yes
checking if Readline version is >= 5.0... yes

Plainly saying, the --with-readline, --with-readline-lib, and --with-readline-inc arguments to the configure don't actually apply.

**Comment by lavv17** [comment]
Please check if /opt/readline-7.0 is a symlink.

**Comment by lavv17** [comment]
> ./configure --with-readline=/home/lav/readline-prefix

> checking for Readline headers in /home/lav/readline-prefix/include/readline... found

> READLINE_CFLAGS = -I/home/lav/readline-prefix/include/readline
> READLINE_LDFLAGS = -L/home/lav/readline-prefix/lib

Seems to work here.

**Comment by areis422** [comment]
not a symlink

drew

On April 21, 2017 3:52:39 PM CDT, "Alexander V. Lukyanov" <notifications@github.com> wrote:
>Please check if /opt/readline-7.0 is a symlink.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lavv17/lftp/issues/336#issuecomment-296302885

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by areis422** [comment]
Alex,

Looks like it's also not compiling against the non-system zlib either

I see now where configure is actually setting the readline variables:
cat config.status | grep -i 'zlib\|readline'
ac_cs_config="'--prefix=/usr' '--sysconfdir=/etc' '--with-readline=/opt/readline-7.0' '--with-openssl=/usr' '--with-zlib=/opt/zlib-1.2.11'"
  set X /bin/sh './configure'  '--prefix=/usr' '--sysconfdir=/etc' '--with-readline=/opt/readline-7.0' '--with-openssl=/usr' '--with-zlib=/opt/zlib-1.2.11' $ac_configure_extra_args --no-create --no-recursion
S["ZLIB_CPPFLAGS"]="-I/opt/zlib-1.2.11/include"
S["ZLIB_LDFLAGS"]="-L/opt/zlib-1.2.11/lib"
S["ZLIB"]="-lz"
S["READLINE_VERSION"]="7.0"
S["READLINE_LIBS"]="-lreadline"
S["READLINE_LDFLAGS"]="-L/opt/readline-7.0/lib"
S["READLINE_CFLAGS"]="-I/opt/readline-7.0/include/readline"

But when running ldd against the compiled binary, it linked against the system readline:
ldd /tmp/lftp-4.7.7/src/lftp
	linux-gate.so.1 =>  (0x00de1000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00259000)
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00bd7000)
	**libz.so.1 => /lib/libz.so.1 (0x0021d000)**
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x00c31000)
	librt.so.1 => /lib/librt.so.1 (0x0024e000)
	**libreadline.so.6 => /usr/lib/libreadline.so.6 (0x0027b000)**
	libutil.so.1 => /lib/libutil.so.1 (0x001a5000)
	libncurses.so.5 => /usr/lib/libncurses.so.5 (0x028be000)
	libresolv.so.2 => /lib/libresolv.so.2 (0x00101000)
	libdl.so.2 => /lib/libdl.so.2 (0x00216000)
	libidn.so.11 => /usr/lib/libidn.so.11 (0x02152000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x022c8000)
	libm.so.6 => /lib/libm.so.6 (0x001eb000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x00186000)
	libc.so.6 => /lib/libc.so.6 (0x0033f000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x00232000)
	/lib/ld-linux.so.2 (0x001cc000)

And when running lftp --version on the compiled binary:
/tmp/lftp-4.7.7/src/lftp --version
LFTP | Version 4.7.7 | Copyright (c) 1996-2017 Alexander V. Lukyanov

LFTP is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with LFTP.  If not, see <http://www.gnu.org/licenses/>.

Send bug reports and questions to the mailing list <lftp@uniyar.ac.ru>.

Libraries used: **Readline 6.3, Expat 2.1.0, OpenSSL 1.0.2k  26 Jan 2017,
zlib 1.2.3**

Also, please reference Issue #229 which I put in a while ago that was supposedly fixed.

Thanks,
Drew

**Comment by lavv17** [comment]
Does setting LD_LIBRARY_PATH environment variable help?
Would adding -R /opt/readline-7.0/lib linker option help?

**Comment by lavv17** [comment]
Please try #339 PR.
