### ISSUE TITLE
Find command not working correctly

### ISSUE THREAD

**Issue by beyerleinf** [lavv17/lftp#341]
Hey :)

what I want to do is connect to a FTP server and delete all files older than X days using following command:
`find ./* -mtime +60 -type f -delete`

But what happens is that it tries to find the files named "-mtime" and so on

>`find: Access failed: 550 /FTP/dir/*: No such file or directory`
`find: Access failed: 550 /FTP/dir/-mtime: No such file or directory`
`find: Access failed: 550 /FTP/dir/+60: No such file or directory`
`find: Access failed: 550 /FTP/dir/-type: No such file or directory`
`find: Access failed: 550 /FTP/dir/f: No such file or directory`
`find: Access failed: 550 /FTP/dir/-delete: No such file or directory`

Or trying to find all zip files in a directory leads to a error
`lftp user@ftp.server.com:/FTP/dir> find ./*.zip`
>`find: Access failed: 550 /FTP/dir/*.zip: No such file or directory`

Do you have any suggestions? Thank you!
_Fabian_

**Comment by SuperdukeGates** [comment]
Hello,

As I know, the find command in lftp isn't implemented as what you expected as the find(1) in your system's /usr/bin/find.

In your case, maybe you need an external script (shell script or like) to do the filter and feedback the result lftp command back to the lftp. For example:
```
lftp> open user@ftp.server.com:/FTP/dir
lftp> find --ls > /tmp/serverlist.txt
lftp> ! /my/place/bin/find_older_files_script
lftp> source /my/place/bin/script_gen_lftp_commands
lftp> quit
```
Where `/my/place/bin/find_older_files_script` read the directory list from file `/tmp/serverlist.txt` and generate a lftp command script file `/my/place/bin/script_gen_lftp_commands`. The `/my/place/bin/script_gen_lftp_commands` includes the lftp commands like `rm some/where/file`.

**Comment by beyerleinf** [comment]
Hey, 

this was very helpful. Works like a charm :)

**Comment by lavv17** [comment]
Hello! As a side note, you can also use "source -e", one temporary file
less.

чт, 27 апр. 2017, 16:22 Fabian Beyerlein <notifications@github.com>:

**Comment by mgupta0421** [comment]
> Hey,
> 
> this was very helpful. Works like a charm :)

Hey, 
I have a query regarding this issue, please help
