### ISSUE TITLE
LFTP - Version 4.6.3a - Some errors 

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#344]
So recently today i started having problems like those i never had before:

`gnutls_record_recv: A TLS packet with unexpected length was received. Assuming EOF.`

```
pget-chunk: blahblahblah.zip: Fatal error: control-socket: Bad address
pget: chunk[0] error: Fatal error: control-socket: Bad address
```

`<---  REST STREAM
<---  SYST
<--- 211 End
---> AUTH TLS
<--- 234 AUTH TLS successful
---> USER ****
**** gnutls_handshake: A TLS packet with unexpected length was received.
---- Closing control socket
---- dns cache hit
---- attempt number 2 (max_retries=1000)
<--- 220 gLFTPd ready.
---> FEAT
<--- 211- Extensions supported:
<---  AUTH TLS
<---  AUTH SSL
<---  PBSZ
<---  PROT
<---  CPSV
<---  SSCN
<---  MDTM
<---  SIZE
<---  REST STREAM
<---  SYST
<--- 211 End
---> USER ******
**** control-socket: Bad address
---- Closing control socket
mirror: Fatal error: control-socket: Bad address
`

download speed is like 
`26.4K/s`

pls help!

**Comment by riksoft** [comment]
I have the same problem connecting to Microsoft FTP using lftp 4.4.13 (default in Ubuntu server 14.04.
<--- 220 Microsoft FTP Service
**** gnutls_handshake: A TLS packet with unexpected length was received.

In Mint 18 the repo contains lftp 4.6.3a and the same script works well.
So, at least in my case it's a matter of version.
On the version with the problem I've tried a lot of ssl forcing and on/off but I can't solve it.
