### ISSUE TITLE
--deference doesn't download symlink as files & remove-dirs doesn't behave

### ISSUE THREAD

**Issue by kcck** [lavv17/lftp#345]
Hello,

I tried the solution that you suggested here: https://github.com/lavv17/lftp/issues/290
I cannot get it to work

Basically I am trying to get lftp to download a symlink of the file via ssh.
If I create a symlink, it downloads the symlink
If I do a hardlink via cp -lr, it downloads the file twice, once as a folder then its content and an other folder in the first one with its content, therefore 2 download for 1 file/folder, ex: 
/home/downlod/movie/file.mvk then LFTP does: /home/downlod/movie/file.mvk/movie/file.mkv
Furthermore, you mention in you man page that only source-dies will be deleted if they dont end with a "/" that doesn't seem to work.

It took me 3 days to write the script and to almost get it to work, the first section has been modified a bit for testing, however it doesn't do what I want to do, 

I would like that only the downloaded file gets deleted with its folder but not the folder in which it resides ex: /home/download/movie/file.mkv
with remove-dirs, LFTP deletes all the way till download, which is not what I want, I'd like to keep the download folder
Here is a copy of my script, I would highly appreciate your assistance,

Regards,

KC

#!/bin/bash

USER="user"
PASS="pass"
HOST="server"
NOW=$(date +"%m-%d-%y_%H.%M.%S")
PORT=22
REMOTE_DIR1='/media/private/deluge/data/completed/movies-couch/LFTP/'
LOCAL_DIR1="/Users/SeedBox/movies-couch"
REMOTE_DIR2='/media/private/deluge/data/completed/tv-sonarr-kc/LFTP/'
LOCAL_DIR2="/Users/SeedBox/tv-sonarr"
REMOTE_DIR3='/media/private/deluge/data/completed/radarr/LFTP/'
LOCAL_DIR3="/Users/kc/SeedBox/radarr"

NFIL=3
NSEG=50
MINCHUNK=1M

echo "${0} Starting at $(date)"

BASE_NAME="$(basename "$0")"
LOCKF="/tmp/$base_name.lock"

trap "rm -f $lock_file" SIGINT SIGTERM
if [ -e "$lock_file" ]
then
    echo "$base_name is running already."
    exit
else

    touch "${LOCKF}"
    /usr/local/bin/lftp -p ${PORT} -u "${USER},${PASS}" sftp://${HOST} << EOF
    set ftp:list-options -L
    set xfer:use-temp-file yes
    set xfer:temp-file-name *.tmp
    set pget:min-chunk-size ${MINCHUNK}
    set pget:default-n ${NSEG}
    set mirror:use-pget-n ${NSEG}
    set mirror:parallel-transfer-count ${NFIL}
    set mirror:parallel-directories yes
    set mirror:no-empty-dirs true
    mirror -c -v --Remove-source-dirs --log="/Users/SeedBox/movies-couch.log" "${REMOTE_DIR1}" "${LOCAL_DIR1}"
    quit
EOF

    touch "${LOCKF}"
    /usr/local/bin/lftp -p ${PORT} -u "${USER},${PASS}" sftp://${HOST} << EOF
    set ftp:list-options -a
    set xfer:use-temp-file yes
    set xfer:temp-file-name *.tmp
    set pget:min-chunk-size ${MINCHUNK}
    set pget:default-n ${NSEG}
    set mirror:use-pget-n ${NSEG}
    set mirror:parallel-transfer-count ${NFIL}
    set mirror:parallel-directories yes
    set mirror:no-empty-dirs true
    mirror -c -v --Remove-source-dirs --log="/Users/SeedBox/tv-sonarr.log" "${REMOTE_DIR2}" "${LOCAL_DIR2}"
    quit
EOF

    touch "${LOCKF}"
    /usr/local/bin/lftp -p ${PORT} -u "${USER},${PASS}" sftp://${HOST} << EOF
    set ftp:list-options -a
    set xfer:use-temp-file yes
    set xfer:temp-file-name *.tmp
    set pget:min-chunk-size ${MINCHUNK}
    set pget:default-n ${NSEG}
    set mirror:use-pget-n ${NSEG}
    #set mirror:parallel-transfer-count ${NFIL}
    #set mirror:parallel-directories yes
    set mirror:no-empty-dirs true
    mirror -c -v --Remove-source-dirs --log="/Users/SeedBox/radarr.log" "${REMOTE_DIR3}"/ "${LOCAL_DIR3}"
    quit
EOF

    rm -f "$lock_file"
    trap - SIGINT SIGTERM
    echo "${0} Finished at $(date)"
    exit 0
fi

**Comment by lavv17** [comment]
The settings starting with ftp: are only applied to ftp protocol, not sftp.
For sftp you can try mirror --dereference, but it only works for plain
files.

The trailing slash makes lftp keep the top directory only, subdirectories
will be removed anyway, if the are empty.

пт, 12 мая 2017, 4:03 kcck <notifications@github.com>:

**Comment by kcck** [comment]
You mean that I cannot have sftp work with symlinks?
How do I get to keep the top directory? It does get deleted. Am talking about the directory of the file.
File gets deleted, folder of the file gets deleted and folder/folder/file gets deleted.
What would be the best config?

Regards

**Comment by klendgit** [comment]
I noticed it today with sftp protocol as well - lftp does **not** download the referenced file, but instead creates a symlink on the local machine.
This is clearly a bug with option -L or --dereference:
command used:
lftp -e 'mirror --dereference --max-errors=1 source && quit' -u X,Y sftp://og@172.30.x.y:/var/tmp/adi-auto-deploy/e2esi/

resulting content on local machine (ls -l source)
[og@lg-l-t-obo01634 ingest]$ \ls -l source
total 72
lrwxrwxrwx. 1 og og 97 Jun 9 11:45 ts0000_20170609_091138pt2.ts -> /var/TestData/00-00-29_3803kbs_mpeg2video_720x576_16x9_25fps_eng.mp2_NOSUB.videohouse_synctest.ts

Version 4.4.8

**Comment by lavv17** [comment]
Does it behave in the last version?

**Comment by klendgit** [comment]
You are correct, 4.4.8 is ancient and it does not happen on the latest release. Sorry for this, I should've checked this better.
