### ISSUE TITLE
Switch to libidn2 due to IDNA2008

### ISSUE THREAD

**Issue by mruprich** [lavv17/lftp#351]
Hi, 
every package included in Fedora that uses libidn library should transition to newer version libidn2.
The reason is that the libidn2 supports IDNA2008 instead of older IDNA2003. More info is available here:
https://fedoraproject.org/wiki/Changes/IDNA2008

I created a patch for configure.ac, lftp.m4 and misc.cc so that by default the older libidn should be used and optionally user can switch to libidn2. 
[lftp-4.7.7-libidn2.txt](https://github.com/lavv17/lftp/files/1040805/lftp-4.7.7-libidn2.txt)

Could you please take a look at it and let me know if this is acceptable or not? 

Thank you.

Regards,
Michal

**Comment by lavv17** [comment]
They claim "ibidn2 library is API compatible", is it really needed to change the code?

**Comment by lavv17** [comment]
Probably support for older libidn should be dropped. What do you think?

**Comment by mruprich** [comment]
I created the patch in this way so that if someone wanted to use the old version but I agree that we can simply drop it.

**Comment by nmav** [comment]
@lavv17 the API is the same but is present in ```idn2.h``` so few changes are needed. About keeping compatibility I think that unless you are interested in supporting IDN in systems which only ship libidn there is no very little reason to support both (I've only kept libidn2 support in gnutls master).
