### ISSUE TITLE
mirroring fails on folder names prefixed with a space

### ISSUE THREAD

**Issue by fragtion** [lavv17/lftp#352]
Edit: I think this is a server error with Serv-U FTP Server v15.1
---

Hi,

Issue is as per title - lftp mirroring skips folder names prefixed with a space (correct path is given in parentheses... am I missing something? xD)

stdout:
> mirror: Access failed: 550 /Images/Product Images/VMC/SPJ_Spin Jig/PSD/No Shadow: No such file or directory. (/Images/Product Images/VMC/SPJ_Spin Jig/PSD/ No Shadow)
> mirror: Access failed: 550 /Images/Product Images/VMC/SPDSR_Live bait SpinDrift Rig/PSD/Layered Stack: No such file or directory. (/Images/Product Images/VMC/SPDSR_Live bait SpinDrift Rig/PSD/ Layered Stack)
> mirror: Access failed: 550 /Images/Product Images/VMC/SRFLJ_Swinging Rugby FL/PSD/Layered Stack: No such file or directory. (/Images/Product Images/VMC/SRFLJ_Swinging Rugby FL/PSD/ Layered Stack)
> mirror: Access failed: 550 /Images/Product Images/VMC/SSHJ_Stand Up Shaky Head Jig/PSD/Layered PSD Stacks: No such file or directory. (/Images/Product Images/VMC/SSHJ_Stand Up Shaky Head Jig/PSD/ Layered PSD Stacks)

lftp invoked by shell script, as follows:
> lftp -f "
> set ftp:use-stat-for-list no
> set ftp:passive-mode no
> set ftp:ssl-allow no
> set ssl:verify-certificate no
> open $HOST
> user $USER $PASS
> lcd $SOURCEFOLDER
> mirror --ignore-time --no-perms --no-umask --continue --delete --parallel=5 --log=$LOGNAME --verbose --use-cache $SOURCEFOLDER $TARGETFOLDER
> bye
> "

Version:
LFTP | Version 4.7.4 | Copyright (c) 1996-2016 Alexander V. Lukyanov
(Using binary package from Ubuntu zesty/17.04)

**Comment by lavv17** [comment]
Are those directory names really prefixed with a space? Maybe it's a stange listing format.

**Comment by lavv17** [comment]
Please send a complete debug log.
