### ISSUE TITLE
Command not recognized error

### ISSUE THREAD

**Issue by Vrihub** [lavv17/lftp#367]
I'm trying to access the swiftp server (https://github.com/ppareit/swiftp/) running on my android device using lftp. I can log in successfully, and CWD to the desired dir, but then...

---> CWD (remote dir)
<--- 250 CWD successful
---> PROT P
<--- 250 CWD successful
---> EPSV
<--- 502 Command not recognized
---> LIST
---> ABOR
---- Closing aborted data socket

sometimes I get instead:

...
---> PROT P
<--- 250 CWD successful
---> PORT 192,168,1,1,143,231
<--- 502 Command not recognized
...

I also tried `set ftp:passive-mode off` but it's the same.

I can successfully access the server using other ftp clients (the `ftp` command line client, or midnight-commander's integrated ftp client).

**Comment by lavv17** [comment]
Try "set prefer-epsv no". Probably the server mistakenly advertise EPSV
support.

пт, 28 июля 2017, 19:16 Vrihub <notifications@github.com>:

**Comment by Vrihub** [comment]
Uhm it seems to work, thank you!

I had noticed `ftp:prefer-epsv` in the man page, but I didn't try it because the man page says:
"Default is 'false'".

Maybe the man page should be fixed? (or am I missing something?)

**Comment by lavv17** [comment]
Yes, the man page is outdated. Will fix.

сб, 29 июля 2017, 0:54 Vrihub <notifications@github.com>:

**Comment by lavv17** [comment]
Probably this setting should be changed back to be false by default. I've had a few issues with EPSV. What do you think?

**Comment by Vrihub** [comment]
Sorry, I really don't know, you are certainly more experienced than me. I can only confirm that setting it to false fixed the problem I reported in this ticket.

**Comment by lavv17** [comment]
364333bf43b74e335701664ecd8d082e08116a14 should resolve the problem.
