### ISSUE TITLE
Disable special meaning of & character?

### ISSUE THREAD

**Issue by Vrihub** [lavv17/lftp#368]
If I try to transfer some files that have the "&" character in the name, using a script (`lftp -f file`), `lftp` interprets the "&" character and goes into background (breaking the rest of the script).

Is it possible to disable the special meaning of "&"? Or at least in non-interactive settings, e.g. scripts?

**Comment by lavv17** [comment]
A backslash cancels the special meaning of & and other characters.

вс, 30 июля 2017, 0:17 Vrihub <notifications@github.com>:

**Comment by Vrihub** [comment]
Thanks, I knew that. I meant it as a feature request :)

**Comment by lavv17** [comment]
I don't think such an option is needed at all. Consider other special characters which can appear in the file names.
