### ISSUE TITLE
Debian#870416: Fails on SwiFTP server: EPSV command not recognized

### ISSUE THREAD

**Issue by noelk** [lavv17/lftp#370]
Hello,

a forwarded bug from a Debian user:

--8<--
I have a problem contacting the FTP server on my android device. It's
the free FTP Demo Server app from FDroid (or see
https://f-droid.org/packages/be.ppareit.swiftp_free/ ).

With Firefox it works like usual. With mc it works just fine.
With lftp, it's not the case, seems to do weird things on login and than
hangs in a retry loop with increasing timeout.  I made a tcp dump, see
below for text stream.

220 SwiFTP 2.15.0 ready
FEAT
530 Login first with USER and PASS, or QUIT
AUTH TLS
502 Command not recognized
USER ftp
331 Send password
PASS ***********
230 Access granted
FEAT
211-Features supported by FTP Server
 UTF8
 MDTM
 MFMT
 MLST Type*;Size*;Modify*;Perm
211 End
PWD
257 "/"
OPTS UTF8 ON
200 OPTS accepted
OPTS MLST Type;Size;Modify;Perm
200 MLST OPTS Type;Size;Modify;Perm;
PROT P
200 OPTS accepted
EPSV
502 Command not recognized
....502 Command not recognized

Regards,
Eduard.
--8<--
https://bugs.debian.org/870416

thx.

**Comment by lavv17** [comment]
Should be fixed by "set prefer-epsv no" or upcoming 4.8.1
