### ISSUE TITLE
Doesn't use user name specified in ~/.netrc

### ISSUE THREAD

**Issue by noelk** [lavv17/lftp#372]
Hello,

I have specified login and password in ~/.netrc as follows:

machine localhost
login nk
password mypassword

I then connect using:

> lftp ftp://localhost

I get a 530 Login or password incorrect!

If I use:

> lftp ftp://nk@localhost

it works. Without the username an anonymous login is tried but the user and password could be used from .netrc:

$ lftp -d ftp://localhost
---- Löse Hostadresse auf...
---- 2  Adressen gefunden: ::1, 127.0.0.1
lftp localhost:~> ls
---- Verbinde mit localhost (::1) Port 21
<--- 220 ProFTPD 1.3.5d Server (Debian) [::1]
---> FEAT
<--- 211-Features:
<---  SITE UTIME
<---  MDTM
<---  SITE RMDIR
<---  TVFS
<---  SITE COPY
<---  MFMT
<---  SIZE
<---  LANG de-DE.UTF-8*
<---  SITE MKDIR
<---  MFF modify;UNIX.group;UNIX.mode;
<---  REST STREAM
<---  MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.mode*;UNIX.owner*;
<---  UTF8
<---  EPRT
<---  SITE SYMLINK
<---  EPSV
<--- 211 End
---> LANG
<--- 200 Using default language de_DE.UTF-8
---> OPTS UTF8 ON
<--- 200 UTF8 set to on
---> OPTS MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner
<--- 200 OPTS MLST modify;perm;size;type;UNIX.group;UNIX.mode;
---> USER anonymous
<--- 331 Password required for anonymous
---> PASS lftp@
<--- 530 Login incorrect.
---- Server Antwort entspricht ftp:retry-530-anonymous, neuer Versuch
---> PWD
<--- 530 Please login with USER and PASS
---> QUIT
<--- 221 Goodbye.
---- Schließe den Kontroll - Socket
---- Verbinde mit localhost (127.0.0.1) Port 21
<--- 220 ProFTPD 1.3.5d Server (Debian) [::ffff:127.0.0.1]
---> FEAT
<--- 211-Features:
<---  SITE UTIME
<---  MDTM
<---  SITE RMDIR
<---  TVFS
<---  SITE COPY
<---  MFMT
<---  SIZE
<---  LANG de-DE.UTF-8*
<---  SITE MKDIR
<---  MFF modify;UNIX.group;UNIX.mode;
<---  REST STREAM
<---  MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.mode*;UNIX.owner*;
<---  UTF8
<---  EPRT
<---  SITE SYMLINK
<---  EPSV
<--- 211 End
---> LANG
<--- 200 Using default language de_DE.UTF-8
---> OPTS UTF8 ON
<--- 200 UTF8 set to on
---> OPTS MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner
<--- 200 OPTS MLST modify;perm;size;type;UNIX.group;UNIX.mode;
---> USER anonymous
<--- 331 Password required for anonymous
---> PASS lftp@
<--- 530 Login incorrect.
---- Server Antwort entspricht ftp:retry-530-anonymous, neuer Versuch
---> PWD
<--- 530 Please login with USER and PASS
---> QUIT
<--- 221 Goodbye.
---- Schließe den Kontroll - Socket
Abbruch                                                
lftp localhost:~> exit

**Comment by sdellenb** [comment]
@noelk It works if you leave out the `ftp://` part in the address, e.g.  `lftp <hostname>` instead of `lftp ftp://<hostname>`.
See also #292

**Comment by HenrikBengtsson** [comment]
My FTP server supports FTP and FTPS.  I have the credentials set up in `~/.netrc` and can successfully access the server. I can access it over FTP using all of the following approaches:
```sh
$ lftp --username=name@email.org ftp://ftp.server.org 
$ lftp --username=name@email.org ftp.server.org
$ lftp ftp.server.org # username picked up from ~/.netrc
```
Over FTPS the following works:
```sh
$ lftp --username=name@email.org ftps://ftp.server.org 
```

Q: Is it possible to specify that the FTPS protocol should be used with the `ftps://` prefix such that the username can also be picked up from `~/.netrc`? 

In a hope that the 990 port could trigger FTPS, I tried
```sh
$ lftp ftp.server.org:990
$ lftp -p 990 ftp.server.org
```
but that (obviously) didn't do it.


**Major disclaimer**:  
I'm on a very old LFTP client and updating is out of my control:
```sh
$ lftp --version | head -1
LFTP | Version 4.0.9 | Copyright (c) 1996-2010 Alexander V. Lukyanov
```
Though, comparing the `lftp --help` options in the above version;
```r
lftp --help
Usage: lftp [OPTS] <site>
`lftp' is the first command executed by lftp after rc files
 -f <file>           execute commands from the file and exit
 -c <cmd>            execute the commands and exit
 --help              print this help and exit
 --version           print lftp version and exit
Other options are the same as in `open' command
 -e <cmd>            execute the command just after selecting
 -u <user>[,<pass>]  use the user/password for authentication
 -p <port>           use the port for connection
 <site>              host name, URL or bookmark name
```
with lftp 4.6.3a on an up-to-date Ubuntu 16.04 does suggest that there are any new options for specifying the protocol.

**Comment by lavv17** [comment]
A default user name from .netrc is only used when URL scheme is not
present. So you can force using the default user name with a non-ftp
protocol by "set cmd:default-protocol ftps". For example:
   lftp -e "set cmd:default-protocol ftps; open ftp.server.org"

вт, 6 февр. 2018 г. в 21:47, Henrik Bengtsson <notifications@github.com>:

**Comment by HenrikBengtsson** [comment]
Thanks for clarifying / confirming and thanks for a great tool.

Personally, I'm happy with the `-e` solution, but may I add to the wishlist to control the protocol via a option?  For example,
```r
lftp --protocol=ftps ftp.server.org
```
Not sure if such an option would fit in the bigger picture with all the other protocols that lftp support.
