### ISSUE TITLE
Document exit codes

### ISSUE THREAD

**Issue by tomsommer** [lavv17/lftp#374]
There is no documentation on possible exit codes or exit values.

Additionally it is impractical that exit codes are an error count, because there is no programmatic way to determine what actually failed (530 vs 550 etc.).

**Comment by lavv17** [comment]
I don't remember using error count as an exit code. Please report exact command which returns such an exit code.

**Comment by lavv17** [comment]
In fact there are just two exit codes lftp should return: 0 and 1, where 1 stands for an error indicator.

**Comment by tomsommer** [comment]
MirrorJob returns the error count as exit code.

**Comment by lavv17** [comment]
No, it isn't the case:
`int   ExitCode() { return stats.error_count!=0; }`

**Comment by lavv17** [comment]
To be exact, it was changed in 2011: febc5ec64f4aed469c3081d08f3947f320a53abf

**Comment by tomsommer** [comment]
Fair enough, old versions are still in the distros :)
