### ISSUE TITLE
Failed to make on Ubuntu 16.04

### ISSUE THREAD

**Issue by scriptzteam** [lavv17/lftp#376]
```
make[2]: Entering directory '/home/lftp/lftp/po'
*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.19 but the autoconf macros are from gettext version 0.18
```

```
gettextize --version 2>&1 | sed -n 's/^.*GNU gettext.* \([0-9]*\.[0-9.]*\).*$/\1/p'
0.19.7
```

**Comment by nomad64** [comment]
I was running into this same issue on my Ubuntu 16.04 box. After some creative searching, I found a workaround.

Change the following line in po/Makefile.in.in
`GETTEXT_MACRO_VERSION = 0.19`
to:
`GETTEXT_MACRO_VERSION = 0.18`

After which, you can `make` as usual. I am not sure if this impacts the functionality of lftp, but I am able to connect to a test SFTP site and mirror files successfully.
