### ISSUE TITLE
4.8.0 crashes during upload of some files

### ISSUE THREAD

**Issue by gohdan** [lavv17/lftp#387]
Fedora 26, lftp from repository, version 4.8.0-1
Crashes during upload of some PHP scripts with the following error:

lftp: FileCopy.cc:876: virtual int FileCopyPeerFA::Do(): Assertion `!session->IsOpen()' failed.                                 
Aborted (стек памяти сброшен на диск)

Falls on the same files constantly. Doesn't depend on hosting. Some files it uploads every time, some files - never. 4.7.8 works fine on that files.

Example of PHP file you could see at https://pastebin.com/4JD7ER25

**Comment by lavv17** [comment]
Please send me the debug output and the script which shows this fault.
