### ISSUE TITLE
lftp-4.8.3/src/Http.cc: 2 * redundant condition ?

### ISSUE THREAD

**Issue by dcb314** [lavv17/lftp#402]
[lftp-4.8.3/src/Http.cc:1740]: (style) Redundant condition: If 'EXPR == ' '', the comparison 'EXPR' is always true.

Source code is

        while(*colon && *colon==' ')

[lftp-4.8.3/src/Http.cc:2450]: (style) Redundant condition: If 'EXPR == ' '', the comparison 'EXPR' is always true.

Duplicate.

**Comment by lavv17** [comment]
It's redundant, but still looks correct.

вт, 10 окт. 2017, 13:37 dcb314 <notifications@github.com>:
