### ISSUE TITLE
lftp exits with error code 0 on 530 error

### ISSUE THREAD

**Issue by mikebridge** [lavv17/lftp#403]
When I have a 530 "login failed" error in the following lftp 4.6.3a script, it exits with code 0 rather than 1.  

```
set ftps:initial-prot ""
set ftp:ssl-force true
set ftp:ssl-protect-data true
set net:reconnect-interval-base 0
open ftp.example.com
user myuser\mypassword
mirror --reverse --delete --verbose ./foo/ /bar
```

```bash
$ lftp -f lftp-api.sync
mirror: Login failed: 530 User cannot log in.
$ echo $?
0
$ lftp -v
LFTP | Version 4.6.3a | Copyright (c) 1996-2014 Alexander V. Lukyanov
```

**Comment by lavv17** [comment]
Is it the same in lftp 4.8.3?

ср, 11 окт. 2017, 4:44 Mike Bridge <notifications@github.com>:

**Comment by mikebridge** [comment]
@lavv17 I upgraded to 4.8.3 and it still does not generate a non-zero exit code:

```bash
$ lftp -f lftp-api.sync
mirror: Login failed: 530 User cannot log in.                                  
$ echo $?
0
$ lftp -v
LFTP | Version 4.8.3 | Copyright (c) 1996-2017 Alexander V. Lukyanov

[legal notice deleted]

Libraries used: Expat 2.1.0, GnuTLS 3.4.10, Readline 6.3, zlib 1.2.8
```

**Comment by lavv17** [comment]
I cannot reproduce the problem:

> lftp -c 'mir ftp://xxx:yyy@backup/ /tmp/x'; echo $?
> mirror: Login failed: 530 Login incorrect.
> 1

And with the command in the file **/tmp/s**:

> lftp -f /tmp/s; echo $?
> mirror: Login failed: 530 Login incorrect.
> 1

**Comment by lavv17** [comment]
Do you have any command after **mirror**? The exit code of the last command is returned. You can try "set fail-exit true".

**Comment by mikebridge** [comment]
Sorry, this is indeed my error---it is continuing on to another command in my script.  Setting `fail-exit` to true fixes this.
