### ISSUE TITLE
Mirroring: How to properly escape destination FTP address/password to handle weird chars?

### ISSUE THREAD

**Issue by dustinbolton** [lavv17/lftp#440]
When calling the mirror command specifying the destination FTP address some characters seem to cause problems. What is the appropriate way to escape the following destination FTP address?

```
'ftp://temp_user:S2P/z92?[V:K6oXO_y/NIPPs]PpGgy.r@host.com:21/path/'
```

In this example the slashes break lftp's parsing of configuration. Escaping with backslashes does not seem to work either.

Suggestions?

**Comment by jsharris1229** [comment]
%2F for /
see https://www.w3schools.com/tags/ref_urlencode.asp
