### ISSUE TITLE
Incorrectly removes files when --flat switch is on

### ISSUE THREAD

**Issue by borkabu** [lavv17/lftp#448]
Reproducible command line 
lftp -e 'mirror -vvv --delete --flat -I "*.gtf.gz" /pub/current/metazoa/gtf/ /localfolder; bye' -u anonymous:anonymous ftp://ftp.ensemblgenomes.org

Have tried it on RedHat and Windows (Cygwin). 

Observed behaviour
First run downloads 154 files, ~500MB
Second run deletes 125 files
Third run downloads 125 files

While expected behaviour should be 
First run downloads 154 files, ~500MB
Subsequent runs do nothing

I will try to debug it...

Best regards
Boris

**Comment by lavv17** [comment]
"files" should always be sorted by name. If not, it's already a bug.
