### ISSUE TITLE
The lftp client cannot use cd on sub-directories without having top-level permissions

### ISSUE THREAD

**Issue by mruprich** [lavv17/lftp#453]
When connecting to a FTP server(windows FTP server in this case), lftp client is denied access to a directory if the user has no permission to access parent directory. This is doable with ftp client because it uses the whole path on the FTP server to access the subdirectory. lftp, on the other hand, cuts the path to pieces and then uses a series of CWD commands to get to the desired directory. That results in access denied error. 

Would you consider changing the behaviour of lftp so that this would be possible as with ftp?

**Comment by mruprich** [comment]
I am not sure if this is the right way but this worked for me: 

diff --git a/src/ftpclass.cc.old b/src/ftpclass.cc
index 170992b..2c432cc 100644
--- a/src/ftpclass.cc.old
+++ b/src/ftpclass.cc
@@ -709,10 +709,10 @@ int Ftp::SendCWD(const char *path,const char *path_url,Expect::expect_t c)
 	 }
 	 strcpy(path2+path2_len,dir);
 	 path2_len+=strlen(dir);
-	 conn->SendCmd2("CWD",dir);
-	 expect->Push(new Expect(Expect::CWD_CURR,path2));
-	 cwd_count++;
       }
+	 cwd_count++;
+	 conn->SendCmd2("CWD",path2);
+	 expect->Push(new Expect(Expect::CWD_CURR,path2));
    }
    Expect *last_cwd=expect->FindLastCWD();
    if(last_cwd)

**Comment by mruprich** [comment]
Hi,
did anyone had some time to look at this?

**Comment by mruprich** [comment]
Hi, any update on this issue?

**Comment by lavv17** [comment]
Does the server report TVFS in the FEAT reply?

**Comment by lavv17** [comment]
If not, try "set ftp:use-tvfs yes"

**Comment by mruprich** [comment]
Thanks, this helped with the issue. I wonder if it wouldn't make sense to change the lftp behaviour to use 'set ftp:use-tvfs auto' by default?

**Comment by lavv17** [comment]
"auto" is the default

**Comment by lavv17** [comment]
Some RFC recommend to send each component of the path separately unless the server has the TVFS feature
