### ISSUE TITLE
Link for readline lib is broken in LFTP site

### ISSUE THREAD

**Issue by paulo-guedes** [lavv17/lftp#455]
Hello, I was reading the LFTP site (https://lftp.yar.ru/) and just noticed that the link for readline lib is broken. 

Currently it points to http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html.
Perhaps it should point to the following site (not sure, please check): 
https://tiswww.case.edu/php/chet/readline/rltop.html

By the way, I got here because lftp is mentioned in the kernel.org site.
Section: "What happened to ftp.kernel.org?". That's pretty cool, isn't it?
https://www.kernel.org/category/faq.html

Thanks,
Paulo

**Comment by lavv17** [comment]
fixed. Thanks!
