### ISSUE TITLE
How to get output when run inside cron

### ISSUE THREAD

**Issue by Corrodian** [lavv17/lftp#470]
I have a cron script that runs lftp and checks if the output contains "X bytes transferred" message. When run from a terminal the scripts works fine. When run as a cron task, the output is empty even though the file is transferred.

How can I get output when running lftp from cron?

My command:
`lftp -u USER,PASS sftp://USER@IP:PORT -e "cd FOLDER; mput -E FILE; quit;"`

**Comment by lavv17** [comment]
set cmd:interactive yes
