### ISSUE TITLE
problem with --with-readline=PATH

### ISSUE THREAD

**Issue by devgeist42** [lavv17/lftp#483]
The following lines which sets and uses `readline_include_dir`

https://github.com/lavv17/lftp/blob/83aeb656f594ee3653377d41292aa8b7fbe9e919/m4/lftp_lib_readline.m4#L108
https://github.com/lavv17/lftp/blob/83aeb656f594ee3653377d41292aa8b7fbe9e919/m4/lftp_lib_readline.m4#L116
https://github.com/lavv17/lftp/blob/83aeb656f594ee3653377d41292aa8b7fbe9e919/m4/lftp_lib_readline.m4#L148
https://github.com/lavv17/lftp/blob/83aeb656f594ee3653377d41292aa8b7fbe9e919/m4/lftp_lib_readline.m4#L176

is inconsistent with the following lines in `readline.h` at http://git.savannah.gnu.org/cgit/readline.git/tree/readline.h#n29
```
#if defined (READLINE_LIBRARY)
#  include "rlstdc.h"
#  include "rltypedefs.h"
#  include "keymaps.h"
#  include "tilde.h"
#else
#  include <readline/rlstdc.h>
#  include <readline/rltypedefs.h>
#  include <readline/keymaps.h>
#  include <readline/tilde.h>
#endif
```

Because of this, build fails with a custom `--with-readline=...`

**Comment by lavv17** [comment]
Please test.
