### ISSUE TITLE
Lftp --newer-than=now-3days issue

### ISSUE THREAD

**Issue by mycloudcms** [lavv17/lftp#493]
Hi, after running lftp mirror with --newer-than=now-3days flag, I spotted that it takes files from remote server, today, yesterday and three days ago but only up to a certain time for 3rd day. So the 3rd day it doesn't take files based on 24hours, for example running the lftp @ 16:00 will not take files from 3rd day @ 03:04.

**Comment by lavv17** [comment]
I think it is a correct behavior.

**Comment by mycloudcms** [comment]
how's that? Can you please describe the thinking behind this issue? If it takes 3 days back, it should take all files within 3rd day

**Comment by mycloudcms** [comment]
Thank you for your reply, can you please inform me how I can get files with --newer-than=5-days and capture the 5 calendar days?

**Comment by lavv17** [comment]
you can use 00:00-5days
