### ISSUE TITLE
lftp on SuSe SLES11 fails to establish TLS 1.2 connection to z/OS

### ISSUE THREAD

**Issue by LTepliakov** [lavv17/lftp#502]
Hi again Alexander,
one more question (problem?)
When I try to establish  TLS 1.2 connection to z/OS host I get an error:

lftp> ~/local/bin/lftp -u us15030,******** ftp://bldbmsa.boulder.ibm.com
lftp us15030@bldbmsa.boulder.ibm.com:~> set ftp:ssl-allow true
lftp us15030@bldbmsa.boulder.ibm.com:~> set ftp:ssl-force true
lftp us15030@bldbmsa.boulder.ibm.com:~> set ftp:ssl-protect-data true
lftp us15030@bldbmsa.boulder.ibm.com:~> set ftp:ssl-protect-list true
lftp us15030@bldbmsa.boulder.ibm.com:~> set ssl:priority NORMAL:+VERS-TLS1.2
lftp us15030@bldbmsa.boulder.ibm.com:~> set ssl:ca-file "/etc/ssl/private/vsftpd.pem"
lftp us15030@bldbmsa.boulder.ibm.com:~> ls
**ls: Fatal error: gnutls_handshake: A TLS fatal alert has been received.**
lftp us15030@bldbmsa.boulder.ibm.com:~> quit

Bit with TLS 1.1 it works fine:

~/local/bin/lftp -u us15030,******** ftp://bldbmsa.boulder.ibm.com
lftp us15030@bldbmsa.boulder.ibm.com:~> set ftp:ssl-allow true
lftp us15030@bldbmsa.boulder.ibm.com:~> set ftp:ssl-force true
lftp us15030@bldbmsa.boulder.ibm.com:~> set ftp:ssl-protect-data true
lftp us15030@bldbmsa.boulder.ibm.com:~> set ftp:ssl-protect-list true
lftp us15030@bldbmsa.boulder.ibm.com:~> set ssl:priority NORMAL:+VERS-TLS1.1
lftp us15030@bldbmsa.boulder.ibm.com:~> set ssl:ca-file "/etc/ssl/private/vsftpd.pem"
lftp us15030@bldbmsa.boulder.ibm.com:~> ls
Volume Unit    Referred Ext Used Recfm Lrecl BlkSz Dsorg Dsname
Migrated                                                BMSB.SPFTEMP0.CNTL
Migrated                                                BMSB.SPFTEMP1.CNTL
PRR3Q4 3390   2019/01/17  1    1  FB      80  8000  PO  CISF.JCL
PRR3P4 3390   2019/01/17  1    2  FB      80  8000  PO  CISF.PROC
PRR612 3390   2019/01/22  122500  VB    1000 10000  PS  CISF.TEST.CSV
PRR3S0 3390   2019/01/22  1    2  FB      80  8000  PO  CISF.UTIL
Migrated                                                CSSLIB

From the other side curl works fine with TLS 1.2 to same z/OS target:
curl --ftp-ssl --tlsv1.2 --cacert /etc/ssl/private/vsftpd.pem --use-ascii -v -T unzip1.jcl 
[SamplCurlbacc.log](https://github.com/lavv17/lftp/files/2804226/SamplCurlbacc.log)
That makes me think that problem is not on server side.

I tried both lftp 4.3.7 installed on the server in /usr/bin/lftp
and lftp 4.8.4 I have compiled from the source into my local folder.

I am on SuSE :

cat /etc/os-release
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"

uname -a
Linux zdsdeveng03 3.0.101-108.84-default #1 SMP Fri Nov 30 15:57:27 UTC 2018 (7a72692) s390x s390x s390x GNU/Linux

The problem is quite important for us, we need to switch to secure file transfer.
With curl I do not see the way how to program a sequence of ftp commands within one session.
Use of sftp instead requires a change on z/OS side to configure secure shell.
Security administrators on SuSE side refuse to install lftp on production blaming that it does not support TLS 1.2 and TLS 1.1 to have vulnerabilities.

Appreciate your help!

**Comment by lavv17** [comment]
You can try to use a newer gnutls or compile LFTP with openssl.

пн, 28 янв. 2019, 21:12 LTepliakov notifications@github.com:

**Comment by LTepliakov** [comment]
Trying to build lftp from source with latest gnutls library, but get error on link stage.

I do not have root access on the host, so I have built gnutls-3.6.6 in my home folder ~/local/lib:
local/lftp-4.8.4> ls -l ../lib
total 42460
-rw-r----- 1 leonidt leonidt      58 Jan 28 19:24 find.txt
-rw-r--r-- 1 leonidt leonidt 1448804 Jan 30 10:26 libgmp.a
-rwxr-xr-x 1 leonidt leonidt     937 Jan 30 10:26 libgmp.la
lrwxrwxrwx 1 leonidt leonidt      16 Jan 30 10:26 libgmp.so -> libgmp.so.10.3.2
lrwxrwxrwx 1 leonidt leonidt      16 Jan 30 10:26 libgmp.so.10 -> libgmp.so.10.3.2
-rwxr-xr-x 1 leonidt leonidt  627160 Jan 30 10:26 libgmp.so.10.3.2
-rwxr-xr-x 1 leonidt leonidt    1071 Feb  1 21:54 libgnutls.la
lrwxrwxrwx 1 leonidt leonidt      20 Feb  1 21:54 libgnutls.so -> libgnutls.so.30.23.1
lrwxrwxrwx 1 leonidt leonidt      20 Feb  1 21:54 libgnutls.so.30 -> libgnutls.so.30.23.1
-rwxr-xr-x 1 leonidt leonidt 7370912 Feb  1 21:54 libgnutls.so.30.23.1
-rw-r--r-- 1 leonidt leonidt 6504792 Feb  1 10:22 libhogweed.a
lrwxrwxrwx 1 leonidt leonidt      17 Feb  1 10:22 libhogweed.so -> libhogweed.so.4.5
lrwxrwxrwx 1 leonidt leonidt      17 Feb  1 10:22 libhogweed.so.4 -> libhogweed.so.4.5
-rw-r--r-- 1 leonidt leonidt 5483600 Jan 31 15:13 libhogweed.so.4.4
-rw-r--r-- 1 leonidt leonidt 5659264 Feb  1 10:22 libhogweed.so.4.5
-rw-r--r-- 1 leonidt leonidt  734126 Feb  2 09:59 liblftp-jobs.a
-rwxr-xr-x 1 leonidt leonidt    1655 Feb  2 09:58 liblftp-jobs.la
-rw-r--r-- 1 leonidt leonidt 2112786 Feb  2 09:59 liblftp-tasks.a
-rwxr-xr-x 1 leonidt leonidt    1410 Feb  2 09:58 liblftp-tasks.la
-rw-r--r-- 1 leonidt leonidt 5149482 Feb  1 10:21 libnettle.a
lrwxrwxrwx 1 leonidt leonidt      16 Feb  1 10:22 libnettle.so -> libnettle.so.6.5
lrwxrwxrwx 1 leonidt leonidt      16 Feb  1 10:22 libnettle.so.6 -> libnettle.so.6.5
-rw-r--r-- 1 leonidt leonidt 4171416 Jan 31 15:13 libnettle.so.6.4
-rw-r--r-- 1 leonidt leonidt 4195336 Feb  1 10:22 libnettle.so.6.5
drwxr-s--x 2 leonidt leonidt     512 Feb  1 21:54 pkgconfig

I ran configure with following options to specify location of new gnutls library:

./configure --prefix=/gsa/pokgsa/home/l/e/leonidt/local --with-libpth-prefix=/gsa/pokgsa/home/l/e/leonidt/local/ LIBGNUTLS_LIBS=-L/gsa/pokgsa/home/l/e/leonidt/local/lib/ LIBGNUTLS_CFLAGS=-I/gsa/pokgsa/home/l/e/leonidt/local/include

but 
make V=1 
fails with error on link stage:
make[2]: Entering directory `/gsa/pokgsa-h3/19/leonidt/local/lftp-4.8.4/src'
/bin/sh ../libtool --silent  --tag=CXX   --mode=link g++  -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -export-dynamic -s -o lftp lftp-lftp.o lftp-complete.o lftp-lftp_rl.o lftp-attach.o liblftp-jobs.la liblftp-tasks.la -L/usr/lib -lreadline -lutil -lncurses -ldl 
/usr/lib64/gcc/s390x-suse-linux/4.3/../../../../s390x-suse-linux/bin/ld: skipping incompatible /usr/lib/librt.so when searching for -lrt
/usr/lib64/gcc/s390x-suse-linux/4.3/../../../../s390x-suse-linux/bin/ld: skipping incompatible /usr/lib/librt.a when searching for -lrt
/usr/lib64/gcc/s390x-suse-linux/4.3/../../../../s390x-suse-linux/bin/ld: skipping incompatible /usr/lib/libutil.so when searching for -lutil
/usr/lib64/gcc/s390x-suse-linux/4.3/../../../../s390x-suse-linux/bin/ld: skipping incompatible /usr/lib/libutil.a when searching for -lutil
/usr/lib64/gcc/s390x-suse-linux/4.3/../../../../s390x-suse-linux/bin/ld: skipping incompatible /usr/lib/libdl.so when searching for -ldl
/usr/lib64/gcc/s390x-suse-linux/4.3/../../../../s390x-suse-linux/bin/ld: skipping incompatible /usr/lib/libdl.a when searching for -ldl
/usr/lib64/gcc/s390x-suse-linux/4.3/../../../../s390x-suse-linux/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/usr/lib64/gcc/s390x-suse-linux/4.3/../../../../s390x-suse-linux/bin/ld: skipping incompatible /usr/lib/libm.a when searching for -lm
/usr/lib64/gcc/s390x-suse-linux/4.3/../../../../s390x-suse-linux/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
/usr/lib64/gcc/s390x-suse-linux/4.3/../../../../s390x-suse-linux/bin/ld: skipping incompatible /usr/lib/libc.a when searching for -lc
/gsa/pokgsa/home/l/e/leonidt/local/lftp-4.8.4/src/.libs/liblftp-network.a(liblftp_network_la-lftp_ssl.o): In function `lftp_ssl_gnutls::get_fp(gnutls_x509_crt_int*)':
lftp_ssl.cc:(.text+0xd6): undefined reference to `gnutls_x509_crt_get_fingerprint'
/gsa/pokgsa/home/l/e/leonidt/local/lftp-4.8.4/src/.libs/liblftp-network.a(liblftp_network_la-lftp_ssl.o): In function `lftp_ssl_gnutls::copy_sid(lftp_ssl_gnutls const*)':

So looks like Make does not place the path to gnutls library to linker command line.
Can you please advice how to configure it correctly?

Appreciate your help!

**Comment by LTepliakov** [comment]
Attached Makefile for reference. (Had to add txt extension for gitub to accept it).

[Makefile.txt](https://github.com/lavv17/lftp/files/2824517/Makefile.txt)

**Comment by LTepliakov** [comment]
I executed the command line that failed under make adding my local library to link path an gnutls library: 
/bin/sh ../libtool --silent  --tag=CXX   --mode=link g++  -O2 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -export-dynamic -s -o lftp lftp-lftp.o lftp-complete.o lftp-lftp_rl.o lftp-attach.o liblftp-jobs.la liblftp-tasks.la -L/usr/lib **-L/gsa/pokgsa/home/l/e/leonidt/local/lib** -lreadline -lutil -lncurses -ldl **-lgnutls**

it built lftp successfully
After than retried to run make and it answered that it has nothing to do more.
make install - installed it without problem to my ~/home/local/bin
and then --hurray!-- this newly built version connected to my host with TLS 1.2 !

I think issue can be closed now.

But still curious, which mistake I did running ./configure script? Why it did not generate correct Makefile for me?

**Comment by lavv17** [comment]
Configure has the flag --with-gnutls=path, try it.

вс, 3 февр. 2019, 23:44 LTepliakov notifications@github.com:

**Comment by LTepliakov** [comment]
Yes, I tried it too before I linked it manually, it did not help, make failed with same error
That was my last configure attempt:
./configure --with-gnutls=yes --prefix=/gsa/pokgsa/home/l/e/leonidt/local --with-libpth-prefix=/gsa/pokgsa/home/l/e/leonidt/local/ LIBGNUTLS_LIBS=-L/gsa/pokgsa/home/l/e/leonidt/local/lib/ LIBGNUTLS_CFLAGS=-I/gsa/pokgsa/home/l/e/leonidt/local/include

**Comment by LTepliakov** [comment]
sorry did not notice that you propose --with-gnutls=path and I tried --with-gnutls=yes
shall try your option

**Comment by LTepliakov** [comment]
Yes it worked fine with 
./configure **--with-gnutls=/gsa/pokgsa/home/l/e/leonidt/loca**l --prefix=/gsa/pokgsa/home/l/e/leonidt/local --with-libpth-prefix=/gsa/pokgsa/home/l/e/leonidt/local/ LIBGNUTLS_LIBS=-L/gsa/pokgsa/home/l/e/leonidt/local/lib/ LIBGNUTLS_CFLAGS=-I/gsa/pokgsa/home/l/e/leonidt/local/include

Thank you so much!
