### ISSUE TITLE
sftp upload to DriveHQ hangs

### ISSUE THREAD

**Issue by reynot** [lavv17/lftp#504]
Hi,

I am trying to use lftp to connect to a sftp server hosted on DriveHQ.
I have successfully transferred files using FTP but I am failing using SFTP.

I can log in, the file transfers successfully and then hangs waiting for a response following the file transfer. I can successfully transfer files using Filezilla and WinSCP.

I am testing on Ubuntu 16.04 LTS and have lftp version 4.6.3.a.

The debug output from lftp is given below.

`lftp -d -u <USER>,<PSWD> sftp://proftp.drivehq.com -e "set sftp:auto-confirm yes; put example_cmds.txt; bye"
---- Running connect program (ssh -a -x -s -l <USER> proftp.drivehq.com sftp)
---> sending a packet, length=5, type=1(INIT), id=0
<--- <USER>@proftp.drivehq.com's password: XXXX
<--- got a packet, length=5, type=2(VERSION), id=0
---- protocol version set to 3
---> sending a packet, length=10, type=16(REALPATH), id=1
<--- got a packet, length=78, type=104(NAME), id=1
---- home set to /
---- path on wire is `/example_cmds.txt'
---> sending a packet, length=34, type=3(OPEN), id=2
<--- got a packet, length=26, type=102(HANDLE), id=2    
---- got file handle 2F6578616D706C655F636D64732E747874 (17)
---> sending a packet, length=942, type=6(WRITE), id=3
---> sending a packet, length=38, type=10(FSETSTAT), id=4
---> sending a packet, length=26, type=4(CLOSE), id=5
<--- got a packet, length=38, type=101(STATUS), id=3        
---- status code=0(OK), message=DriveHQ SFTP Server
<--- got a packet, length=54, type=101(STATUS), id=4        
---- status code=4(Failure), message=SSH_FXP_FSETSTAT is not implemented
`example_cmds.txt' at 904 (100%) eta:0s [Waiting for response...] `

It seems it is trying to set file stats after performing the transfer which is not supported.
I have tried disabling use of the stat command with the following:
set ftp:use-stat false
set ftp:use-stat-for-list false

Any suggestions greatly appreciated.

Thanks 

Tim Reynolds

**Comment by lavv17** [comment]
The server failed to send reply for the close command.

вт, 5 февр. 2019, 20:41 reynot notifications@github.com:

**Comment by reynot** [comment]
Thanks. I am in communication with DriveHQ and hopefully they will fix there end. I will update and close when I get a conclusion.

**Comment by reynot** [comment]
I can confirm DriveHQ fixed there implementation at their end and all now works.
Many thanks for the help
