### ISSUE TITLE
Pipeline filtering and arguments with quotes

### ISSUE THREAD

**Issue by bacher09** [lavv17/lftp#506]
Hi, I'm not exactly sure if this bug or just odd undocumented behavior.
If I try command like this it will not work:

    ls  | egrep '(test|best)'
    sh: -c: line 0: syntax error near unexpected token `test'
    sh: -c: line 0: `echo (test|best)'

It happens because lftp removes single quote from `egrep` arguments. Here's strace log that demonstrates this: 

    execve("/bin/sh", ["sh", "-c", "egrep (test|best)"], 0x560169496d50 /* 80 vars */) = 0 

But if I'll try to execute command via `!` lftp will not remove quotes. Like this:

    ! echo '(test|best)'

I can achieve behavior I wanted too via such commands:

    ls | "egrep '(test|best)'"
    ls | egrep \'(test|best)\'

But it looks odd and isn't documented in any way. Moreover, as I mentioned before, when commands used with `!`  they have different behavior. 

I also debugged lftp a little bit and find that quotes was removed in [CmdExec::parse_one_cmd](https://github.com/lavv17/lftp/blob/master/src/parsecmd.cc#L39) method.

**Comment by lavv17** [comment]
Probably it was an intention to allow multiple commands with pipeline on
the same line.
It can be changed, but for backward compatibility a setting will be
required.

пт, 15 февр. 2019, 19:39 Slava notifications@github.com:

**Comment by bacher09** [comment]
Thanks for quick reply.

Also wanted to ask what you think about making this parser behave more like bash (somewhere in future) and define intended behavior with tests.  
I checked code that handles quotes and found that quotes closed automatically. 
For example this is valid for lftp:

    "ls

While `(` is handled differently. Also, depending on how many opening quotes meaning of closing quote can change, for example `(echo )` will work as empty echo, while `echo )` will work as `echo ")"` in bash (or `echo \)`.
