### ISSUE TITLE
mirror -R with --no-empty-dirs

### ISSUE THREAD

**Issue by forgive38** [lavv17/lftp#518]
Hello

with this command line :
`lftp -e 'set net:timeout 5s;set net:max-retries 1;set net:reconnect-interval-base 1;set net:reconnect-interval-multiplier 1 ;set ftp:ssl-allow no;set xfer:log-file "/tmp/lftp_transfer.log";mirror -R --max-errors=3 --log="/tmp/mirror_commands.log" --exclude=src --parallel=20  -e -n --no-empty-dirs /local/ / ; bye ' -u user,pass site.ftp.org`

i have some errors.
I found that when you use --no-empty-dirs, empty dirs are not created on remote but, there are some chmod commands on these non existent remote directories, so there are errors.
And I don't know why, but all directories are created each time on remote (seen in /tmp/mirror_commands.log ) even they already exist.
Without option --no-empty-dirs, lftp works like a charm

**Comment by lavv17** [comment]
fixed in 3415d42a48d1ad7234af1046e38d05358da16d52
