### ISSUE TITLE
OPTS MLST is incorrectly formatted

### ISSUE THREAD

**Issue by Hanicef** [lavv17/lftp#521]
When `cls` is issued, LFTP doesn't send the `OPTS MLST` command properly. According to RFC-3659, the request format should be like this:
`"OPTS" SP "MLST" [ SP 1*(factname ";") ]`, where `factname` is a fact.

The problem with LFTP is that the last fact is missing a semicolon. This causes some servers to miss out on that specific fact, and therefore not include it. An example of this can be seen on ftp://ietf.org/ in which this happens during the execution of `cls`:
```
---> OPTS MLST modify;perm;size;type;UNIX.group;UNIX.mode;UNIX.owner
<--- 200 OPTS MLST modify;perm;size;type;UNIX.group;UNIX.mode;
```
What happens is that `UNIX.owner` is not seen by the server due to the missing semicolon, and therefore is not included in the output. This is not that bad in this case, but it can cause the server to miss more important tags such as `size` or `type`, which could cause unexpected behavior in LFTP.

**Comment by lavv17** [comment]
fixed in d76207c757dd34ccd7db3876c67f7b467f85504a
