### ISSUE TITLE
Publishing a new release

### ISSUE THREAD

**Issue by dns2utf8** [lavv17/lftp#524]
Hi

It would be very cool to have a new release in debian testing so then it would make it into buster.
Currently the freeze has already happend but maybe a small release would make it into debian-updates?

Cheers

**Comment by dns2utf8** [comment]
Hi all

Since 4.8.4 was released in 2018 I am wondering if it was possible to do a release in 2019?
I could also help with some parts of the procress. Do you have any open tasks @lavv17 ?

Cheers,
Stefan

**Comment by lavv17** [comment]
I think I'll make a release this year.

**Comment by dns2utf8** [comment]
Thank you :smiley: I am looking forward to it

**Comment by ekilah** [comment]
I am new and have no idea how debian's package updates system works, but I happen to be using `lftp` on a debian box. I came here looking if it would be possible to get 4.8.0+ on debian, `apt-get` only sees `4.7.1-1`. Any advice would be appreciated!

**Comment by dns2utf8** [comment]
Debian unstable (sid) and testing (bullseye) and stable (buster) have 4.8.4: https://packages.debian.org/buster/lftp
Can you upgrade you system from oldstable (stretch) to stable?

**Comment by ekilah** [comment]
Thanks, I am using `Turnkey Linux` which I had to wait for `buster` support on. Once they supported `buster` and I installed a new container with it, I was able to grab `4.8.4`.
