### ISSUE TITLE
Multiplex multiple file transfers in one connection

### ISSUE THREAD

**Issue by bijoythomas** [lavv17/lftp#528]
Hello, this is more of a question...

Does the parallel transfer option for `mput` use a separate connection for each file it is transferring? Or is it using a single connection and multiplexing the files over separate channels?

If it is using a separate connection per file, is there a way to force it to use a single connection?

**Comment by lavv17** [comment]
It uses multiple connections. There is no such thing as a channel inside a
connection.

чт, 6 июня 2019, 1:55 Bijoy Thomas <notifications@github.com>:

**Comment by lavv17** [comment]
It could multiplex over sftp but it's unsupported by lftp. Also it won't give any transfer rate benefits over sequential transfer.
http/2 also supports multiplexing, but this protocol is not implemented in lftp.
