### ISSUE TITLE
getting access denied error when trying to do pget on Mac Mojave - debug doesn't show any details 

### ISSUE THREAD

**Issue by L07tB0y** [lavv17/lftp#531]
Installed lftp though home brew and running lftp version 4.8.4_1. I enabled debug logging and it does not show any thing other than the error below. 

---- path on wire is `/media/sde1/home/data/test/'
---> sending a packet, length=72, type=3(OPEN), id=9
<--- got a packet, length=13, type=102(HANDLE), id=9
---- got file handle 00000000 (4)
---> sending a packet, length=13, type=8(FSTAT), id=10
<--- got a packet, length=37, type=105(ATTRS), id=10
---- file info: size=4096, date=Sun Jul  7 13:14:02 2019
---> sending a packet, length=25, type=5(READ), id=11
---> sending a packet, length=25, type=5(READ), id=12
<--- got a packet, length=24, type=101(STATUS), id=11
---- status code=4(Failure), message=Failure
---> sending a packet, length=13, type=4(CLOSE), id=13
pget: Access failed: Failure (test/)
<--- got a packet, length=24, type=101(STATUS), id=12
---- status code=4(Failure), message=Failure
<--- got a packet, length=24, type=101(STATUS), id=13
---- status code=0(OK), message=Success

**Comment by lavv17** [comment]
It looks like you are trying to retrieve a directory.

вс, 7 июля 2019, 21:44 L07tB0y <notifications@github.com>:
