### ISSUE TITLE
Compilation issue: "gettext infrastructure mismatch"

### ISSUE THREAD

**Issue by I4HJrl0** [lavv17/lftp#544]
LFTP version: latest master (6f0b3d8).
OS: Ubuntu 18.04.

This is a copy of #376.

I'm running `./autogen.sh && make` and I'm getting the following _make_ error:
> Making all in po
make[2]: Entering directory 'lftp/po'
*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.19 but the autoconf macros are from gettext version 0.18
Makefile:260: recipe for target 'stamp-po' failed
make[2]: *** [stamp-po] Error 1
make[2]: Leaving directory 'lftp/po'
Makefile:1613: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory 'lftp'
Makefile:1558: recipe for target 'all' failed
make: *** [all] Error 2

The error message is indeed correct: my Autoconf macros (as returned by `gnulib-tool --extract-autoconf-snippet gettext`) are indeed of version 0.18.1, and the installed gettext is of version 0.19.8.1.

I'm looking for a solution which can be applied before running _autogen.sh_ (i.e. not an edit to the file _makefile.in.in_).

Thank you.

**Comment by lavv17** [comment]
should be fixed in 4.9.0
