### ISSUE TITLE
In OpenSSH_8.0p1 version, lftp does not automatically answer “yes”

### ISSUE THREAD

**Issue by gr258** [lavv17/lftp#547]
When lftp first connects to the sftp server, ssh prompts "Are you sure you want to continue connecting (yes/no/[fingerprint])?", lftp cannot automatically answer yes.
I think the following conditions are not true in SSH_Access.cc:
if(ends_with(b,b+s,"(yes/no)?"))
{
    const char *answer=QueryBool("auto-confirm",hostname)?"yes\n":"no\n";
    pty_recv_buf->Put(answer);
    pty_send_buf->Put(answer);
    return m;
}

**Comment by lavv17** [comment]
If I am not mistaken, it is already fixed in the git sources.

вт, 17 сент. 2019, 16:55 gr258 <notifications@github.com>:

**Comment by gr258** [comment]
I think the string "(yes/no/[fingerprint])?" is not ending with "(yes/no)?" because there is another string "[fingerprint]", please check it out, thank you!

**Comment by userdocs** [comment]
This is an existing issue.

https://github.com/lavv17/lftp/issues/525
