### ISSUE TITLE
Segmentation fault when calling "lftp --version"

### ISSUE THREAD

**Issue by arbyter** [lavv17/lftp#549]
lftp-Version: 4.8.4
OS-Version: macOS 10.14.6 (18G95)

When calling "lftp --version" I'm getting the regular output, but it quits with a segmentation fault error. This in turn hinders other tools from parsing the output.

`LFTP | Version 4.8.4 | Copyright (c) 1996-2017 Alexander V. Lukyanov

LFTP is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with LFTP.  If not, see <http://www.gnu.org/licenses/>.

Send bug reports and questions to the mailing list <lftp@uniyar.ac.ru>.

[1]    60381 segmentation fault  lftp --version`

**Comment by lavv17** [comment]
Please provide a stack trace using a debugger.

вс, 22 сент. 2019, 21:42 Marcus Sümnick <notifications@github.com>:

**Comment by arbyter** [comment]
I'll try this. How can I get readline-devel for macOS. I can't find any information how to download this "special" version of readline.

**Comment by arbyter** [comment]
okay, figured out to use lldb for debugging. stack trace incoming

`* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x00007fff6b4d4140 libsystem_platform.dylib`_platform_strncmp + 320
    frame #1: 0x00000001000110a3 lftp`cmd_ver(CmdExec*) + 358
    frame #2: 0x0000000100009a16 lftp`CmdExec::exec_parsed_command() + 542
    frame #3: 0x000000010000a7a3 lftp`CmdExec::Do() + 1601
    frame #4: 0x0000000100040b79 lftp`SMTask::ScheduleThis() + 83
    frame #5: 0x0000000100040a77 lftp`SMTask::Schedule() + 235
    frame #6: 0x0000000100009335 lftp`Job::WaitDone() + 37
    frame #7: 0x0000000100003961 lftp`main + 681
    frame #8: 0x00007fff6b2d5405 libdyld.dylib`start + 1`

**Comment by lavv17** [comment]
It would be nice to recompile with debug info (use configure --with-debug)
