### ISSUE TITLE
[4.8.1] mirror: <file>: file size decreased during transfer

### ISSUE THREAD

**Issue by ladislavhorky** [lavv17/lftp#551]
Hello,

I am using `lftp` version 4.8.1 from package `4.8.1-1ubuntu0.1` for Ubuntu 18.04 to recursively download directories from SFTP server, I am using command:

```
$ lftp
:~> set sftp:connect-program "ssh -a -x -i <mykey>"
:~> connect sftp://user@server
:~> mirror -P 5 <directory>
```

For a small percentage of files, I get message 

`mirror: <file>: file size decreased during transfer`

The downloaded file is one sector (4K) smaller than if I download it with `sftp` tool. The checksum of sftp-downloaded file is correct, the same checksum of lftp-downloaded is not.

There is a mix of large files (~100M) and small accompanying text files (single line of text). Only the large ones get logged although also the text files seem affected. Maybe they are to small (already fit in to a single sector) to be detected this way.

There are several reports that this have been fixed in 4.4 (https://bugs.launchpad.net/ubuntu/+source/lftp/+bug/1713270) but apparently it still happens.

**Comment by ladislavhorky** [comment]
Redownloading the same with `mirror -c ...` multiple times until it logs zero errors in final summary seem to be a workaround fixing all, even the small files.

**Comment by lavv17** [comment]
26004c5e1f6a82afbd9b6b302fc947383392f8e2 may fix it, please try.

**Comment by lavv17** [comment]
another fix may be in d90dbeeb63065fb0cb3adefcd5bc6aa8136dbf8d

**Comment by ladislavhorky** [comment]
Thx, will let you know about result when (and if :( ) I manage to get back to it.

**Comment by bsikander** [comment]
This issue still exists in 4.8.x and I have not been able to find a solution. Is there any update on the solution?

Further, why the binary for latest version 4.9.2 is not available through apt?
