### ISSUE TITLE
get1 -d race condition

### ISSUE THREAD

**Issue by cyph84** [lavv17/lftp#554]
get1 -d seems to have a race condition between starting of transfer and mkdir of the destination directory.

A command like `get1 -d -o ./test1/README.txt README.txt` will sometimes fail with 

> get1: README.txt: ./test1/README.txt: No such file or directory

Re-trying the command will result in success after a few tries.

get1 will always succeed if ./test1/ were created beforehand.

**Comment by lavv17** [comment]
Please enable debug in lftp to see what commands are being sent to the
server.

вс, 22 дек. 2019, 8:24 cyph84 <notifications@github.com>:

**Comment by cyph84** [comment]
It seems to fail after establishing data connection.

Running the command:
`get1 -d -o /tmp/1/2/test.txt 'example/test/txt'`

I get:

> [3768399] 2019-12-25 12:09:07 ftp.example.com ---> SIZE example/test.txt
> [3768399] 2019-12-25 12:09:07 ftp.example.com <--- 213 188825604                        
> [3768399] 2019-12-25 12:09:07 ftp.example.com ---> MDTM example/test.txt
> [3768399] 2019-12-25 12:09:07 ftp.example.com <--- 213 20181010144353                        
> [3768399] 2019-12-25 12:09:07 ftp.example.com ---> PASV
> [3768399] 2019-12-25 12:09:08 ftp.example.com <--- 227 Entering Passive Mode (117,25,149,175,151,78)
> [3768399] 2019-12-25 12:09:08 ftp.example.com ---- Connecting data socket to (117.25.149.175) port 38734
> [3768399] 2019-12-25 12:09:08 ftp.example.com ---- Data connection established
> [3768399] 2019-12-25 12:09:08 ftp.example.com 0:0 translated to pair 0:0 (0,0)
> [3768399] 2019-12-25 12:09:08 ftp.example.com 0 translated to pair 0:0 (0,0)
> [3768399] 2019-12-25 12:09:08 ftp.example.com 0:0 translated to pair 0:0 (0,0)
> [3768399] 2019-12-25 12:09:08 ftp.example.com 0 translated to pair 0:0 (0,0)
> [3768399] 2019-12-25 12:09:08 ftp.example.com 0:0 translated to pair 0:0 (0,0)
> [3768399] 2019-12-25 12:09:08 ftp.example.com 0 translated to pair 0:0 (0,0)
> [3768399] 2019-12-25 12:09:08 ftp.example.com ---> RETR example/test.txt
> [3768399] 2019-12-25 12:09:08 ftp.example.com <--- 150 Data connection accepted from 120.25.255.113:60980; transfer starting for /example/test.txt (188825604 bytes)
> [3768399] 2019-12-25 12:09:08 ---> ABOR
> get1: /example/test.txt: /tmp/1/2/test.txt: No such file or directory
> [3768399] 2019-12-25 12:09:09 ftp.example.com <--- 226 ABOR command successful.
> [3768399] 2019-12-25 12:09:09 ftp.example.com <--- 426-Compression : 81.96% (65.574 KBytes/80 KBytes).
> [3768399] 2019-12-25 12:09:09 ftp.example.com <--- 426 Retrieve aborted; ABORT requested by client
> [3768399] 2019-12-25 12:09:09 ftp.example.com ---- Closing aborted data socket
>
