### ISSUE TITLE
Chown?

### ISSUE THREAD

**Issue by martijintro** [lavv17/lftp#563]
Because i want to chown some remote things.

- There is NO `chown` command by native in your application
- In your manual i see i have to use the "mirror" command
  --> to add `--allow-chown` does not seems help: mirror -R --allow-chown /etc/mysql/client_cert /etc/mysql;

**Comment by martijintro** [comment]
Not possible??

**Comment by martijintro** [comment]
Do i need a build up an additional SSH connection to the remote destination, just to change the owner???

**Comment by martijintro** [comment]
Proof:

Commands:

- `chmod 0400 /etc/mysql/*.pem && chown mysql:mysql /etc/mysql/*.pem && chmod 0400 /etc/mysql/client_cert/*.pem && chown mysql:mysql /etc/mysql/client_cert/*.pem;
`
- `mirror -R --allow-chown /etc/mysql/client_cert /etc/mysql/test;`



Result on target server:

![image](https://user-images.githubusercontent.com/42765391/72353871-07883880-36e5-11ea-8d45-57535e128629.png)

So you see, the owner is still "root" - so not equivalent to the source system file owner "mysql:mysql"...


Bug or feature? ;-)

**Comment by martijintro** [comment]
Do i need to add `-s` parameter as a requirement for `--allow-chown`

-> https://lftp.yar.ru/lftp-man.html

Thx for feedback.

**Comment by lavv17** [comment]
Remote chown is not implemented, mirror can only chown local files.

If you have ssh access, then it's possible to execute lftp remotely and
pull changes.

вт, 14 янв. 2020, 17:52 martijintro <notifications@github.com>:

**Comment by martijintro** [comment]
Oh, thank you very much for your feedback! :-)

First, i was thinking it's only possible with `mirror ...`, so the files on the target will have the same owner as on the source.

"If you have ssh access, then it's possible to execute lftp remotely and
pull changes."

Instead of that, i will use the normal `chown` on the remote server - i think this is less complicated than use a lftp-based "local chmod" on the remote machine.

**Comment by lavv17** [comment]
You can also use fish protocol and "quote chown"

вт, 14 янв. 2020, 18:53 martijintro <notifications@github.com>:

**Comment by martijintro** [comment]
I never heard about that, but i will look about - thank you very much! :-)
