### ISSUE TITLE
mkdir -f causes fail-exit to occur

### ISSUE THREAD

**Issue by thomric2** [lavv17/lftp#579]
```
set cmd:fail-exit true
mkdir -pf ftp://<user>:<pass>@<IP>:<port>/folder/path`
```

Even though the error is suppressed from `-f` the script exists. This does not match how `chmod -f` operates where even if the error from chmod is suppressed the lftp session is allowed to continue.

**Comment by lavv17** [comment]
I'm not sure. -f option suppresses error message, but not the exit code. Try "mkdir -f /path || .true"

**Comment by thomric2** [comment]
Ok, will do. Wasn't sure if it was an issue since I saw differences in how chmod worked vs mkdir. I'll use that || trick then.
