### ISSUE TITLE
'configure' doesn't test for some dependencies

### ISSUE THREAD

**Issue by simonbcn** [lavv17/lftp#58]
`configure` ends with any error even when it doesn't exist the headers of ncurses and zlib.

**Comment by JoshShashaty** [comment]
Had the same issue with running `configure` and LFTP not compiling on `make` when getting the error
`lftp_tinfo.cc:53: error: 'setupterm' was not declared in this scope`

What I did was install ncurses-dev ... ran `configure` again... then `make` compiled.  

Running Ubuntu 14.04.2 LTS
Compiling LFTP 4.6.2

**Comment by Twilight** [comment]
similar here with Debian Jessie, compiling 4.6.2, found this thread and installed libncurses5-dev and libncursesw5-dev, it compiles then, dunno which one does the trick though.

**Comment by mjinks** [comment]
Did this ever get resolved? I'm trying to compile lftp 4.6.4, from upstream, and hitting what looks like the same series of errors.

**Comment by mjinks** [comment]
Correction: re-running './configure ----with-openssl=/usr/lib' seems to have done the trick. make concluded successfully.

**Comment by lavv17** [comment]
I get the error properly:
```
checking for library containing tigetstr... no
checking for library containing tgetstr... no
configure: WARNING: No terminfo
checking for readline... configure: error: need installed readline-devel package
```

**Comment by rmast** [comment]
The readline-devel package (libreadline-dev) is another issue about another package before the missing ncurses-dev, and I re-ran the './configure  --with-openssl=/usr/lib' afterward, so this thread about the missing ncurses-dev in the configure still applies.

**Comment by 2devnull** [comment]
This worked for me
```
apt-get install -y gcc build-essential automake readline-common libreadline6-dev pkg-config libgnutls-dev ncurses-dev

cd /tmp
wget http://lftp.yar.ru/ftp/lftp-4.6.5.tar.gz
gunzip lftp-4.6.5.tar.gz
tar xvf lftp-4.6.5.tar 
rm lftp-4.6.5.tar 
cd lftp-4.6.5/
./configure 
make
make install
```

**Comment by lordspace** [comment]
Hey 2devnull, your install steps worked for me.
Thanks. My thanks goes to STDOUT and not to /dev/null :smile:
