### ISSUE TITLE
local ls not work

### ISSUE THREAD

**Issue by lesar** [lavv17/lftp#584]
I'm ask [here](https://stackoverflow.com/questions/61046003/how-can-list-local-file-using-lftp) but perhaps is a bug.  

I'am on Ubuntu 19.10 and using lftp 4.8.4  

from lftp help, I see, I can use bash command using '!'
  
I like to list my local file: not remote!  
`ls` list remote file  
`!ls`, `!dir`, `!dir` list remote file too 
`lls` **unknown command**  

`lpwd` give me current local path but I like to list local file too!  
Have I to open a new terminal to list local file or is a bug?

Can you help?  
best regards,  
Leonardo

**P.S.** On man page I read:

>       !ls
>       To do a directory listing of the local host.

but not work!

**Comment by andy-burns-uk** [comment]
Did you try `local ls` ?

**Comment by lesar** [comment]
to use local ls you mean to exit from lftp and do ls?  
if so I not think this is useful: I think work in lftp on one terminal (one windows) is more productive.

regards,
Leonardo

**Comment by andy-burns-uk** [comment]
No, I mean use `local ls` as a command within lftp, just as you were using `lpwd` as a command

**Comment by lesar** [comment]
Silly me,
reading the man I notice the !ls that not work but have not see 
`local command`
below 
thank you very match, 
sorry
