### ISSUE TITLE
Command results not available

### ISSUE THREAD

**Issue by GitsBaud** [lavv17/lftp#587]
Hi there,
Thanks in advance for your time
What I want to achieve was already discussed on issue #330 but not a proper solution was given 

I'm using lftp as below :
`lftp sftp://{username}:{passwd}@{server_name} -e "cd dir1/; lcd dir2/; mget file1_*.csv; bye" 2>&1 | awk 'some_code'` inside a bash script, launched by a cronjob

I execute this line in a terminal and I get a result/status for each command so for instance : 
cd ok, cwd=dir1/
lcd ok, local cwd=dir2/
XX bytes transferred

**I'd like to make them appear in a log file now**

Although from a terminal again it's working well : 
`my_lftp_command_above > output.log 2>&1` writes in the log file the same output

When using cronjob it doesn't work any longer : 
-1-
`
#!/bin/bash
my_lftp_command_above > output.log 2>&1
exit
`
and 
`
18 22 * * 3 /tmp/script.sh
`
or
-2-
`
#!/bin/bash
my_lftp_command_above 2>&1
exit
`
and 
`
18 22 * * 3 /tmp/script.sh > output.log 
`
in both cases, output.log is empty

However, from cronjob or terminal, I do get the result I'm expecting if the lftp command somehow fails (using a wrong username for example)

I see a comment from @lavv17 "The status line is not shown when the output is not a terminal.". Is there a way they still can end up in my log file ?

Also tried with `-d` but got unlucky 

Thanks very much
Guillaume

**Comment by lavv17** [comment]
Try "set cmd:verbose yes" and "set cmd:interactive yes"

**Comment by GitsBaud** [comment]
Hey ! It does the trick ! Thanks
