### ISSUE TITLE
Does LFTP work with EPSV as passive mode?

### ISSUE THREAD

**Issue by andreswatson** [lavv17/lftp#628]
Hi, not sure if LFTP is properly working when I set   **ftp:prefer-epsv**

I'm still getting an error "The given address is not yours" as I'm behind a NAT, but using PASSIVE MODE and EPSV must be the solution.

Any ideas?

**Comment by guayerd** [comment]
I'm still not being able to make `lftp` work in extended passive mode...

**Comment by andreswatson** [comment]
Solved.

**Comment by Arun-Narasimhan** [comment]
Hi @andreswatson, can you please post how did you solve this? I am facing the same issue. LFTP uses only PASV. I tried setting **set ftp:prefer-epsv true**  and **set ftp:prefer-epsv yes**

Both did not work. The server supports EPSV.
